//! AI Semantic tools — 2 tools for embeddings and semantic cleaning
//!
//! Tools: semantic_cleaner, search_obsidian
//!
//! Tool functions are always registered. `semantic_cleaner` runs when a
//! semantic cleaner is injected into the `Container` (constructed behind the
//! `ai` feature); without one it returns an honest feature-gated error.
//! `search_obsidian` requires `embedding_port`, `note_repository`, and
//! `text_chunker` to be injected (#386); without them it returns an honest
//! feature-gated error.
//!
//! ## Test-coverage exception (issue #516, task 4)
//! The success paths of both handlers require the ONNX semantic-cleaning
//! model (`--features ai`) and call ports whose traits (`SemanticCleaner`,
//! `EmbeddingPort`, `NoteRepository`, `TextChunker`) are sealed to
//! `webfang_core`, so no stub can be injected from this crate's unit tests.
//! Only the model-free error/validation branches are therefore unit-tested,
//! which leaves `ai.rs` at ~65% line coverage. It is **intentionally exempt**
//! from the ≥70% per-handler line-coverage gate. The model-dependent paths are
//! exercised by the integration harness under the `ai` feature.

use super::McpHandler;
use crate::mcp_server::params::*;
use rmcp::handler::server::tool::ToolRouter;
use rmcp::handler::server::wrapper::Parameters;
use rmcp::tool;
use rmcp::tool_router;
use rmcp::{model::CallToolResult, model::Content, ErrorData as McpError};
use tracing::instrument;
use webfang_core::application::vault_search::{SyncSummary, VaultSearchResult, VaultSearchService};
use webfang_core::domain::DocumentChunk;
use webfang_core::infrastructure::obsidian::{detect_vault, VaultFsReader};

/// Build an honest tool error (`isError:true`) carrying a Spanish message.
///
/// Shared by the AI handlers so feature-gated and operational failures are
/// reported as `CallToolResult::error` — never an MCP protocol error, never a
/// false success. Mirrors the slice-1 export handlers (see `export.rs`).
fn honest_error(message: impl Into<String>) -> CallToolResult {
    CallToolResult::error(vec![Content::text(message.into())])
}

/// Success envelope for `semantic_cleaner` (REQ-01).
///
/// Embeddings are inline and full — each chunk carries its vector (truncating
/// would violate REQ-01). The summary fields give a quick overview without
/// scanning `documents`.
#[derive(serde::Serialize)]
struct SemanticCleanResponse {
    /// The URL that was fetched and cleaned.
    url: String,
    /// Number of semantic chunks produced.
    chunks: usize,
    /// Embedding dimensionality (0 when the cleaner produced no embeddings).
    embedding_dim: usize,
    /// The cleaned chunks, each with its embedding populated.
    documents: Vec<DocumentChunk>,
}

/// Success envelope for `search_obsidian` (#386).
#[derive(serde::Serialize)]
struct VaultSearchResponse {
    /// The search query.
    query: String,
    /// Number of results returned.
    results: usize,
    /// The matching note chunks, sorted by descending relevance.
    documents: Vec<VaultSearchResult>,
}

#[tool_router(router = tool_router_ai, vis = "pub")]
// Allow: the `tool_router_ai` fn generated by rmcp-macros cannot be documented from this crate.
#[allow(missing_docs)]
impl McpHandler {
    /// Semantic HTML cleaning with AI embeddings
    ///
    /// Fetches a URL, cleans its HTML content, and returns semantically
    /// chunked content with embeddings. Requires the `ai` feature.
    ///
    /// Respects SSRF protection and the site's robots.txt: a disallowed URL
    /// is rejected with a `robots.txt` error before any fetch — even with the
    /// `ai` feature off (#749, uniform with #697).
    #[tool(
        description = "Fetch a URL, semantically clean its HTML content using AI embeddings, and return chunked content with vectors. Requires --features ai."
    )]
    #[instrument(skip(self), fields(url = %params.url))]
    async fn semantic_cleaner(
        &self,
        Parameters(params): Parameters<ScrapeUrlParams>,
    ) -> Result<CallToolResult, McpError> {
        params.validate()?;

        let _permit = acquire_semaphore!(self, ai);

        // REQ-03: reject malformed URLs first (invalid-params), regardless of
        // cleaner presence — no fetch, no cleaning.
        let url = url::Url::parse(&params.url).map_err(|e| {
            McpError::invalid_params(
                format!("URL inválida: {e}"),
                Some(serde_json::Value::String("url".to_string())),
            )
        })?;

        // #749 fold-in: this tool fetched the caller URL without the SSRF
        // guard every other URL-fetching tool has.
        crate::mcp_server::ssrf::validate_url_no_ssrf(&url).await?;
        // #749: robots.txt gate BEFORE the cleaner-presence check — site
        // policy is independent of local feature state, so a denial is
        // reported even with the `ai` feature off.
        if let Some(err) = self.state.robots_denied_for(&url).await {
            return Ok(honest_error(err.to_string()));
        }

        // REQ-02: absent cleaner (ai feature off) -> honest Spanish error.
        let Some(cleaner) = self.state.container.cleaner() else {
            return Ok(honest_error(
                "funcionalidad no disponible: limpieza semántica con IA. Reconstruye con --features ai para habilitarla.",
            ));
        };

        // REQ-01: fetch the page via the existing HTTP port, then clean it.
        // Operational failures map to honest errors — never a false success.
        let response = match self.state.container.http_client().get(&params.url).await {
            Ok(resp) => resp,
            Err(e) => return Ok(honest_error(format!("no se pudo obtener la página: {e}"))),
        };
        let documents = match cleaner.clean(&params.url, &response.body).await {
            Ok(docs) => docs,
            Err(e) => return Ok(honest_error(format!("error al limpiar el contenido: {e}"))),
        };

        let chunks = documents.len();
        let embedding_dim = documents
            .first()
            .and_then(|doc| doc.embeddings.as_ref())
            .map(Vec::len)
            .unwrap_or(0);
        let envelope = SemanticCleanResponse {
            url: params.url.clone(),
            chunks,
            embedding_dim,
            documents,
        };
        let payload = match serde_json::to_string(&envelope) {
            Ok(json) => json,
            Err(e) => {
                return Ok(honest_error(format!(
                    "error al serializar la respuesta: {e}"
                )))
            },
        };
        Ok(CallToolResult::success(vec![Content::text(payload)]))
    }

    /// Semantic search over Obsidian vault using embeddings
    ///
    /// Searches indexed vault notes by embedding the query and ranking
    /// against pre-computed chunk embeddings via cosine similarity.
    /// Requires `embedding_port`, `note_repository`, and `text_chunker`
    /// to be injected into the Container (#386).
    #[tool(
        description = "Semantic search over Obsidian vault using ONNX Runtime embeddings. Returns top matching notes by cosine similarity. Requires --features ai."
    )]
    #[instrument(skip(self), fields(query = %params.query))]
    async fn search_obsidian(
        &self,
        Parameters(params): Parameters<SearchObsidianParams>,
    ) -> Result<CallToolResult, McpError> {
        params.validate()?;

        let _permit = acquire_semaphore!(self, obsidian);

        // Check all three required ports are available.
        let Some(embedding) = self.state.container.embedding_port() else {
            return Ok(honest_error(
                "funcionalidad no disponible: búsqueda semántica en Obsidian. Reconstruye con --features ai para habilitarla.",
            ));
        };
        let Some(repo) = self.state.container.note_repository() else {
            return Ok(honest_error(
                "funcionalidad no disponible: no hay repositorio de notas configurado. Verifica la configuración de persistencia.",
            ));
        };
        let Some(chunker) = self.state.container.text_chunker() else {
            return Ok(honest_error(
                "funcionalidad no disponible: no hay chunker de texto configurado. Reconstruye con --features ai.",
            ));
        };

        // Vault reader: prefer the Container-injected port; fall back to the
        // default fs adapter so the tool keeps working without extra wiring
        // (ADR-0012-B sub-slice 3.I, #1071).
        let note_reader = self
            .state
            .container
            .vault_note_reader()
            .unwrap_or_else(|| std::sync::Arc::new(VaultFsReader));
        let service = VaultSearchService::new(embedding, repo, chunker, note_reader);
        let limit = params.limit.unwrap_or(10);

        // Lazy sync: reconcile the vault filesystem against the index
        // before searching. Uses the explicit vault_path param or falls
        // back to auto-detection. Sync failures are non-fatal — we
        // proceed with whatever is already indexed.
        let vault_path = params
            .vault_path
            .clone()
            .or_else(|| detect_vault(None, None, None).map(|p| p.to_string_lossy().into_owned()));
        if let Some(vp) = &vault_path {
            match service.sync_vault(std::path::Path::new(vp)).await {
                Ok(SyncSummary {
                    indexed,
                    updated,
                    deleted,
                    unchanged,
                }) => {
                    tracing::info!(
                        indexed,
                        updated,
                        deleted,
                        unchanged,
                        vault_path = %vp,
                        "lazy vault sync completed before search"
                    );
                },
                Err(e) => {
                    tracing::warn!(
                        vault_path = %vp,
                        "vault sync failed, searching existing index: {e}"
                    );
                },
            }
        }

        match service.search(&params.query, limit).await {
            Ok(results) => {
                let envelope = VaultSearchResponse {
                    query: params.query.clone(),
                    results: results.len(),
                    documents: results,
                };
                match serde_json::to_string(&envelope) {
                    Ok(json) => Ok(CallToolResult::success(vec![Content::text(json)])),
                    Err(e) => Ok(honest_error(format!(
                        "error al serializar la respuesta: {e}"
                    ))),
                }
            },
            Err(e) => Ok(honest_error(format!("error en la búsqueda semántica: {e}"))),
        }
    }
}

/// Build the AI semantic tools router (semantic_cleaner, search_obsidian).
///
/// Returns a partial router that is combined with the other category routers
/// via the `+` operator in
/// [`build_tool_router`](crate::mcp_server::handlers::build_tool_router).
pub fn build_router() -> ToolRouter<McpHandler> {
    McpHandler::tool_router_ai()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::mcp_server::state::McpState;
    use rmcp::handler::server::wrapper::Parameters;
    use rmcp::model::CallToolResult;
    use serial_test::serial;
    use tempfile::TempDir;
    use webfang_core::di::Container;
    use webfang_core::domain::CrawlerConfig;
    use webfang_core::domain::config::ScraperConfig;
    use webfang_core::infrastructure::crawler::robots_utils::RobotsFetcher;
    use wiremock::matchers::{method, path};
    use wiremock::{Mock, MockServer, ResponseTemplate};

    /// REQ-02/04 contract: `honest_error` produces a `CallToolResult` that
    /// serializes with `isError:true` and carries the exact Spanish text —
    /// never a protocol error, never a false success. Mirrors the slice-1
    /// export-handler test (export.rs).
    #[test]
    fn honest_error_sets_is_error_and_spanish_text() {
        let result = honest_error("funcionalidad no disponible: prueba");

        // Serialize exactly as the MCP transport would, then assert the honest
        // error contract: isError:true plus the Spanish message.
        let json = serde_json::to_value(&result).expect("CallToolResult must serialize");
        assert_eq!(
            json.get("isError").and_then(|v| v.as_bool()),
            Some(true),
            "honest_error must set isError:true, got: {json}"
        );
        let text = json
            .get("content")
            .and_then(|c| c.as_array())
            .and_then(|arr| arr.first())
            .and_then(|first| first.get("text"))
            .and_then(|t| t.as_str())
            .unwrap_or_default();
        assert!(
            text.contains("funcionalidad no disponible"),
            "honest Spanish error text expected, got: {text}"
        );
    }

    /// Build a default handler (no cleaner / embedding ports injected) backed by
    /// a real DI container. The `ai` feature is off in unit tests, so the
    /// cleaner and embedding ports are `None` — exactly the branch these tests
    /// exercise (honest feature-gated errors, no ONNX model needed).
    ///
    /// The robots fetcher is dropped for determinism (#705/#749): with
    /// `None`, the robots gate is no-op and never touches the network against
    /// the real hosts these validation tests use; tests that exercise
    /// enforcement wire a fetcher explicitly (see the #749 robots tests).
    async fn test_handler() -> (McpHandler, TempDir) {
        let (mut state, tmp) = test_state().await;
        state.robots_fetcher = None;
        (McpHandler::new(state), tmp)
    }

    /// Build a state with a real robots fetcher for #749 enforcement tests.
    /// Offline-friendly: construction never touches the network.
    async fn test_handler_with_robots() -> (McpHandler, TempDir) {
        let (state, tmp) = test_state().await;
        let state = state.with_robots_fetcher(std::sync::Arc::new(
            RobotsFetcher::with_default_profile(5).expect("fetcher construction is offline"),
        ));
        (McpHandler::new(state), tmp)
    }

    /// Shared state construction for `test_handler` /
    /// `test_handler_with_robots` (kept in one place so both states build on
    /// the identical baseline). The `TempDir` is returned so the caller keeps
    /// the configured `output_dir` alive.
    async fn test_state() -> (McpState, TempDir) {
        let tmp = TempDir::new().expect("create temp dir");
        let crawler_config =
            CrawlerConfig::new(url::Url::parse("https://example.com").expect("valid url"));
        let scraper_config = ScraperConfig {
            output_dir: tmp.path().to_path_buf(),
            ..Default::default()
        };
        let container = Container::new(crawler_config, scraper_config)
            .await
            .expect("create container");
        (McpState::new(container), tmp)
    }

    fn result_text(result: &CallToolResult) -> String {
        serde_json::to_value(result)
            .ok()
            .and_then(|v| v.get("content").and_then(|c| c.as_array()).cloned())
            .and_then(|arr| arr.first().cloned())
            .and_then(|first| {
                first
                    .get("text")
                    .and_then(|t| t.as_str())
                    .map(str::to_owned)
            })
            .unwrap_or_default()
    }

    /// REQ-03: a malformed URL must be rejected with `McpError::invalid_params`
    /// before any fetch/clean — no honest-error envelope, a real protocol error.
    #[tokio::test]
    async fn semantic_cleaner_invalid_url_is_invalid_params() {
        let (handler, _tmp) = test_handler().await;
        let res = handler
            .semantic_cleaner(Parameters(ScrapeUrlParams {
                url: "not a url".to_string(),
            }))
            .await;
        assert!(
            res.is_err(),
            "invalid URL must return McpError, got: {res:?}"
        );
    }

    /// REQ-02: a valid URL with no cleaner injected (ai feature off) maps to an
    /// honest Spanish `isError:true` envelope — never a false success.
    #[tokio::test]
    #[serial] // WEBFANG_MCP_DISABLE_SSRF is process-global — see scraping.rs
    async fn semantic_cleaner_no_cleaner_is_honest_feature_error() {
        // #749 made SSRF/robots gates run before the cleaner check; keep this
        // feature-gated test hermetic (offline) by disabling the SSRF probe —
        // the robots gate is already a no-op in `test_handler`.
        std::env::set_var("WEBFANG_MCP_DISABLE_SSRF", "1");
        let (handler, _tmp) = test_handler().await;
        let res = handler
            .semantic_cleaner(Parameters(ScrapeUrlParams {
                url: "https://example.com/article".to_string(),
            }))
            .await
            .expect("semantic_cleaner returns Ok with honest error");
        let json = serde_json::to_value(&res).expect("CallToolResult serializes");
        assert_eq!(
            json.get("isError").and_then(|v| v.as_bool()),
            Some(true),
            "missing cleaner must set isError:true, got: {json}"
        );
        let text = result_text(&res);
        assert!(
            text.contains("--features ai") && text.contains("limpieza semántica"),
            "Spanish feature-gated message expected, got: {text}"
        );
    }

    /// #749: a robots-disallowed URL is rejected with an honest `robots.txt`
    /// error BEFORE the page fetch — even without a cleaner, since the robots
    /// gate precedes the cleaner-presence check (site policy is independent
    /// of local feature state).
    #[cfg_attr(miri, ignore)] // real network stack via wreq — unsupported by Miri
    #[tokio::test]
    #[serial]
    async fn semantic_cleaner_robots_disallowed_errors_before_fetch_and_cleaner_check() {
        std::env::set_var("WEBFANG_MCP_DISABLE_SSRF", "1"); // wiremock binds 127.0.0.1
        let (handler, _tmp) = test_handler_with_robots().await;
        let server = MockServer::start().await;
        Mock::given(method("GET"))
            .and(path("/robots.txt"))
            .respond_with(
                ResponseTemplate::new(200).set_body_string("User-agent: *\nDisallow: /private\n"),
            )
            .mount(&server)
            .await;

        let res = handler
            .semantic_cleaner(Parameters(ScrapeUrlParams {
                url: format!("{}/private/page", server.uri()),
            }))
            .await
            .expect("semantic_cleaner returns Ok with honest error");

        let json = serde_json::to_value(&res).expect("CallToolResult serializes");
        assert_eq!(
            json.get("isError").and_then(|v| v.as_bool()),
            Some(true),
            "robots denial must set isError:true, got: {json}"
        );
        let text = result_text(&res);
        assert!(
            text.contains("robots.txt"),
            "error text must report the robots.txt denial, got: {text}"
        );
        let page_hits = server
            .received_requests()
            .await
            .expect("request recording is enabled")
            .iter()
            .filter(|r| r.url.path() != "/robots.txt")
            .count();
        assert_eq!(page_hits, 0, "the robots gate must block the page fetch");
    }

    /// `search_obsidian` with no embedding port injected maps to an honest
    /// Spanish `isError:true` envelope (feature-gated path).
    #[tokio::test]
    async fn search_obsidian_no_embedding_is_honest_feature_error() {
        let (handler, _tmp) = test_handler().await;
        let res = handler
            .search_obsidian(Parameters(SearchObsidianParams {
                query: "rust async".to_string(),
                vault_path: None,
                limit: None,
            }))
            .await
            .expect("search_obsidian returns Ok with honest error");
        let json = serde_json::to_value(&res).expect("CallToolResult serializes");
        assert_eq!(
            json.get("isError").and_then(|v| v.as_bool()),
            Some(true),
            "missing embedding port must set isError:true, got: {json}"
        );
        let text = result_text(&res);
        assert!(
            text.contains("--features ai") && text.contains("búsqueda semántica"),
            "Spanish feature-gated message expected, got: {text}"
        );
    }

    /// `build_router` returns the AI-tool partial router without panicking.
    #[test]
    fn build_router_returns_ai_router() {
        let router = build_router();
        // Non-ZST assert keeps the value live and confirms the function ran.
        assert!(std::mem::size_of_val(&router) > 0);
    }
}
