//! Asset Management tools — 1 tool for downloading images/documents
//!
//! Tools: download_assets

use super::McpHandler;
use crate::mcp_server::params::*;
use rmcp::handler::server::tool::ToolRouter;
use rmcp::handler::server::wrapper::Parameters;
use rmcp::tool;
use rmcp::tool_router;
use rmcp::{model::CallToolResult, model::Content, ErrorData as McpError};
use tracing::instrument;

#[tool_router(router = tool_router_assets, vis = "pub")]
// Allow: the `tool_router_assets` fn generated by rmcp-macros cannot be documented from this crate.
#[allow(missing_docs)]
impl McpHandler {
    /// Download images and documents from HTML into the output directory.
    ///
    /// The boolean toggles `images` (default: true) and `documents`
    /// (default: false) select which asset kinds are downloaded. Files are
    /// written with SHA-256 hashed filenames; the response reports each
    /// downloaded asset with its local path.
    #[tool(
        description = "Download images (default: true) and/or documents (default: false) referenced in HTML content into the output directory (SHA-256 hashed filenames). 'images' and 'documents' are boolean toggles, not URL lists. Returns the downloaded assets with their local paths. For a full scrape that also downloads assets, use scrape_with_options with download_images/download_documents."
    )]
    #[instrument(skip(self), fields(base_url = %params.base_url, images = params.images.unwrap_or(true), documents = params.documents.unwrap_or(false), output_dir = ?params.output_dir))]
    async fn download_assets(
        &self,
        Parameters(params): Parameters<DownloadAssetsParams>,
    ) -> Result<CallToolResult, McpError> {
        params.validate()?;

        let _permit = acquire_semaphore!(self, assets);

        let base_url = url::Url::parse(&params.base_url).map_err(|e| {
            McpError::invalid_params(
                format!("invalid base URL: {e}"),
                Some(serde_json::Value::String("base_url".to_string())),
            )
        })?;

        let mut config = webfang_core::infrastructure::config::ScraperConfig {
            download_images: params.images.unwrap_or(true),
            download_documents: params.documents.unwrap_or(false),
            ..Default::default()
        };
        if let Some(ref output_dir) = params.output_dir {
            config.output_dir = std::path::PathBuf::from(output_dir);
        }

        // Shared downloader when injected (connection pooling across calls);
        // None falls back to a per-call Downloader built from the config.
        let dl = self
            .state
            .downloader
            .as_deref()
            .map(|d| d as &dyn webfang_core::domain::ports::AssetDownloaderPort);

        match webfang_core::application::scraper_service::download_assets_if_enabled(
            &params.html,
            &base_url,
            &config,
            dl,
        )
        .await
        {
            Ok(assets) => {
                tracing::info!(
                    downloaded = assets.len(),
                    images = config.download_images,
                    documents = config.download_documents,
                    "assets downloaded"
                );
                let content = serde_json::to_string_pretty(&assets)
                    .unwrap_or_else(|_| "failed to serialize".into());
                Ok(CallToolResult::success(vec![Content::text(content)]))
            },
            Err(e) => Ok(CallToolResult::error(vec![Content::text(e.to_string())])),
        }
    }
}

/// Build the asset management router (download_assets).
///
/// Returns a partial router that is combined with the other category routers
/// via the `+` operator in
/// [`build_tool_router`](crate::mcp_server::handlers::build_tool_router).
pub fn build_router() -> ToolRouter<McpHandler> {
    McpHandler::tool_router_assets()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::mcp_server::state::McpState;
    use rmcp::handler::server::wrapper::Parameters;
    use rmcp::model::CallToolResult;
    use tempfile::TempDir;
    use webfang_core::di::Container;
    use webfang_core::domain::CrawlerConfig;
    use webfang_core::infrastructure::config::ScraperConfig;
    use wiremock::matchers::{method, path};
    use wiremock::{Mock, MockServer, ResponseTemplate};

    async fn test_handler() -> (McpHandler, TempDir) {
        let tmp = TempDir::new().expect("create temp dir");
        let crawler_config =
            CrawlerConfig::new(url::Url::parse("https://example.com").expect("valid url"));
        let scraper_config = ScraperConfig {
            output_dir: tmp.path().to_path_buf(),
            ..Default::default()
        };
        let container = Container::new(crawler_config, scraper_config)
            .await
            .expect("create container");
        let state = McpState::new(container);
        (McpHandler::new(state), tmp)
    }

    fn result_text(result: &CallToolResult) -> String {
        serde_json::to_value(result)
            .ok()
            .and_then(|v| v.get("content").and_then(|c| c.as_array()).cloned())
            .and_then(|arr| arr.first().cloned())
            .and_then(|first| {
                first
                    .get("text")
                    .and_then(|t| t.as_str())
                    .map(str::to_owned)
            })
            .unwrap_or_default()
    }

    #[tokio::test]
    async fn download_assets_invalid_base_url_is_invalid_params() {
        let (handler, _tmp) = test_handler().await;
        let res = handler
            .download_assets(Parameters(DownloadAssetsParams {
                html: "<html></html>".to_string(),
                base_url: "not a url".to_string(),
                images: None,
                documents: None,
                output_dir: None,
            }))
            .await;
        assert!(res.is_err(), "invalid base URL must be a protocol error");
    }

    #[tokio::test]
    async fn download_assets_no_assets_is_empty_success() {
        let (handler, _tmp) = test_handler().await;
        // `output_dir` must be a safe relative path (params validation, #512).
        let out_dir = "test-output/download-assets-empty";
        let _ = std::fs::remove_dir_all(out_dir);
        let res = handler
            .download_assets(Parameters(DownloadAssetsParams {
                html: "<html><body><p>no images here</p></body></html>".to_string(),
                base_url: "https://example.com/".to_string(),
                images: Some(true),
                documents: None,
                output_dir: Some(out_dir.to_string()),
            }))
            .await
            .expect("download_assets returns Ok");
        let text = result_text(&res);
        assert!(
            text.contains("[]"),
            "no assets must yield an empty list: {text}"
        );
        let _ = std::fs::remove_dir_all(out_dir);
    }

    #[tokio::test]
    async fn download_assets_downloads_image_from_html() {
        let (handler, _tmp) = test_handler().await;
        // `output_dir` must be a safe relative path (params validation, #512).
        let out_dir = "test-output/download-assets-image";
        let _ = std::fs::remove_dir_all(out_dir);
        let server = MockServer::start().await;
        // The page references an image; wiremock serves it so the download
        // path executes against a real (ephemeral) HTTP endpoint.
        Mock::given(method("GET"))
            .and(path("/img/logo.png"))
            .respond_with(
                ResponseTemplate::new(200)
                    .set_body_bytes(b"fake-png-bytes")
                    .insert_header("content-type", "image/png"),
            )
            .mount(&server)
            .await;

        let html = format!(
            r#"<html><body><img src="{}/img/logo.png"></body></html>"#,
            server.uri()
        );
        let res = handler
            .download_assets(Parameters(DownloadAssetsParams {
                html,
                base_url: server.uri(),
                images: Some(true),
                documents: None,
                output_dir: Some(out_dir.to_string()),
            }))
            .await
            .expect("download_assets returns Ok");
        let text = result_text(&res);
        // At least one asset downloaded and its local path reported.
        assert!(
            text.contains("logo.png") || text.contains("assets") || text.contains(".png"),
            "downloaded asset must be reported: {text}"
        );
        let _ = std::fs::remove_dir_all(out_dir);
    }
}
