//! Accessibility-tree snapshot tool — 1 tool: get_accessibility_snapshot
//!
//! The tool is always registered. With the `chromium` feature it returns a
//! compact interactive AXTree snapshot (CDP `Accessibility.getFullAXTree`);
//! without it, an honest Spanish feature-gated error (ai.rs pattern, #386).

use super::McpHandler;
use crate::mcp_server::params::*;
use rmcp::handler::server::tool::ToolRouter;
use rmcp::handler::server::wrapper::Parameters;
use rmcp::tool;
use rmcp::tool_router;
use rmcp::{model::CallToolResult, model::Content, ErrorData as McpError};
use tracing::instrument;
use webfang_core::domain::CorrelationId;
use webfang_core::infrastructure::observability::log_scrape_error;

#[cfg(feature = "chromium")]
use webfang_core::infrastructure::axtree::{
    fetch_axtree_snapshot, fetch_playwright_snapshot, SnapshotFormat,
};

/// Build an honest tool error (`isError:true`) carrying a Spanish message
/// (same contract as `ai.rs` / `export.rs`).
fn honest_error(message: impl Into<String>) -> CallToolResult {
    CallToolResult::error(vec![Content::text(message.into())])
}

#[tool_router(router = tool_router_axtree, vis = "pub")]
// Allow: the `tool_router_axtree` fn generated by rmcp-macros cannot be documented from this crate.
#[allow(missing_docs)]
impl McpHandler {
    /// Compact accessibility-tree snapshot of a rendered page
    ///
    /// Fetches the page's accessibility tree via CDP
    /// `Accessibility.getFullAXTree`, then serializes interactive elements as
    /// `@eN`-referenced nodes with a `token_estimate`. Requires the
    /// `chromium` feature.
    ///
    /// Refs (`@eN` for compact, `eN` for playwright-mcp) are snapshot-scoped
    /// and become stale after any page mutation or selector change — callers
    /// MUST re-snapshot before reusing a prior `eN` (R7 stale-ref contract).
    #[tool(
        description = "Fetch a rendered page's accessibility tree and return a compact snapshot of interactive elements with @eN refs and a token_estimate. Refs are snapshot-scoped and stale after any page mutation or selector change — re-snapshot before reuse. Requires --features chromium."
    )]
    #[instrument(skip(self), fields(url = %params.url, interactive_only = params.interactive_only, format = ?params.format, trace_id = tracing::field::Empty))]
    async fn get_accessibility_snapshot(
        &self,
        Parameters(params): Parameters<GetAccessibilitySnapshotParams>,
    ) -> Result<CallToolResult, McpError> {
        let root_correlation = CorrelationId::new();
        tracing::Span::current().record(
            "trace_id",
            tracing::field::display(root_correlation.trace_id()),
        );
        params.validate()?;

        let _permit = acquire_semaphore!(self, scraping);

        // #1116: the URL was parsed+hardened at the deserialization boundary
        // (`McpUrl`); the old re-parse — and its now-unreachable
        // `axtree.validate_url` error log — are gone.
        let url = params.url.as_url();

        if let Err(e) = crate::mcp_server::ssrf::validate_url_no_ssrf(url).await {
            log_scrape_error(
                &e,
                url.as_str(),
                "axtree.validate_ssrf",
                Some(&root_correlation),
                "SSRF validation failed",
            );
            return Err(e);
        }

        fetch_snapshot(
            url,
            params.interactive_only,
            params.selector.as_deref(),
            params.format,
            &root_correlation,
        )
        .await
    }
}

/// Chromium-enabled path: run the core engine and surface failures as honest
/// Spanish errors (spec R5). Refs in the returned `Content::text` are
/// snapshot-scoped; callers MUST re-snapshot after any page mutation or
/// selector change before reusing a prior `eN` (R7 stale-ref contract).
#[cfg(feature = "chromium")]
#[tracing::instrument(skip_all, fields(format = %format!("{format:?}"), ref_count, token_estimate, trace_id = %correlation.trace_id()))]
async fn fetch_snapshot(
    url: &url::Url,
    interactive_only: bool,
    selector: Option<&str>,
    format: SnapshotFormatParams,
    correlation: &CorrelationId,
) -> Result<CallToolResult, McpError> {
    let child = correlation.child();
    match format {
        SnapshotFormatParams::Compact => {
            let core_format = SnapshotFormat::Compact;
            match fetch_axtree_snapshot(url, interactive_only, selector, core_format).await {
                Ok(snapshot) => {
                    tracing::Span::current().record("ref_count", snapshot.nodes.len());
                    tracing::Span::current().record("token_estimate", snapshot.token_estimate);
                    tracing::info!(
                        token_estimate = snapshot.token_estimate,
                        ref_count = snapshot.nodes.len(),
                        trace_id = %child.trace_id(),
                        "axtree snapshot produced"
                    );
                    match serde_json::to_string(&snapshot) {
                        Ok(json) => Ok(CallToolResult::success(vec![Content::text(json)])),
                        Err(e) => {
                            log_scrape_error(
                                &e,
                                url.as_str(),
                                "axtree.serialize",
                                Some(&child),
                                "compact snapshot serialization failed",
                            );
                            Ok(honest_error(format!(
                                "error al serializar la respuesta: {e}"
                            )))
                        },
                    }
                },
                Err(e) => {
                    log_scrape_error(
                        &e,
                        url.as_str(),
                        "axtree.fetch_compact",
                        Some(&child),
                        "compact snapshot fetch failed",
                    );
                    Ok(honest_error(format!(
                        "no se pudo obtener el árbol de accesibilidad: {e}"
                    )))
                },
            }
        },
        SnapshotFormatParams::PlaywrightMcp => {
            match fetch_playwright_snapshot(url, interactive_only, selector).await {
                Ok(snapshot) => {
                    tracing::Span::current().record("ref_count", snapshot.ref_count);
                    tracing::Span::current().record("token_estimate", snapshot.token_estimate);
                    tracing::info!(
                        token_estimate = snapshot.token_estimate,
                        ref_count = snapshot.ref_count,
                        trace_id = %child.trace_id(),
                        "axtree playwright snapshot produced"
                    );
                    Ok(CallToolResult::success(vec![Content::text(
                        snapshot.content,
                    )]))
                },
                Err(e) => {
                    log_scrape_error(
                        &e,
                        url.as_str(),
                        "axtree.fetch_playwright",
                        Some(&child),
                        "playwright snapshot fetch failed",
                    );
                    Ok(honest_error(format!(
                        "no se pudo obtener el árbol de accesibilidad: {e}"
                    )))
                },
            }
        },
    }
}

/// Feature-off path: honest Spanish error (ai.rs pattern, #386).
#[cfg(not(feature = "chromium"))]
async fn fetch_snapshot(
    _url: &url::Url,
    _interactive_only: bool,
    _selector: Option<&str>,
    _format: SnapshotFormatParams,
    _correlation: &CorrelationId,
) -> Result<CallToolResult, McpError> {
    Ok(honest_error(
        "funcionalidad no disponible: captura del árbol de accesibilidad. Reconstruye con --features chromium para habilitarla.",
    ))
}

/// Build the accessibility-tools router (get_accessibility_snapshot).
///
/// Returns a partial router combined with the other category routers via the
/// `+` operator in [`build_tool_router`](crate::mcp_server::handlers::build_tool_router).
pub fn build_router() -> ToolRouter<McpHandler> {
    McpHandler::tool_router_axtree()
}

#[cfg(test)]
mod tests {
    use super::*;
    #[cfg(not(feature = "chromium"))]
    use crate::mcp_server::state::McpState;
    #[cfg(not(feature = "chromium"))]
    use rmcp::handler::server::wrapper::Parameters;
    #[cfg(not(feature = "chromium"))]
    use serial_test::serial;
    #[cfg(not(feature = "chromium"))]
    use tempfile::TempDir;
    #[cfg(not(feature = "chromium"))]
    use webfang_core::di::Container;
    #[cfg(not(feature = "chromium"))]
    use webfang_core::domain::config::ScraperConfig;
    #[cfg(not(feature = "chromium"))]
    use webfang_core::domain::CrawlerConfig;

    /// Test helper: build an `McpUrl` from a KNOWN-VALID http(s) string.
    #[cfg(not(feature = "chromium"))]
    fn vu(s: &str) -> crate::mcp_server::params::McpUrl {
        s.parse().expect("test url must be valid http(s)")
    }

    /// Build a default handler (no chromium — unit tests run with default
    /// features) backed by a real DI container. Offline: construction never
    /// touches the network.
    #[cfg(not(feature = "chromium"))]
    async fn test_handler() -> (McpHandler, TempDir) {
        let tmp = TempDir::new().expect("create temp dir");
        let crawler_config =
            CrawlerConfig::new(url::Url::parse("https://example.com").expect("valid url"));
        let scraper_config = ScraperConfig {
            output_dir: tmp.path().to_path_buf(),
            ..Default::default()
        };
        let container = Container::new(crawler_config, scraper_config)
            .await
            .expect("create container");
        (McpHandler::new(McpState::new(container)), tmp)
    }

    #[cfg(not(feature = "chromium"))]
    fn result_text(result: &CallToolResult) -> String {
        serde_json::to_value(result)
            .ok()
            .and_then(|v| v.get("content").and_then(|c| c.as_array()).cloned())
            .and_then(|arr| arr.first().cloned())
            .and_then(|first| {
                first
                    .get("text")
                    .and_then(|t| t.as_str())
                    .map(str::to_owned)
            })
            .unwrap_or_default()
    }

    /// Feature-off contract: a valid URL without the `chromium` feature maps
    /// to an honest Spanish `isError:true` envelope — never a false success
    /// (ai.rs pattern). Only meaningful when the feature is off (with
    /// `chromium` enabled this path launches a real browser — untestable here).
    #[tokio::test]
    #[cfg(not(feature = "chromium"))]
    #[serial] // WEBFANG_MCP_DISABLE_SSRF is process-global — see ai.rs
    async fn get_accessibility_snapshot_feature_off_is_honest_error() {
        // Lift the guard for this test only; EnvGuard restores the original
        // on drop, so the "1" cannot leak into sibling tests in a shared
        // process (#1126).
        let _guard = webfang_test_utils::EnvGuard::with(&[("WEBFANG_MCP_DISABLE_SSRF", "1")]);
        let (handler, _tmp) = test_handler().await;
        let res = handler
            .get_accessibility_snapshot(Parameters(GetAccessibilitySnapshotParams {
                url: vu("https://example.com/page"),
                selector: None,
                interactive_only: true,
                format: SnapshotFormatParams::Compact,
            }))
            .await
            .expect("get_accessibility_snapshot returns Ok with honest error");
        let json = serde_json::to_value(&res).expect("CallToolResult serializes");
        assert_eq!(
            json.get("isError").and_then(|v| v.as_bool()),
            Some(true),
            "feature-off must set isError:true, got: {json}"
        );
        let text = result_text(&res);
        assert!(
            text.contains("--features chromium") && text.contains("árbol de accesibilidad"),
            "Spanish feature-gated message expected, got: {text}"
        );
    }

    /// #1116: a malformed URL is unrepresentable — `McpUrl` rejects it at
    /// deserialization (rmcp → -32602) before any snapshot work.
    #[test]
    fn get_accessibility_snapshot_invalid_url_is_unrepresentable() {
        let res = serde_json::from_value::<GetAccessibilitySnapshotParams>(serde_json::json!({
            "url": "not a url"
        }));
        assert!(
            res.is_err(),
            "invalid URL must fail to deserialize: {res:?}"
        );
    }

    /// The honest-error contract: `isError:true` + Spanish text.
    #[test]
    fn honest_error_sets_is_error_and_spanish_text() {
        let result = honest_error("funcionalidad no disponible: prueba");
        let json = serde_json::to_value(&result).expect("CallToolResult must serialize");
        assert_eq!(json.get("isError").and_then(|v| v.as_bool()), Some(true));
    }

    /// Params defaults: interactive_only=true, format=compact.
    #[test]
    fn params_defaults_are_interactive_only_compact() {
        let params: GetAccessibilitySnapshotParams =
            serde_json::from_value(serde_json::json!({ "url": "https://example.com" }))
                .expect("minimal params deserialize");
        assert!(params.interactive_only);
        assert_eq!(params.format, SnapshotFormatParams::Compact);
        assert!(params.selector.is_none());
    }

    /// `build_router` returns the axtree partial router without panicking.
    #[test]
    fn build_router_returns_axtree_router() {
        let router = build_router();
        assert!(std::mem::size_of_val(&router) > 0);
    }
}
