//! Accessibility-tree snapshot tool — 1 tool: get_accessibility_snapshot
//!
//! The tool is always registered. With the `chromium` feature it returns a
//! compact interactive AXTree snapshot (CDP `Accessibility.getFullAXTree`);
//! without it, an honest Spanish feature-gated error (ai.rs pattern, #386).

use super::McpHandler;
use crate::mcp_server::params::*;
use rmcp::handler::server::tool::ToolRouter;
use rmcp::handler::server::wrapper::Parameters;
use rmcp::tool;
use rmcp::tool_router;
use rmcp::{model::CallToolResult, model::Content, ErrorData as McpError};
use tracing::instrument;

#[cfg(feature = "chromium")]
use webfang_core::infrastructure::axtree::{fetch_axtree_snapshot, SnapshotFormat};

/// Build an honest tool error (`isError:true`) carrying a Spanish message
/// (same contract as `ai.rs` / `export.rs`).
fn honest_error(message: impl Into<String>) -> CallToolResult {
    CallToolResult::error(vec![Content::text(message.into())])
}

#[tool_router(router = tool_router_axtree, vis = "pub")]
// Allow: the `tool_router_axtree` fn generated by rmcp-macros cannot be documented from this crate.
#[allow(missing_docs)]
impl McpHandler {
    /// Compact accessibility-tree snapshot of a rendered page
    ///
    /// Fetches the page's accessibility tree via CDP
    /// `Accessibility.getFullAXTree`, then serializes interactive elements as
    /// `@eN`-referenced nodes with a `token_estimate`. Requires the
    /// `chromium` feature.
    #[tool(
        description = "Fetch a rendered page's accessibility tree and return a compact snapshot of interactive elements with @eN refs and a token_estimate. Requires --features chromium."
    )]
    #[instrument(skip(self), fields(url = %params.url, interactive_only = params.interactive_only))]
    async fn get_accessibility_snapshot(
        &self,
        Parameters(params): Parameters<GetAccessibilitySnapshotParams>,
    ) -> Result<CallToolResult, McpError> {
        params.validate()?;

        let _permit = acquire_semaphore!(self, scraping);

        let url = url::Url::parse(&params.url).map_err(|e| {
            McpError::invalid_params(
                format!("URL inválida: {e}"),
                Some(serde_json::Value::String("url".to_string())),
            )
        })?;

        crate::mcp_server::ssrf::validate_url_no_ssrf(&url).await?;

        fetch_snapshot(
            &url,
            params.interactive_only,
            params.selector.as_deref(),
            params.format,
        )
        .await
    }
}

/// Chromium-enabled path: run the core engine and surface failures as honest
/// Spanish errors (spec R5).
#[cfg(feature = "chromium")]
async fn fetch_snapshot(
    url: &url::Url,
    interactive_only: bool,
    selector: Option<&str>,
    format: SnapshotFormatParams,
) -> Result<CallToolResult, McpError> {
    let core_format = match format {
        SnapshotFormatParams::Compact => SnapshotFormat::Compact,
        SnapshotFormatParams::PlaywrightMcp => return Ok(honest_error(
            "formato no soportado: playwright-mcp aún no está implementado. Usa format=compact.",
        )),
    };
    match fetch_axtree_snapshot(url, interactive_only, selector, core_format).await {
        Ok(snapshot) => {
            tracing::info!(
                token_estimate = snapshot.token_estimate,
                interactive = snapshot.nodes.len(),
                "axtree snapshot produced"
            );
            match serde_json::to_string(&snapshot) {
                Ok(json) => Ok(CallToolResult::success(vec![Content::text(json)])),
                Err(e) => Ok(honest_error(format!(
                    "error al serializar la respuesta: {e}"
                ))),
            }
        },
        Err(e) => Ok(honest_error(format!(
            "no se pudo obtener el árbol de accesibilidad: {e}"
        ))),
    }
}

/// Feature-off path: honest Spanish error (ai.rs pattern, #386).
#[cfg(not(feature = "chromium"))]
async fn fetch_snapshot(
    _url: &url::Url,
    _interactive_only: bool,
    _selector: Option<&str>,
    _format: SnapshotFormatParams,
) -> Result<CallToolResult, McpError> {
    Ok(honest_error(
        "funcionalidad no disponible: captura del árbol de accesibilidad. Reconstruye con --features chromium para habilitarla.",
    ))
}

/// Build the accessibility-tools router (get_accessibility_snapshot).
///
/// Returns a partial router combined with the other category routers via the
/// `+` operator in [`build_tool_router`](crate::mcp_server::handlers::build_tool_router).
pub fn build_router() -> ToolRouter<McpHandler> {
    McpHandler::tool_router_axtree()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::mcp_server::state::McpState;
    use rmcp::handler::server::wrapper::Parameters;
    #[cfg(not(feature = "chromium"))]
    use serial_test::serial;
    use tempfile::TempDir;
    use webfang_core::di::Container;
    use webfang_core::domain::CrawlerConfig;
    use webfang_core::infrastructure::config::ScraperConfig;

    /// Build a default handler (no chromium — unit tests run with default
    /// features) backed by a real DI container. Offline: construction never
    /// touches the network.
    async fn test_handler() -> (McpHandler, TempDir) {
        let tmp = TempDir::new().expect("create temp dir");
        let crawler_config =
            CrawlerConfig::new(url::Url::parse("https://example.com").expect("valid url"));
        let scraper_config = ScraperConfig {
            output_dir: tmp.path().to_path_buf(),
            ..Default::default()
        };
        let container = Container::new(crawler_config, scraper_config)
            .await
            .expect("create container");
        (McpHandler::new(McpState::new(container)), tmp)
    }

    #[cfg(not(feature = "chromium"))]
    fn result_text(result: &CallToolResult) -> String {
        serde_json::to_value(result)
            .ok()
            .and_then(|v| v.get("content").and_then(|c| c.as_array()).cloned())
            .and_then(|arr| arr.first().cloned())
            .and_then(|first| {
                first
                    .get("text")
                    .and_then(|t| t.as_str())
                    .map(str::to_owned)
            })
            .unwrap_or_default()
    }

    /// Feature-off contract: a valid URL without the `chromium` feature maps
    /// to an honest Spanish `isError:true` envelope — never a false success
    /// (ai.rs pattern). Only meaningful when the feature is off (with
    /// `chromium` enabled this path launches a real browser — untestable here).
    #[tokio::test]
    #[cfg(not(feature = "chromium"))]
    #[serial] // WEBFANG_MCP_DISABLE_SSRF is process-global — see ai.rs
    async fn get_accessibility_snapshot_feature_off_is_honest_error() {
        std::env::set_var("WEBFANG_MCP_DISABLE_SSRF", "1");
        let (handler, _tmp) = test_handler().await;
        let res = handler
            .get_accessibility_snapshot(Parameters(GetAccessibilitySnapshotParams {
                url: "https://example.com/page".to_string(),
                selector: None,
                interactive_only: true,
                format: SnapshotFormatParams::Compact,
            }))
            .await
            .expect("get_accessibility_snapshot returns Ok with honest error");
        let json = serde_json::to_value(&res).expect("CallToolResult serializes");
        assert_eq!(
            json.get("isError").and_then(|v| v.as_bool()),
            Some(true),
            "feature-off must set isError:true, got: {json}"
        );
        let text = result_text(&res);
        assert!(
            text.contains("--features chromium") && text.contains("árbol de accesibilidad"),
            "Spanish feature-gated message expected, got: {text}"
        );
    }

    /// A malformed URL must be rejected with `McpError::invalid_params`
    /// before any snapshot work.
    #[tokio::test]
    async fn get_accessibility_snapshot_invalid_url_is_invalid_params() {
        let (handler, _tmp) = test_handler().await;
        let res = handler
            .get_accessibility_snapshot(Parameters(GetAccessibilitySnapshotParams {
                url: "not a url".to_string(),
                selector: None,
                interactive_only: true,
                format: SnapshotFormatParams::Compact,
            }))
            .await;
        assert!(
            res.is_err(),
            "invalid URL must return McpError, got: {res:?}"
        );
    }

    /// The honest-error contract: `isError:true` + Spanish text.
    #[test]
    fn honest_error_sets_is_error_and_spanish_text() {
        let result = honest_error("funcionalidad no disponible: prueba");
        let json = serde_json::to_value(&result).expect("CallToolResult must serialize");
        assert_eq!(json.get("isError").and_then(|v| v.as_bool()), Some(true));
    }

    /// Params defaults: interactive_only=true, format=compact.
    #[test]
    fn params_defaults_are_interactive_only_compact() {
        let params: GetAccessibilitySnapshotParams =
            serde_json::from_value(serde_json::json!({ "url": "https://example.com" }))
                .expect("minimal params deserialize");
        assert!(params.interactive_only);
        assert_eq!(params.format, SnapshotFormatParams::Compact);
        assert!(params.selector.is_none());
    }

    /// `build_router` returns the axtree partial router without panicking.
    #[test]
    fn build_router_returns_axtree_router() {
        let router = build_router();
        assert!(std::mem::size_of_val(&router) > 0);
    }
}
