//! Content Processing tools — 7 tools for HTML/Markdown transformation
//!
//! Tools: extract_links, clean_html, convert_html_to_markdown,
//! highlight_code_blocks, convert_wiki_links, generate_frontmatter,
//! generate_rich_metadata

use super::McpHandler;
use crate::mcp_server::params::*;
use rmcp::handler::server::tool::ToolRouter;
use rmcp::handler::server::wrapper::Parameters;
use rmcp::tool;
use rmcp::tool_router;
use rmcp::{model::CallToolResult, model::Content, ErrorData as McpError};
use tracing::instrument;

#[tool_router(router = tool_router_content, vis = "pub")]
// Allow: the `tool_router_content` fn generated by rmcp-macros cannot be documented from this crate.
#[allow(missing_docs)]
impl McpHandler {
    /// Remove boilerplate from HTML (scripts, nav, sidebar, footer, SVG)
    #[tool(
        description = "Remove boilerplate from HTML including scripts, styles, navigation, sidebar, footer, and SVG elements. Returns cleaned HTML."
    )]
    #[instrument(skip(self), fields(html_len = params.html.len()))]
    async fn clean_html(
        &self,
        Parameters(params): Parameters<CleanHtmlParams>,
    ) -> Result<CallToolResult, McpError> {
        params.validate()?;

        let _permit = acquire_semaphore!(self, content);

        let cleaned =
            webfang_core::infrastructure::converter::html_cleaner::clean_html(&params.html);
        Ok(CallToolResult::success(vec![Content::text(cleaned)]))
    }

    /// Convert HTML to Markdown
    #[tool(
        description = "Convert HTML to Markdown, preserving headings, code blocks, lists, and formatting."
    )]
    #[instrument(skip(self), fields(html_len = params.html.len()))]
    async fn convert_html_to_markdown(
        &self,
        Parameters(params): Parameters<HtmlToMarkdownParams>,
    ) -> Result<CallToolResult, McpError> {
        params.validate()?;

        let _permit = acquire_semaphore!(self, content);

        let md = webfang_core::infrastructure::converter::html_to_markdown::convert_to_markdown(
            &params.html,
        );
        Ok(CallToolResult::success(vec![Content::text(md)]))
    }

    /// Extract all crawlable href links from HTML
    #[tool(
        description = "Extract href links from HTML content, honoring rel=\"nofollow\" (excluded) and a document <base href>. Returns list of raw href values."
    )]
    #[instrument(skip(self), fields(base_url = %params.base_url))]
    async fn extract_links(
        &self,
        Parameters(params): Parameters<ExtractLinksParams>,
    ) -> Result<CallToolResult, McpError> {
        params.validate()?;

        let _permit = acquire_semaphore!(self, content);

        match webfang_core::infrastructure::crawler::extract_links(&params.html, &params.base_url) {
            Ok(links) => {
                let content = serde_json::to_string_pretty(&links)
                    .unwrap_or_else(|_| "failed to serialize".into());
                Ok(CallToolResult::success(vec![Content::text(content)]))
            },
            Err(e) => Ok(CallToolResult::error(vec![Content::text(e.to_string())])),
        }
    }

    /// Add syntax highlighting to fenced code blocks
    #[tool(
        description = "Add syntax highlighting to fenced code blocks in Markdown using syntect. Returns Markdown with highlighted code."
    )]
    #[instrument(skip(self), fields(markdown_len = params.markdown.len()))]
    async fn highlight_code_blocks(
        &self,
        Parameters(params): Parameters<HighlightCodeParams>,
    ) -> Result<CallToolResult, McpError> {
        params.validate()?;

        let _permit = acquire_semaphore!(self, content);

        let highlighted =
            webfang_core::infrastructure::converter::syntax_highlight::highlight_code_blocks(
                &params.markdown,
            );
        Ok(CallToolResult::success(vec![Content::text(highlighted)]))
    }

    /// Convert HTTP links to Obsidian [[wiki-link]] syntax
    #[tool(
        description = "Convert same-domain HTTP links to Obsidian [[wiki-link]] syntax for internal note linking."
    )]
    #[instrument(skip(self), fields(base_domain = %params.base_domain))]
    async fn convert_wiki_links(
        &self,
        Parameters(params): Parameters<ConvertWikiLinksParams>,
    ) -> Result<CallToolResult, McpError> {
        params.validate()?;

        let _permit = acquire_semaphore!(self, content);

        let wikilinks = webfang_core::infrastructure::converter::wikilinks::convert_wiki_links(
            &params.markdown,
            &params.base_domain,
        );
        Ok(CallToolResult::success(vec![Content::text(wikilinks)]))
    }

    /// Generate YAML frontmatter for a scraped document
    #[tool(
        description = "Generate YAML frontmatter with title, URL, date, author, excerpt, and optional rich metadata."
    )]
    #[instrument(skip(self), fields(params = ?params))]
    async fn generate_frontmatter(
        &self,
        Parameters(params): Parameters<GenerateFrontmatterParams>,
    ) -> Result<CallToolResult, McpError> {
        params.validate()?;

        let _permit = acquire_semaphore!(self, content);

        let title = params.title.as_deref().unwrap_or("Untitled");
        let url = params.url.as_deref().unwrap_or("");
        let author = params.author.as_deref();
        let excerpt = params.excerpt.as_deref();
        let tags = params.tags.as_deref().unwrap_or(&[]);
        let fm = webfang_core::infrastructure::output::frontmatter::generate_with_metadata(
            title, url, None, author, excerpt, tags, None,
        );
        Ok(CallToolResult::success(vec![Content::text(fm)]))
    }

    /// Generate rich metadata from scraped content (word count, reading time, language, content type)
    #[tool(
        description = "Generate rich metadata from scraped content including word count, reading time (200 WPM), language detection, and content type classification."
    )]
    #[instrument(skip(self), fields(params = ?params))]
    // serde_json::to_string cannot fail for a serde_json::Value.
    #[allow(clippy::expect_used)]
    async fn generate_rich_metadata(
        &self,
        Parameters(params): Parameters<GenerateRichMetadataParams>,
    ) -> Result<CallToolResult, McpError> {
        params.validate()?;

        let _permit = acquire_semaphore!(self, content);

        let content = params.content.as_deref().unwrap_or("");

        let word_count =
            webfang_core::infrastructure::obsidian::metadata::compute_word_count(content);
        let reading_time =
            webfang_core::infrastructure::obsidian::metadata::compute_reading_time(word_count);

        let meta = serde_json::json!({
            "word_count": word_count,
            "reading_time_minutes": reading_time,
        });
        Ok(CallToolResult::success(vec![Content::text(
            serde_json::to_string_pretty(&meta).expect("serializing JSON to a string cannot fail"),
        )]))
    }
}

/// Build the content processing router (7 tools for HTML/Markdown
/// transformation).
///
/// Returns a partial router that is combined with the other category routers
/// via the `+` operator in
/// [`build_tool_router`](crate::mcp_server::handlers::build_tool_router).
pub fn build_router() -> ToolRouter<McpHandler> {
    McpHandler::tool_router_content()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::mcp_server::state::McpState;
    use rmcp::handler::server::wrapper::Parameters;
    use rmcp::model::CallToolResult;
    use tempfile::TempDir;
    use webfang_core::di::Container;
    use webfang_core::domain::CrawlerConfig;
    use webfang_core::infrastructure::config::ScraperConfig;

    /// Build an `McpHandler` backed by a real `Container` (no network, no MCP
    /// server). The temp dir is returned so it stays alive for the test.
    async fn test_handler() -> (McpHandler, TempDir) {
        let tmp = TempDir::new().expect("create temp dir");
        let crawler_config =
            CrawlerConfig::new(url::Url::parse("https://example.com").expect("valid url"));
        let scraper_config = ScraperConfig {
            output_dir: tmp.path().to_path_buf(),
            ..Default::default()
        };
        let container = Container::new(crawler_config, scraper_config)
            .await
            .expect("create container");
        let state = McpState::new(container);
        (McpHandler::new(state), tmp)
    }

    /// Extract the first `content[0].text` from a `CallToolResult` (mirrors the
    /// MCP transport serialization used by the integration harness).
    fn result_text(result: &CallToolResult) -> String {
        serde_json::to_value(result)
            .ok()
            .and_then(|v| v.get("content").and_then(|c| c.as_array()).cloned())
            .and_then(|arr| arr.first().cloned())
            .and_then(|first| {
                first
                    .get("text")
                    .and_then(|t| t.as_str())
                    .map(str::to_owned)
            })
            .unwrap_or_default()
    }

    #[tokio::test]
    async fn clean_html_removes_scripts() {
        let (handler, _tmp) = test_handler().await;
        let html = "<html><head><script>evil()</script></head><body><p>Hello</p></body></html>";
        let res = handler
            .clean_html(Parameters(CleanHtmlParams {
                html: html.to_string(),
            }))
            .await
            .expect("clean_html returns Ok");
        let text = result_text(&res);
        assert!(
            text.contains("Hello"),
            "cleaned text must keep body: {text}"
        );
        assert!(!text.contains("evil()"), "scripts must be stripped: {text}");
    }

    #[tokio::test]
    async fn convert_html_to_markdown_preserves_heading() {
        let (handler, _tmp) = test_handler().await;
        let html = "<h1>My Title</h1><p>Body text here</p>";
        let res = handler
            .convert_html_to_markdown(Parameters(HtmlToMarkdownParams {
                html: html.to_string(),
            }))
            .await
            .expect("convert returns Ok");
        let text = result_text(&res);
        assert!(
            text.contains("My Title"),
            "markdown must preserve heading: {text}"
        );
    }

    #[tokio::test]
    async fn extract_links_resolves_relative() {
        let (handler, _tmp) = test_handler().await;
        let html =
            r#"<html><body><a href="/page">x</a><a href="https://other.com/y">y</a></body></html>"#;
        let res = handler
            .extract_links(Parameters(ExtractLinksParams {
                html: html.to_string(),
                base_url: "https://example.com".to_string(),
            }))
            .await
            .expect("extract_links returns Ok");
        let text = result_text(&res);
        assert!(
            text.contains("page"),
            "relative link must be present: {text}"
        );
        assert!(
            text.contains("other.com"),
            "absolute link must be present: {text}"
        );
    }

    #[tokio::test]
    async fn highlight_code_blocks_is_idempotent_ok() {
        let (handler, _tmp) = test_handler().await;
        let md = "```rust\nfn main() {}\n```";
        let res = handler
            .highlight_code_blocks(Parameters(HighlightCodeParams {
                markdown: md.to_string(),
            }))
            .await
            .expect("highlight returns Ok");
        let text = result_text(&res);
        assert!(
            text.contains("main"),
            "code tokens must survive highlighting: {text}"
        );
    }

    #[tokio::test]
    async fn convert_wiki_links_same_domain() {
        let (handler, _tmp) = test_handler().await;
        let md = "[note](https://example.com/notes/a-note)";
        let res = handler
            .convert_wiki_links(Parameters(ConvertWikiLinksParams {
                markdown: md.to_string(),
                base_domain: "example.com".to_string(),
            }))
            .await
            .expect("convert_wiki_links returns Ok");
        let text = result_text(&res);
        assert!(
            text.contains("[["),
            "same-domain link becomes wiki-link: {text}"
        );
    }

    #[tokio::test]
    async fn generate_frontmatter_includes_title() {
        let (handler, _tmp) = test_handler().await;
        let res = handler
            .generate_frontmatter(Parameters(GenerateFrontmatterParams {
                title: Some("Hello".to_string()),
                url: Some("https://example.com/p".to_string()),
                author: None,
                excerpt: None,
                tags: None,
            }))
            .await
            .expect("generate_frontmatter returns Ok");
        let text = result_text(&res);
        assert!(
            text.contains("Hello"),
            "frontmatter must include title: {text}"
        );
        assert!(
            text.contains("example.com"),
            "frontmatter must include url: {text}"
        );
    }

    #[tokio::test]
    async fn generate_frontmatter_honors_author_excerpt_tags() {
        let (handler, _tmp) = test_handler().await;
        // Bug #3 regression: params.author, params.excerpt, params.tags MUST
        // be passed through to generate_with_metadata, not hardcoded to None/empty
        // (issue #590).
        let res = handler
            .generate_frontmatter(Parameters(GenerateFrontmatterParams {
                title: Some("My Post".to_string()),
                url: Some("https://example.com/post".to_string()),
                author: Some("Jane Doe".to_string()),
                excerpt: Some("A brief summary".to_string()),
                tags: Some(vec!["rust".to_string(), "web".to_string()]),
            }))
            .await
            .expect("generate_frontmatter returns Ok");
        let text = result_text(&res);
        assert!(text.contains("Jane Doe"), "author must appear: {text}");
        assert!(
            text.contains("A brief summary"),
            "excerpt must appear: {text}"
        );
        assert!(text.contains("rust"), "tag 'rust' must appear: {text}");
        assert!(text.contains("web"), "tag 'web' must appear: {text}");
    }

    #[tokio::test]
    async fn generate_rich_metadata_counts_words() {
        let (handler, _tmp) = test_handler().await;
        let res = handler
            .generate_rich_metadata(Parameters(GenerateRichMetadataParams {
                content: Some("one two three four five".to_string()),
            }))
            .await
            .expect("generate_rich_metadata returns Ok");
        let text = result_text(&res);
        let parsed: serde_json::Value = serde_json::from_str(&text).expect("rich metadata is JSON");
        assert_eq!(
            parsed.get("word_count").and_then(|v| v.as_u64()),
            Some(5),
            "word_count must be 5: {parsed}"
        );
        assert!(
            parsed.get("reading_time_minutes").is_some(),
            "reading_time must be present: {parsed}"
        );
    }
}
