//! Obsidian Integration tools — 3 tools for vault operations
//!
//! Tools: detect_obsidian_vault, build_obsidian_uri, open_in_obsidian

use super::McpHandler;
use crate::mcp_server::params::*;
use rmcp::handler::server::tool::ToolRouter;
use rmcp::handler::server::wrapper::Parameters;
use rmcp::tool;
use rmcp::tool_router;
use rmcp::{model::CallToolResult, model::Content, ErrorData as McpError};
use tracing::instrument;

#[tool_router(router = tool_router_obsidian, vis = "pub")]
// Allow: the `tool_router_obsidian` fn generated by rmcp-macros cannot be documented from this crate.
#[allow(missing_docs)]
impl McpHandler {
    /// Detect Obsidian vault path using multi-priority detection
    #[tool(
        description = "Detect Obsidian vault path using multi-priority detection: CLI flag → env var → config file → registry → auto-scan."
    )]
    #[instrument(skip(self), fields(vault_path = ?params.vault_path))]
    async fn detect_obsidian_vault(
        &self,
        Parameters(params): Parameters<DetectVaultParams>,
    ) -> Result<CallToolResult, McpError> {
        params.validate()?;

        let _permit = acquire_semaphore!(self, obsidian);

        let cli_path = params
            .vault_path
            .as_ref()
            .map(|p| std::path::Path::new(p.as_str()));
        // Hermetic injection (tests, #726): route detection through the
        // injected root/registry so the host's Obsidian registry is never
        // read. `None` (production) keeps the default detection chain.
        let detected = if let Some((root, registry_path)) = &self.state.obsidian_hermetic {
            webfang_core::infrastructure::obsidian::vault_detector::detect_vault_hermetic(
                Some(root.as_path()),
                Some(registry_path.as_path()),
                cli_path,
                None,
                None,
            )
        } else {
            webfang_core::infrastructure::obsidian::vault_detector::detect_vault(
                cli_path, None, None,
            )
        };
        match detected {
            Some(path) => Ok(CallToolResult::success(vec![Content::text(
                path.display().to_string(),
            )])),
            None => Ok(CallToolResult::success(vec![Content::text(
                "no vault detected",
            )])),
        }
    }

    /// Build obsidian:// URI protocol link
    #[tool(
        description = "Build an obsidian:// URI protocol link to open a specific note in the Obsidian app."
    )]
    #[instrument(skip(self), fields(vault_name = %params.vault_name, file_path = %params.file_path))]
    async fn build_obsidian_uri(
        &self,
        Parameters(params): Parameters<BuildObsidianUriParams>,
    ) -> Result<CallToolResult, McpError> {
        params.validate()?;

        let _permit = acquire_semaphore!(self, obsidian);

        if let Err(e) = webfang_core::infrastructure::obsidian::uri::validate_obsidian_input(
            &params.vault_name,
            &params.file_path,
        ) {
            return Ok(CallToolResult::error(vec![Content::text(e)]));
        }

        let uri = webfang_core::infrastructure::obsidian::uri::build_obsidian_uri(
            &params.vault_name,
            &params.file_path,
        );
        Ok(CallToolResult::success(vec![Content::text(uri)]))
    }

    /// Open a note in Obsidian app via URI protocol
    #[tool(
        description = "Open a note in the Obsidian app using the obsidian:// URI protocol. Launches the Obsidian application."
    )]
    #[instrument(skip(self), fields(vault_name = %params.vault_name, file_path = %params.file_path))]
    async fn open_in_obsidian(
        &self,
        Parameters(params): Parameters<BuildObsidianUriParams>,
    ) -> Result<CallToolResult, McpError> {
        params.validate()?;

        let _permit = acquire_semaphore!(self, obsidian);

        if let Err(e) = webfang_core::infrastructure::obsidian::uri::validate_obsidian_input(
            &params.vault_name,
            &params.file_path,
        ) {
            return Ok(CallToolResult::error(vec![Content::text(e)]));
        }

        let uri = webfang_core::infrastructure::obsidian::uri::build_obsidian_uri(
            &params.vault_name,
            &params.file_path,
        );
        use webfang_core::infrastructure::obsidian::uri::DispatchStatus;
        match webfang_core::infrastructure::obsidian::uri::open_in_obsidian(&uri) {
            Ok(DispatchStatus::Dispatched) => Ok(CallToolResult::success(vec![Content::text(
                format!("Abriendo en Obsidian: {uri}"),
            )])),
            Ok(DispatchStatus::HandlerFailed) => {
                Ok(CallToolResult::success(vec![Content::text(format!(
                    "⚠️ El manejador de URI falló (Obsidian puede no estar instalado). URI: {uri}"
                ))]))
            },
            Err(e) => Ok(CallToolResult::error(vec![Content::text(format!(
                "error al abrir Obsidian: {e}"
            ))])),
        }
    }
}

/// Build the Obsidian integration router (detect_obsidian_vault,
/// build_obsidian_uri, open_in_obsidian).
///
/// Returns a partial router that is combined with the other category routers
/// via the `+` operator in
/// [`build_tool_router`](crate::mcp_server::handlers::build_tool_router).
pub fn build_router() -> ToolRouter<McpHandler> {
    McpHandler::tool_router_obsidian()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::mcp_server::state::McpState;
    use rmcp::handler::server::wrapper::Parameters;
    use rmcp::model::CallToolResult;
    use std::fs;
    use tempfile::TempDir;
    use webfang_core::di::Container;
    use webfang_core::domain::CrawlerConfig;
    use webfang_core::infrastructure::config::ScraperConfig;

    async fn test_handler() -> (McpHandler, TempDir) {
        let tmp = TempDir::new().expect("create temp dir");
        let crawler_config =
            CrawlerConfig::new(url::Url::parse("https://example.com").expect("valid url"));
        let scraper_config = ScraperConfig {
            output_dir: tmp.path().to_path_buf(),
            ..Default::default()
        };
        let container = Container::new(crawler_config, scraper_config)
            .await
            .expect("create container");
        // Hermetic vault detection (#726): detection runs against an isolated
        // empty scan root and a non-existent registry file, so tests never
        // touch the host's real Obsidian installation.
        let detect_root = tmp.path().join("detect-root");
        fs::create_dir_all(&detect_root).expect("create detect root");
        let registry = detect_root.join("obsidian.json");
        let state = McpState::new(container).with_obsidian_hermetic(detect_root, registry);
        (McpHandler::new(state), tmp)
    }

    fn result_text(result: &CallToolResult) -> String {
        serde_json::to_value(result)
            .ok()
            .and_then(|v| v.get("content").and_then(|c| c.as_array()).cloned())
            .and_then(|arr| arr.first().cloned())
            .and_then(|first| {
                first
                    .get("text")
                    .and_then(|t| t.as_str())
                    .map(str::to_owned)
            })
            .unwrap_or_default()
    }

    #[tokio::test]
    async fn detect_obsidian_vault_finds_cli_path() {
        let (handler, _tmp) = test_handler().await;
        // `vault_path` must be a safe relative path (params validation, #512).
        // A directory containing the `.obsidian` marker is a valid vault.
        let vault_dir = "test-output/obsidian-vault";
        let _ = fs::remove_dir_all(vault_dir);
        fs::create_dir_all(format!("{vault_dir}/.obsidian")).expect("create .obsidian");
        let res = handler
            .detect_obsidian_vault(Parameters(DetectVaultParams {
                vault_path: Some(vault_dir.to_string()),
            }))
            .await
            .expect("detect returns Ok");
        let text = result_text(&res);
        assert!(
            text.contains("obsidian-vault"),
            "detected vault path must be reported: {text}"
        );
        let _ = fs::remove_dir_all(vault_dir);
    }

    #[tokio::test]
    async fn detect_obsidian_vault_none_when_not_a_vault() {
        let (handler, _tmp) = test_handler().await;
        // A plain dir with no `.obsidian` marker is not a vault.
        let not_vault_dir = "test-output/obsidian-notvault";
        let _ = fs::remove_dir_all(not_vault_dir);
        fs::create_dir_all(not_vault_dir).expect("create dir");
        let res = handler
            .detect_obsidian_vault(Parameters(DetectVaultParams {
                vault_path: Some(not_vault_dir.to_string()),
            }))
            .await
            .expect("detect returns Ok");
        let text = result_text(&res);
        assert_eq!(
            text, "no vault detected",
            "non-vault path must report no vault: {text}"
        );
        let _ = fs::remove_dir_all(not_vault_dir);
    }

    #[tokio::test]
    async fn build_obsidian_uri_success() {
        let (handler, _tmp) = test_handler().await;
        let res = handler
            .build_obsidian_uri(Parameters(BuildObsidianUriParams {
                vault_name: "MyVault".to_string(),
                file_path: "Notes/note.md".to_string(),
            }))
            .await
            .expect("build returns Ok");
        let text = result_text(&res);
        assert!(
            text.starts_with("obsidian://open?vault=MyVault&file="),
            "must build obsidian uri: {text}"
        );
    }

    #[tokio::test]
    async fn build_obsidian_uri_rejects_control_chars() {
        let (handler, _tmp) = test_handler().await;
        let res = handler
            .build_obsidian_uri(Parameters(BuildObsidianUriParams {
                vault_name: "MyVault".to_string(),
                file_path: "Notes\note.md".to_string(),
            }))
            .await
            .expect("build returns Ok on invalid input");
        let json = serde_json::to_value(&res).expect("serialize");
        assert_eq!(
            json.get("isError").and_then(|v| v.as_bool()),
            Some(true),
            "control chars must map to isError:true, got: {json}"
        );
    }

    #[tokio::test]
    async fn open_in_obsidian_rejects_control_chars() {
        let (handler, _tmp) = test_handler().await;
        let res = handler
            .open_in_obsidian(Parameters(BuildObsidianUriParams {
                vault_name: "MyVault".to_string(),
                file_path: "Notes\note.md".to_string(),
            }))
            .await
            .expect("open returns Ok on invalid input");
        let json = serde_json::to_value(&res).expect("serialize");
        assert_eq!(
            json.get("isError").and_then(|v| v.as_bool()),
            Some(true),
            "control chars must map to isError:true, got: {json}"
        );
    }
}
