//! Scraping Core tools — 8 tools for URL scraping and crawling
//!
//! Tools: scrape_url, scrape_with_options, scrape_batch, crawl_site,
//! crawl_with_sitemap, discover_urls, discover_sitemap, detect_spa

use super::McpHandler;
use crate::mcp_server::metrics::{domain_of, Outcome};
use crate::mcp_server::params::*;
use crate::mcp_server::selector_service;
use rmcp::handler::server::tool::ToolRouter;
use rmcp::handler::server::wrapper::Parameters;
use rmcp::tool;
use rmcp::tool_router;
use rmcp::{model::CallToolResult, model::Content, ErrorData as McpError};
use std::time::Instant;
use tracing::instrument;

#[tool_router(router = tool_router_scraping, vis = "pub")]
// Allow: the `tool_router_scraping` fn generated by rmcp-macros cannot be documented from this crate.
#[allow(missing_docs)]
impl McpHandler {
    /// Scrape a single URL and extract clean content using Readability algorithm
    #[tool(
        description = "Scrape a single URL and extract clean content using Readability algorithm (Firefox Reader mode). Returns title, content, excerpt, author, and date."
    )]
    #[instrument(skip(self), fields(url = %params.url))]
    async fn scrape_url(
        &self,
        Parameters(params): Parameters<ScrapeUrlParams>,
    ) -> Result<CallToolResult, McpError> {
        params.validate()?;

        let _permit = acquire_semaphore!(self, scraping);

        let url = url::Url::parse(&params.url).map_err(|e| {
            McpError::invalid_params(
                format!("invalid URL: {e}"),
                Some(serde_json::Value::String("url".to_string())),
            )
        })?;

        crate::mcp_server::ssrf::validate_url_no_ssrf(&url).await?;

        let start = Instant::now();
        let client = self.state.container.http_client().as_ref();
        // One run identity per tool call, shared by its success and error events (#501/#698).
        let root_correlation = webfang_core::domain::CorrelationId::new();
        match webfang_core::application::scraper_service::scrape_with_readability(client, &url)
            .await
        {
            Ok(results) => {
                let count = results.len();
                self.state.record_scrape_identity(
                    "scrape_url",
                    domain_of(&params.url),
                    Outcome::Success,
                    count,
                    start,
                    &root_correlation,
                );
                let content = serde_json::to_string_pretty(&results)
                    .unwrap_or_else(|_| "failed to serialize".into());
                Ok(CallToolResult::success(vec![Content::text(content)]))
            },
            Err(e) => {
                self.state.record_scrape_identity(
                    "scrape_url",
                    domain_of(&params.url),
                    Outcome::Error,
                    0,
                    start,
                    &root_correlation,
                );
                Ok(CallToolResult::error(vec![Content::text(e.to_string())]))
            },
        }
    }

    /// Scrape a URL with configurable options (asset download, concurrency)
    #[tool(
        description = "Scrape a URL with configurable options including asset downloading, concurrency, and delay settings."
    )]
    #[instrument(skip(self), fields(url = %params.url))]
    async fn scrape_with_options(
        &self,
        Parameters(params): Parameters<ScrapeWithOptionsParams>,
    ) -> Result<CallToolResult, McpError> {
        params.validate()?;

        let _permit = acquire_semaphore!(self, scraping);

        let url = url::Url::parse(&params.url).map_err(|e| {
            McpError::invalid_params(
                format!("invalid URL: {e}"),
                Some(serde_json::Value::String("url".to_string())),
            )
        })?;

        crate::mcp_server::ssrf::validate_url_no_ssrf(&url).await?;

        let mut config = webfang_core::infrastructure::config::ScraperConfig::default();
        if let Some(max) = params.max_pages {
            config.max_pages = Some(max as usize);
        }
        if params.download_images == Some(true) {
            config.download_images = true;
        }
        if params.download_documents == Some(true) {
            config.download_documents = true;
        }
        // Wire CSS selector (defaults to "body" when not provided)
        if let Some(ref sel) = params.selector {
            config.selector = sel.clone();
        }

        let start = Instant::now();
        let client = self.state.container.http_client().as_ref();
        let dl = self
            .state
            .downloader
            .as_deref()
            .map(|d| d as &dyn webfang_core::domain::ports::AssetDownloaderPort);
        let inspector = self.state.inspector.as_deref();
        // robots.txt enforcement (#697): shared fetcher from the state; the
        // tool-level opt-out is `params.ignore_robots`.
        let robots = self.state.robots_fetcher.as_deref();
        let ignore_robots = params.ignore_robots.unwrap_or(false);
        // An MCP tool call IS an operation (#501): mint the run-root identity
        // at the handler entry; the use case derives the page child from it.
        let root_correlation = webfang_core::domain::CorrelationId::new();
        match webfang_core::application::scraper_service::scrape_with_config(
            client,
            &url,
            &config,
            dl,
            inspector,
            None,
            robots,
            ignore_robots,
            &root_correlation,
        )
        .await
        {
            Ok(outcome) => {
                let count = outcome.results.len();
                self.state.record_scrape_identity(
                    "scrape_with_options",
                    domain_of(&params.url),
                    Outcome::Success,
                    count,
                    start,
                    &root_correlation,
                );
                let response = selector_service::build_scrape_response(
                    outcome.results,
                    &outcome.extract_result,
                    &params.selector,
                );
                let content = serde_json::to_string_pretty(&response)
                    .unwrap_or_else(|_| "failed to serialize".into());
                Ok(CallToolResult::success(vec![Content::text(content)]))
            },
            Err(e) => {
                self.state.record_scrape_identity(
                    "scrape_with_options",
                    domain_of(&params.url),
                    Outcome::Error,
                    0,
                    start,
                    &root_correlation,
                );
                Ok(CallToolResult::error(vec![Content::text(e.to_string())]))
            },
        }
    }

    /// Scrape multiple URLs with concurrency control
    #[tool(
        description = "Scrape multiple URLs with concurrency control. Failed URLs are logged but don't stop the batch."
    )]
    #[instrument(skip(self), name = "mcp.scrape_batch", fields(url_count = params.urls.len()))]
    async fn scrape_batch(
        &self,
        Parameters(params): Parameters<ScrapeBatchParams>,
    ) -> Result<CallToolResult, McpError> {
        params.validate()?;

        tracing::info!("starting batch scrape");
        let _permit = acquire_semaphore!(self, scraping);

        let mut urls: Vec<url::Url> = Vec::with_capacity(params.urls.len());
        for raw in &params.urls {
            let url = url::Url::parse(raw).map_err(|e| {
                McpError::invalid_params(
                    format!("invalid URL: {e}"),
                    Some(serde_json::Value::String("urls".to_string())),
                )
            })?;
            crate::mcp_server::ssrf::validate_url_no_ssrf(&url).await?;
            urls.push(url);
        }

        if urls.is_empty() {
            return Ok(CallToolResult::error(vec![Content::text(
                "no valid URLs provided",
            )]));
        }

        let start = Instant::now();
        // One run identity per tool call, shared by its success and error events (#501/#698).
        let root_correlation = webfang_core::domain::CorrelationId::new();
        let domain = urls
            .first()
            .and_then(|u| u.host_str())
            .map(str::to_string)
            .unwrap_or_else(|| "unknown".to_string());
        let count = urls.len();

        let mut config = webfang_core::infrastructure::config::ScraperConfig::default();
        if let Some(c) = params.concurrency {
            config.scraper_concurrency = c;
        }

        let client = self.state.container.http_client().as_ref();
        let dl = self
            .state
            .downloader
            .as_deref()
            .map(|d| d as &dyn webfang_core::domain::ports::AssetDownloaderPort);
        // robots.txt enforcement (#697): shared fetcher from the state; the
        // tool-level opt-out is `params.ignore_robots`.
        let robots = self.state.robots_fetcher.as_deref();
        let ignore_robots = params.ignore_robots.unwrap_or(false);
        match webfang_core::application::scraper_service::scrape_multiple_with_limit(
            client,
            &urls,
            &config,
            dl,
            robots,
            ignore_robots,
        )
        .await
        {
            Ok(outcome) => {
                let failed_count = outcome.failed.len();
                let outcome_type = if failed_count == 0 {
                    Outcome::Success
                } else if outcome.results.is_empty() {
                    Outcome::Error
                } else {
                    Outcome::Partial
                };
                self.state.record_scrape_identity(
                    "scrape_batch",
                    domain,
                    outcome_type,
                    count,
                    start,
                    &root_correlation,
                );
                tracing::info!(
                    "batch scrape complete: {} pages, {} failed",
                    outcome.results.len(),
                    failed_count
                );
                // Serialize the full outcome (results + failed) so the caller
                // knows exactly which URLs failed and why (issue #591).
                let content = serde_json::to_string_pretty(&outcome)
                    .unwrap_or_else(|_| "failed to serialize".into());
                Ok(CallToolResult::success(vec![Content::text(content)]))
            },
            Err(e) => {
                self.state.record_scrape_identity(
                    "scrape_batch",
                    domain,
                    Outcome::Error,
                    count,
                    start,
                    &root_correlation,
                );
                tracing::error!("batch scrape failed: {}", e);
                Ok(CallToolResult::error(vec![Content::text(e.to_string())]))
            },
        }
    }

    /// Crawl a website with BFS and depth limit
    #[tool(
        description = "Crawl a website using BFS with configurable depth limit, concurrency control, and rate limiting."
    )]
    #[instrument(skip(self), fields(url = %params.url))]
    // serde_json::to_string cannot fail for a serde_json::Value.
    #[allow(clippy::expect_used)]
    async fn crawl_site(
        &self,
        Parameters(params): Parameters<CrawlSiteParams>,
    ) -> Result<CallToolResult, McpError> {
        params.validate()?;

        let _permit = acquire_semaphore!(self, scraping);

        let seed_url = url::Url::parse(&params.url).map_err(|e| {
            McpError::invalid_params(
                format!("invalid URL: {e}"),
                Some(serde_json::Value::String("url".to_string())),
            )
        })?;

        crate::mcp_server::ssrf::validate_url_no_ssrf(&seed_url).await?;

        let start = Instant::now();
        // One run identity per tool call, shared by its success and error events (#501/#698).
        let root_correlation = webfang_core::domain::CorrelationId::new();
        // Clone: the builder consumes `seed_url` and the Ok arm re-uses it as
        // the filter anchor (the config itself is moved into the crawl).
        let crawler_config = webfang_core::domain::CrawlerConfig::builder(seed_url.clone())
            .max_depth(params.max_depth.unwrap_or(3))
            .max_pages(params.max_pages.unwrap_or(100) as usize)
            .build();

        match webfang_core::application::crawler::crawl_site(crawler_config).await {
            Ok(result) => {
                let count = result.total_pages;
                self.state.record_scrape_identity(
                    "crawl_site",
                    domain_of(&params.url),
                    Outcome::Success,
                    count,
                    start,
                    &root_correlation,
                );
                // REQ-01: filter discovered URLs before responding — keep only
                // seed-host-internal entries; exclusions warn with the URL.
                let mut urls = Vec::with_capacity(result.urls.len());
                filter_ssrf_safe(&result.urls, &seed_url, &mut urls);
                let json = serde_json::json!({
                    "urls": urls,
                    "total_pages": result.total_pages,
                    "errors": result.errors,
                    "error_breakdown": result.error_breakdown,
                });
                Ok(CallToolResult::success(vec![Content::text(
                    serde_json::to_string_pretty(&json)
                        .expect("serializing JSON to a string cannot fail"),
                )]))
            },
            Err(e) => {
                self.state.record_scrape_identity(
                    "crawl_site",
                    domain_of(&params.url),
                    Outcome::Error,
                    0,
                    start,
                    &root_correlation,
                );
                Ok(CallToolResult::error(vec![Content::text(e.to_string())]))
            },
        }
    }

    /// Discover and crawl URLs from a sitemap
    #[tool(
        description = "Discover URLs from a website's sitemap and crawl them. Auto-discovers sitemap from robots.txt if not provided."
    )]
    // serde_json::to_string cannot fail for a serde_json::Value.
    #[allow(clippy::expect_used)]
    #[instrument(skip(self), name = "mcp.crawl_with_sitemap", fields(url = %params.url))]
    async fn crawl_with_sitemap(
        &self,
        Parameters(params): Parameters<CrawlWithSitemapParams>,
    ) -> Result<CallToolResult, McpError> {
        params.validate()?;

        tracing::info!("starting sitemap crawl");
        let _permit = acquire_semaphore!(self, scraping);

        let seed_url = url::Url::parse(&params.url).map_err(|e| {
            tracing::error!("invalid URL: {}", e);
            McpError::invalid_params(
                format!("invalid URL: {e}"),
                Some(serde_json::Value::String("url".to_string())),
            )
        })?;
        crate::mcp_server::ssrf::validate_url_no_ssrf(&seed_url).await?;

        // REQ-02: validate the explicit sitemap URL at entry, BEFORE any
        // sitemap fetch (guard ON unless disabled via env for tests).
        if let Some(s) = &params.sitemap_url {
            let sitemap = url::Url::parse(s).map_err(|e| {
                McpError::invalid_params(format!("URL de sitemap inválida: {e}"), None)
            })?;
            crate::mcp_server::ssrf::validate_url_no_ssrf(&sitemap).await?;
        }

        let start = Instant::now();
        // One run identity per tool call, shared by its success and error events (#501/#698).
        let root_correlation = webfang_core::domain::CorrelationId::new();
        // Clone: `CrawlerConfig::new` consumes `seed_url` and the Ok arm
        // re-uses it as the filter anchor.
        let config = webfang_core::domain::CrawlerConfig::new(seed_url.clone());

        match webfang_core::application::crawler::crawl_with_sitemap(
            &params.url,
            params.sitemap_url.as_deref(),
            &config,
        )
        .await
        {
            Ok(urls) => {
                let count = urls.len();
                self.state.record_scrape_identity(
                    "crawl_with_sitemap",
                    domain_of(&params.url),
                    Outcome::Success,
                    count,
                    start,
                    &root_correlation,
                );
                tracing::info!("sitemap crawl complete: {} urls found", urls.len());
                // REQ-01: filter discovered URLs before responding. Sitemap
                // discovery is host-agnostic — the filter is the gate that
                // drops external-domain and forbidden-literal-IP entries.
                let mut url_strings = Vec::with_capacity(urls.len());
                filter_ssrf_safe(&urls, &seed_url, &mut url_strings);
                Ok(CallToolResult::success(vec![Content::text(
                    serde_json::to_string_pretty(&url_strings)
                        .expect("serializing JSON to a string cannot fail"),
                )]))
            },
            Err(e) => {
                self.state.record_scrape_identity(
                    "crawl_with_sitemap",
                    domain_of(&params.url),
                    Outcome::Error,
                    0,
                    start,
                    &root_correlation,
                );
                tracing::error!("sitemap crawl failed: {}", e);
                Ok(CallToolResult::error(vec![Content::text(e.to_string())]))
            },
        }
    }

    /// Discover URLs from a single page's HTML links
    #[tool(
        description = "Fetch a single page and extract all internal links. Lightweight URL discovery without full crawl."
    )]
    #[instrument(skip(self), fields(url = %params.url))]
    async fn discover_urls(
        &self,
        Parameters(params): Parameters<DiscoverUrlsParams>,
    ) -> Result<CallToolResult, McpError> {
        params.validate()?;

        let _permit = acquire_semaphore!(self, scraping);

        let url = url::Url::parse(&params.url).map_err(|e| {
            McpError::invalid_params(
                format!("invalid URL: {e}"),
                Some(serde_json::Value::String("url".to_string())),
            )
        })?;
        crate::mcp_server::ssrf::validate_url_no_ssrf(&url).await?;

        let start = Instant::now();
        // One run identity per tool call, shared by its success and error events (#501/#698).
        let root_correlation = webfang_core::domain::CorrelationId::new();
        let port = self.state.container.http_client();
        match port.get(url.as_str()).await {
            Ok(resp) => {
                // A non-2xx response (e.g. 404) is a genuine failure for URL
                // discovery, not an empty link set (issue #606). Surface it as
                // a tool error rather than a misleading empty `[]`.
                if !(200..=299).contains(&resp.status) {
                    self.state.record_scrape_identity(
                        "discover_urls",
                        domain_of(&params.url),
                        Outcome::Error,
                        0,
                        start,
                        &root_correlation,
                    );
                    return Ok(CallToolResult::error(vec![Content::text(format!(
                        "HTTP error: status {}",
                        resp.status
                    ))]));
                }
                let html = resp.body;
                match webfang_core::infrastructure::crawler::extract_links(&html, &params.url) {
                    Ok(links) => {
                        let count = links.len();
                        self.state.record_scrape_identity(
                            "discover_urls",
                            domain_of(&params.url),
                            Outcome::Success,
                            count,
                            start,
                            &root_correlation,
                        );
                        let content = serde_json::to_string_pretty(&links)
                            .unwrap_or_else(|_| "failed to serialize".into());
                        Ok(CallToolResult::success(vec![Content::text(content)]))
                    },
                    Err(e) => {
                        self.state.record_scrape_identity(
                            "discover_urls",
                            domain_of(&params.url),
                            Outcome::Error,
                            0,
                            start,
                            &root_correlation,
                        );
                        Ok(CallToolResult::error(vec![Content::text(e.to_string())]))
                    },
                }
            },
            Err(e) => {
                self.state.record_scrape_identity(
                    "discover_urls",
                    domain_of(&params.url),
                    Outcome::Error,
                    0,
                    start,
                    &root_correlation,
                );
                Ok(CallToolResult::error(vec![Content::text(format!(
                    "HTTP error: {e}"
                ))]))
            },
        }
    }

    /// Auto-discover sitemap URL from robots.txt or common locations
    #[tool(
        description = "Auto-discover a website's sitemap URL by checking robots.txt and common locations (/sitemap.xml, /sitemap_index.xml, etc.)."
    )]
    #[instrument(skip(self), fields(url = %params.url))]
    async fn discover_sitemap(
        &self,
        Parameters(params): Parameters<DiscoverUrlsParams>,
    ) -> Result<CallToolResult, McpError> {
        params.validate()?;

        let _permit = acquire_semaphore!(self, scraping);

        let seed = url::Url::parse(&params.url).map_err(|e| {
            McpError::invalid_params(
                format!("invalid URL: {e}"),
                Some(serde_json::Value::String("url".to_string())),
            )
        })?;
        crate::mcp_server::ssrf::validate_url_no_ssrf(&seed).await?;

        let start = Instant::now();
        // One run identity per tool call, shared by its success and error events (#501/#698).
        let root_correlation = webfang_core::domain::CorrelationId::new();
        let crawler_config = webfang_core::domain::CrawlerConfig::new(seed);

        match webfang_core::application::crawler::crawl_with_sitemap(
            &params.url,
            None,
            &crawler_config,
        )
        .await
        {
            Ok(discovered) => {
                let count = discovered.len();
                self.state.record_scrape_identity(
                    "discover_sitemap",
                    domain_of(&params.url),
                    Outcome::Success,
                    count,
                    start,
                    &root_correlation,
                );
                let urls: Vec<String> = discovered.into_iter().map(|d| d.url.to_string()).collect();
                let content = serde_json::to_string_pretty(&urls)
                    .unwrap_or_else(|_| "failed to serialize".into());
                Ok(CallToolResult::success(vec![Content::text(content)]))
            },
            Err(e) => {
                self.state.record_scrape_identity(
                    "discover_sitemap",
                    domain_of(&params.url),
                    Outcome::Error,
                    0,
                    start,
                    &root_correlation,
                );
                Ok(CallToolResult::error(vec![Content::text(e.to_string())]))
            },
        }
    }

    /// Detect if a URL requires JavaScript rendering (SPA)
    #[tool(
        description = "Detect if a page requires JavaScript rendering (Single Page Application). Checks for minimal content and SPA markers like <div id=\"root\"> or <div id=\"app\">."
    )]
    #[instrument(skip(self), fields(url = %params.url))]
    // serde_json::to_string cannot fail for a serde_json::Value.
    #[allow(clippy::expect_used)]
    async fn detect_spa(
        &self,
        Parameters(params): Parameters<DetectSpaParams>,
    ) -> Result<CallToolResult, McpError> {
        params.validate()?;

        let _permit = acquire_semaphore!(self, scraping);

        let url = url::Url::parse(&params.url).map_err(|e| {
            McpError::invalid_params(
                format!("invalid URL: {e}"),
                Some(serde_json::Value::String("url".to_string())),
            )
        })?;
        crate::mcp_server::ssrf::validate_url_no_ssrf(&url).await?;

        let start = Instant::now();
        // One run identity per tool call, shared by its success and error events (#501/#698).
        let root_correlation = webfang_core::domain::CorrelationId::new();
        let port = self.state.container.http_client();
        match port.get(url.as_str()).await {
            Ok(resp) => {
                self.state.record_scrape_identity(
                    "detect_spa",
                    domain_of(&params.url),
                    Outcome::Success,
                    1,
                    start,
                    &root_correlation,
                );
                let html = resp.body;
                let text = webfang_core::infrastructure::scraper::fallback::extract_text(&html);
                match webfang_core::application::scraper_service::detect_spa_content(
                    url.as_str(),
                    &text,
                    &html,
                ) {
                    Some(info) => {
                        let json = serde_json::json!({
                            "url": info.url,
                            "char_count": info.char_count,
                            "has_spa_markers": info.has_spa_markers,
                        });
                        Ok(CallToolResult::success(vec![Content::text(
                            serde_json::to_string_pretty(&json)
                                .expect("serializing JSON to a string cannot fail"),
                        )]))
                    },
                    None => Ok(CallToolResult::success(vec![Content::text(
                        "not an SPA - sufficient content found",
                    )])),
                }
            },
            Err(e) => {
                self.state.record_scrape_identity(
                    "detect_spa",
                    domain_of(&params.url),
                    Outcome::Error,
                    0,
                    start,
                    &root_correlation,
                );
                Ok(CallToolResult::error(vec![Content::text(format!(
                    "HTTP error: {e}"
                ))]))
            },
        }
    }
}

/// Keep only seed-host-internal URLs in the discovery output (REQ-01, SSRF
/// defense-in-depth).
///
/// The engine's internal-link gating already applies on the BFS crawl path,
/// but sitemap discovery returns every `<loc>` host-agnostic. This post-hoc
/// filter is the authoritative gate that ensures no external-domain or
/// forbidden-literal-IP URL ever reaches an MCP response, complementing the
/// entry-level SSRF validator. Each exclusion emits a structured `warn` with
/// the `url` field (REQ-01/REQ-07).
///
/// Returns the number of excluded URLs. `total_pages` / crawl counts are NOT
/// recomputed — they keep engine semantics (pages crawled, not links emitted).
fn filter_ssrf_safe(
    urls: &[webfang_core::domain::DiscoveredUrl],
    seed: &url::Url,
    out: &mut Vec<String>,
) -> usize {
    let seed_host = seed.host_str().unwrap_or(""); // mirrors crawl_task.rs internal-link anchor
    let mut excluded = 0usize;
    for d in urls {
        let internal =
            webfang_core::domain::url_validation::is_internal_link(d.url.as_str(), seed_host);
        if internal {
            // Hostnames compared here are non-literal hosts; literal IPs on a
            // non-seed host fall through to the exclusion branch below.
            out.push(d.url.to_string());
            continue;
        }
        excluded += 1;
        let reason = if webfang_core::infrastructure::ssrf::is_forbidden_literal_host(
            d.url.host_str().unwrap_or(""),
        ) {
            "forbidden_literal_ip"
        } else {
            "external_domain"
        };
        tracing::warn!(
            url = %d.url,
            reason = %reason,
            "discovered URL excluded from MCP response (SSRF defense-in-depth)"
        );
    }
    excluded
}

/// Build the scraping core router (8 tools for URL scraping and crawling).
///
/// Returns a partial router that is combined with the other category routers
/// via the `+` operator in
/// [`build_tool_router`](crate::mcp_server::handlers::build_tool_router).
pub fn build_router() -> ToolRouter<McpHandler> {
    McpHandler::tool_router_scraping()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::mcp_server::state::McpState;
    use rmcp::handler::server::wrapper::Parameters;
    use rmcp::model::CallToolResult;
    use tempfile::TempDir;
    use webfang_core::di::Container;
    use webfang_core::domain::CrawlerConfig;
    use webfang_core::infrastructure::config::ScraperConfig;

    async fn test_handler() -> (McpHandler, TempDir) {
        let tmp = TempDir::new().expect("create temp dir");
        let crawler_config =
            CrawlerConfig::new(url::Url::parse("https://example.com").expect("valid url"));
        let scraper_config = ScraperConfig {
            output_dir: tmp.path().to_path_buf(),
            ..Default::default()
        };
        let container = Container::new(crawler_config, scraper_config)
            .await
            .expect("create container");
        let mut state = McpState::new(container);
        // Determinism (#705): handler tests must stay offline — the robots
        // check performs a real robots.txt fetch, so unit tests drop the
        // fetcher instead of risking network access through loopback URLs.
        state.robots_fetcher = None;
        (McpHandler::new(state), tmp)
    }

    /// Assert that a handler rejected a loopback/private URL via the SSRF gate.
    fn assert_ssrf_rejected(res: Result<CallToolResult, McpError>) {
        let err = res.expect_err("loopback/internal URL must be blocked by SSRF");
        let msg = err.to_string();
        assert!(
            msg.contains("SSRF"),
            "error must report SSRF protection, got: {msg}"
        );
    }

    #[tokio::test]
    async fn scrape_url_rejects_loopback() {
        // SSRF protection must block requests to internal/loopback addresses
        // before any fetch happens (Bug #673).
        let (handler, _tmp) = test_handler().await;
        let res = handler
            .scrape_url(Parameters(ScrapeUrlParams {
                url: "http://127.0.0.1/".to_string(),
            }))
            .await;
        assert_ssrf_rejected(res);
    }

    #[tokio::test]
    async fn scrape_url_invalid_url_is_invalid_params() {
        let (handler, _tmp) = test_handler().await;
        let res = handler
            .scrape_url(Parameters(ScrapeUrlParams {
                url: "not a url".to_string(),
            }))
            .await;
        assert!(res.is_err(), "invalid URL must be a protocol error");
    }

    #[tokio::test]
    async fn scrape_with_options_rejects_loopback() {
        // SSRF protection must block internal/loopback addresses (Bug #673).
        let (handler, _tmp) = test_handler().await;
        let res = handler
            .scrape_with_options(Parameters(ScrapeWithOptionsParams {
                url: "http://127.0.0.1/".to_string(),
                max_pages: Some(1),
                download_images: Some(false),
                download_documents: Some(false),
                selector: None,
                ignore_robots: None,
            }))
            .await;
        assert_ssrf_rejected(res);
    }

    #[tokio::test]
    async fn scrape_with_options_invalid_url_is_invalid_params() {
        let (handler, _tmp) = test_handler().await;
        let res = handler
            .scrape_with_options(Parameters(ScrapeWithOptionsParams {
                url: "::bad::".to_string(),
                max_pages: None,
                download_images: None,
                download_documents: None,
                selector: None,
                ignore_robots: None,
            }))
            .await;
        assert!(res.is_err(), "invalid URL must be a protocol error");
    }

    #[tokio::test]
    async fn scrape_batch_rejects_loopback() {
        // SSRF protection must block internal/loopback addresses in a batch (Bug #673).
        let (handler, _tmp) = test_handler().await;
        let res = handler
            .scrape_batch(Parameters(ScrapeBatchParams {
                urls: vec!["http://127.0.0.1/".to_string()],
                concurrency: Some(2),
                ignore_robots: None,
            }))
            .await;
        assert_ssrf_rejected(res);
    }

    #[tokio::test]
    async fn scrape_batch_no_valid_urls_is_error() {
        let (handler, _tmp) = test_handler().await;
        // Params validation (#512) rejects unparseable URLs up front.
        let res = handler
            .scrape_batch(Parameters(ScrapeBatchParams {
                urls: vec!["not a url".to_string()],
                concurrency: None,
                ignore_robots: None,
            }))
            .await;
        assert!(
            res.is_err(),
            "invalid URLs must be a protocol error, got: {res:?}"
        );
    }

    #[test]
    fn zero_limits_are_rejected() {
        // Bug #597: concurrency:0 deadlocks buffer_unordered(0).
        // Bug #598: max_pages:0 panics mpsc::channel(0).
        // Both must be rejected up front with invalid_params.
        let batch = ScrapeBatchParams {
            urls: vec!["https://example.com".to_string()],
            concurrency: Some(0),
            ignore_robots: None,
        }
        .validate();
        assert!(batch.is_err(), "concurrency 0 must be rejected: {batch:?}");

        let crawl = CrawlSiteParams {
            url: "https://example.com".into(),
            max_depth: None,
            max_pages: Some(0),
        }
        .validate();
        assert!(crawl.is_err(), "max_pages 0 must be rejected: {crawl:?}");
    }

    #[tokio::test]
    async fn discover_urls_rejects_loopback() {
        // SSRF protection must block internal/loopback addresses (Bug #673).
        let (handler, _tmp) = test_handler().await;
        let res = handler
            .discover_urls(Parameters(DiscoverUrlsParams {
                url: "http://127.0.0.1/".to_string(),
            }))
            .await;
        assert_ssrf_rejected(res);
    }

    #[tokio::test]
    async fn discover_urls_invalid_url_is_invalid_params() {
        let (handler, _tmp) = test_handler().await;
        // Params validation (#512) rejects unparseable URLs up front.
        let res = handler
            .discover_urls(Parameters(DiscoverUrlsParams {
                url: "not a url".to_string(),
            }))
            .await;
        assert!(
            res.is_err(),
            "invalid URL must be a protocol error, got: {res:?}"
        );
    }

    #[tokio::test]
    async fn detect_spa_rejects_loopback() {
        // SSRF protection must block internal/loopback addresses (Bug #673).
        let (handler, _tmp) = test_handler().await;
        let res = handler
            .detect_spa(Parameters(DetectSpaParams {
                url: "http://127.0.0.1/".to_string(),
            }))
            .await;
        assert_ssrf_rejected(res);
    }

    #[tokio::test]
    async fn detect_spa_invalid_url_is_invalid_params() {
        let (handler, _tmp) = test_handler().await;
        // Params validation (#512) rejects unparseable URLs up front.
        let res = handler
            .detect_spa(Parameters(DetectSpaParams {
                url: "not a url".to_string(),
            }))
            .await;
        assert!(
            res.is_err(),
            "invalid URL must be a protocol error, got: {res:?}"
        );
    }

    #[tokio::test]
    async fn crawl_site_invalid_url_is_invalid_params() {
        let (handler, _tmp) = test_handler().await;
        let res = handler
            .crawl_site(Parameters(CrawlSiteParams {
                url: "not a url".to_string(),
                max_depth: None,
                max_pages: None,
            }))
            .await;
        assert!(res.is_err(), "invalid URL must be a protocol error");
    }

    #[tokio::test]
    async fn crawl_with_sitemap_invalid_url_is_invalid_params() {
        let (handler, _tmp) = test_handler().await;
        let res = handler
            .crawl_with_sitemap(Parameters(CrawlWithSitemapParams {
                url: "not a url".to_string(),
                sitemap_url: None,
            }))
            .await;
        assert!(res.is_err(), "invalid URL must be a protocol error");
    }

    /// REQ-01: the post-hoc filter keeps seed-host-internal URLs and drops
    /// external-domain and forbidden-literal-IP URLs, reporting the exclusion
    /// count. Empty input produces empty output with zero exclusions.
    #[test]
    fn filter_ssrf_safe_keeps_internal_drops_external_literal() {
        let seed = url::Url::parse("https://example.com/").expect("valid seed");
        let discovered = vec![
            webfang_core::domain::DiscoveredUrl::html(
                url::Url::parse("https://example.com/a").expect("valid url"),
                1,
                seed.clone(),
            ),
            webfang_core::domain::DiscoveredUrl::html(
                url::Url::parse("https://other.com/x").expect("valid url"),
                1,
                seed.clone(),
            ),
            webfang_core::domain::DiscoveredUrl::html(
                url::Url::parse("http://10.0.0.5/x").expect("valid url"),
                1,
                seed.clone(),
            ),
        ];

        let mut out = Vec::new();
        let excluded = filter_ssrf_safe(&discovered, &seed, &mut out);
        assert_eq!(
            out,
            vec!["https://example.com/a".to_string()],
            "only the seed-host URL survives"
        );
        assert_eq!(excluded, 2, "external + forbidden literal are excluded");

        let mut empty_out = Vec::new();
        assert_eq!(
            filter_ssrf_safe(&[], &seed, &mut empty_out),
            0,
            "empty input excludes nothing"
        );
        assert!(
            empty_out.is_empty(),
            "empty input keeps the output empty (established as the filtered case above returns entries)"
        );
    }

    /// REQ-02: an internal `sitemap_url` is rejected at entry (guard ON) with
    /// the SSRF message, before any sitemap fetch. The seed uses a public
    /// literal IP so its own validation resolves locally (no DNS dependency).
    #[tokio::test]
    async fn crawl_with_sitemap_rejects_internal_sitemap_url() {
        // Defensive under shared-process harnesses: the escape hatch must be
        // unset for this process so the guard is active. (nextest isolates
        // each test in its own process, so this is a no-op there.)
        std::env::remove_var("WEBFANG_MCP_DISABLE_SSRF");

        let (handler, _tmp) = test_handler().await;
        let res = handler
            .crawl_with_sitemap(Parameters(CrawlWithSitemapParams {
                url: "http://8.8.8.8/".to_string(),
                sitemap_url: Some("http://127.0.0.1/".to_string()),
            }))
            .await;
        assert_ssrf_rejected(res);
    }

    #[tokio::test]
    async fn discover_sitemap_invalid_url_is_invalid_params() {
        let (handler, _tmp) = test_handler().await;
        let res = handler
            .discover_sitemap(Parameters(DiscoverUrlsParams {
                url: "not a url".to_string(),
            }))
            .await;
        assert!(res.is_err(), "invalid URL must be a protocol error");
    }
}
