//! Scraping Core tools — 8 tools for URL scraping and crawling
//!
//! Tools: scrape_url, scrape_with_options, scrape_batch, crawl_site,
//! crawl_with_sitemap, discover_urls, discover_sitemap, detect_spa

use super::McpHandler;
use crate::mcp_server::metrics::{domain_of, Outcome, ScrapeEvent};
use crate::mcp_server::params::*;
use crate::mcp_server::selector_service;
use rmcp::handler::server::tool::ToolRouter;
use rmcp::handler::server::wrapper::Parameters;
use rmcp::tool;
use rmcp::tool_router;
use rmcp::{model::CallToolResult, model::Content, ErrorData as McpError};
use std::time::Instant;
use tracing::instrument;

#[tool_router(router = tool_router_scraping, vis = "pub")]
// Allow: the `tool_router_scraping` fn generated by rmcp-macros cannot be documented from this crate.
#[allow(missing_docs)]
impl McpHandler {
    /// Scrape a single URL and extract clean content using Readability algorithm
    #[tool(
        description = "Scrape a single URL and extract clean content using Readability algorithm (Firefox Reader mode). Returns title, content, excerpt, author, and date."
    )]
    #[instrument(skip(self), fields(url = %params.url))]
    async fn scrape_url(
        &self,
        Parameters(params): Parameters<ScrapeUrlParams>,
    ) -> Result<CallToolResult, McpError> {
        params.validate()?;

        let _permit = acquire_semaphore!(self, scraping);

        let url = url::Url::parse(&params.url).map_err(|e| {
            McpError::invalid_params(
                format!("invalid URL: {e}"),
                Some(serde_json::Value::String("url".to_string())),
            )
        })?;

        let start = Instant::now();
        let client = self.state.container.http_client().as_ref();
        match webfang_core::application::scraper_service::scrape_with_readability(client, &url)
            .await
        {
            Ok(results) => {
                let count = results.len();
                self.state.record_scrape(ScrapeEvent {
                    tool: "scrape_url",
                    domain: domain_of(&params.url),
                    outcome: Outcome::Success,
                    count,
                    duration: start.elapsed(),
                });
                let content = serde_json::to_string_pretty(&results)
                    .unwrap_or_else(|_| "failed to serialize".into());
                Ok(CallToolResult::success(vec![Content::text(content)]))
            },
            Err(e) => {
                self.state.record_scrape(ScrapeEvent {
                    tool: "scrape_url",
                    domain: domain_of(&params.url),
                    outcome: Outcome::Error,
                    count: 0,
                    duration: start.elapsed(),
                });
                Ok(CallToolResult::error(vec![Content::text(e.to_string())]))
            },
        }
    }

    /// Scrape a URL with configurable options (asset download, concurrency)
    #[tool(
        description = "Scrape a URL with configurable options including asset downloading, concurrency, and delay settings."
    )]
    #[instrument(skip(self), fields(url = %params.url))]
    async fn scrape_with_options(
        &self,
        Parameters(params): Parameters<ScrapeWithOptionsParams>,
    ) -> Result<CallToolResult, McpError> {
        params.validate()?;

        let _permit = acquire_semaphore!(self, scraping);

        let url = url::Url::parse(&params.url).map_err(|e| {
            McpError::invalid_params(
                format!("invalid URL: {e}"),
                Some(serde_json::Value::String("url".to_string())),
            )
        })?;

        let mut config = webfang_core::infrastructure::config::ScraperConfig::default();
        if let Some(max) = params.max_pages {
            config.max_pages = Some(max as usize);
        }
        if params.download_images == Some(true) {
            config.download_images = true;
        }
        if params.download_documents == Some(true) {
            config.download_documents = true;
        }
        // Wire CSS selector (defaults to "body" when not provided)
        if let Some(ref sel) = params.selector {
            config.selector = sel.clone();
        }

        let start = Instant::now();
        let client = self.state.container.http_client().as_ref();
        let dl = self
            .state
            .downloader
            .as_deref()
            .map(|d| d as &dyn webfang_core::domain::ports::AssetDownloaderPort);
        let inspector = self.state.inspector.as_deref();
        // An MCP tool call IS an operation (#501): mint the run-root identity
        // at the handler entry; the use case derives the page child from it.
        let root_correlation = webfang_core::domain::CorrelationId::new();
        match webfang_core::application::scraper_service::scrape_with_config(
            client,
            &url,
            &config,
            dl,
            inspector,
            None,
            &root_correlation,
        )
        .await
        {
            Ok(outcome) => {
                let count = outcome.results.len();
                self.state.record_scrape(ScrapeEvent {
                    tool: "scrape_with_options",
                    domain: domain_of(&params.url),
                    outcome: Outcome::Success,
                    count,
                    duration: start.elapsed(),
                });
                let response = selector_service::build_scrape_response(
                    outcome.results,
                    &outcome.extract_result,
                    &params.selector,
                );
                let content = serde_json::to_string_pretty(&response)
                    .unwrap_or_else(|_| "failed to serialize".into());
                Ok(CallToolResult::success(vec![Content::text(content)]))
            },
            Err(e) => {
                self.state.record_scrape(ScrapeEvent {
                    tool: "scrape_with_options",
                    domain: domain_of(&params.url),
                    outcome: Outcome::Error,
                    count: 0,
                    duration: start.elapsed(),
                });
                Ok(CallToolResult::error(vec![Content::text(e.to_string())]))
            },
        }
    }

    /// Scrape multiple URLs with concurrency control
    #[tool(
        description = "Scrape multiple URLs with concurrency control. Failed URLs are logged but don't stop the batch."
    )]
    #[instrument(skip(self), name = "mcp.scrape_batch", fields(url_count = params.urls.len()))]
    async fn scrape_batch(
        &self,
        Parameters(params): Parameters<ScrapeBatchParams>,
    ) -> Result<CallToolResult, McpError> {
        params.validate()?;

        tracing::info!("starting batch scrape");
        let _permit = acquire_semaphore!(self, scraping);

        let urls: Vec<url::Url> = params
            .urls
            .iter()
            .filter_map(|u| url::Url::parse(u).ok())
            .collect();

        if urls.is_empty() {
            return Ok(CallToolResult::error(vec![Content::text(
                "no valid URLs provided",
            )]));
        }

        let start = Instant::now();
        let domain = urls
            .first()
            .and_then(|u| u.host_str())
            .map(str::to_string)
            .unwrap_or_else(|| "unknown".to_string());
        let count = urls.len();

        let mut config = webfang_core::infrastructure::config::ScraperConfig::default();
        if let Some(c) = params.concurrency {
            config.scraper_concurrency = c;
        }

        let client = self.state.container.http_client().as_ref();
        let dl = self
            .state
            .downloader
            .as_deref()
            .map(|d| d as &dyn webfang_core::domain::ports::AssetDownloaderPort);
        match webfang_core::application::scraper_service::scrape_multiple_with_limit(
            client, &urls, &config, dl,
        )
        .await
        {
            Ok(outcome) => {
                let failed_count = outcome.failed.len();
                let outcome_type = if failed_count == 0 {
                    Outcome::Success
                } else if outcome.results.is_empty() {
                    Outcome::Error
                } else {
                    Outcome::Partial
                };
                self.state.record_scrape(ScrapeEvent {
                    tool: "scrape_batch",
                    domain,
                    outcome: outcome_type,
                    count,
                    duration: start.elapsed(),
                });
                tracing::info!(
                    "batch scrape complete: {} pages, {} failed",
                    outcome.results.len(),
                    failed_count
                );
                // Serialize the full outcome (results + failed) so the caller
                // knows exactly which URLs failed and why (issue #591).
                let content = serde_json::to_string_pretty(&outcome)
                    .unwrap_or_else(|_| "failed to serialize".into());
                Ok(CallToolResult::success(vec![Content::text(content)]))
            },
            Err(e) => {
                self.state.record_scrape(ScrapeEvent {
                    tool: "scrape_batch",
                    domain,
                    outcome: Outcome::Error,
                    count,
                    duration: start.elapsed(),
                });
                tracing::error!("batch scrape failed: {}", e);
                Ok(CallToolResult::error(vec![Content::text(e.to_string())]))
            },
        }
    }

    /// Crawl a website with BFS and depth limit
    #[tool(
        description = "Crawl a website using BFS with configurable depth limit, concurrency control, and rate limiting."
    )]
    #[instrument(skip(self), fields(url = %params.url))]
    // serde_json::to_string cannot fail for a serde_json::Value.
    #[allow(clippy::expect_used)]
    async fn crawl_site(
        &self,
        Parameters(params): Parameters<CrawlSiteParams>,
    ) -> Result<CallToolResult, McpError> {
        params.validate()?;

        let _permit = acquire_semaphore!(self, scraping);

        let seed_url = url::Url::parse(&params.url).map_err(|e| {
            McpError::invalid_params(
                format!("invalid URL: {e}"),
                Some(serde_json::Value::String("url".to_string())),
            )
        })?;

        let start = Instant::now();
        let crawler_config = webfang_core::domain::CrawlerConfig::builder(seed_url)
            .max_depth(params.max_depth.unwrap_or(3))
            .max_pages(params.max_pages.unwrap_or(100) as usize)
            .build();

        match webfang_core::application::crawler::crawl_site(crawler_config).await {
            Ok(result) => {
                let count = result.total_pages;
                self.state.record_scrape(ScrapeEvent {
                    tool: "crawl_site",
                    domain: domain_of(&params.url),
                    outcome: Outcome::Success,
                    count,
                    duration: start.elapsed(),
                });
                let urls: Vec<String> = result.urls.iter().map(|u| u.url.to_string()).collect();
                let json = serde_json::json!({
                    "urls": urls,
                    "total_pages": result.total_pages,
                    "errors": result.errors,
                    "error_breakdown": result.error_breakdown,
                });
                Ok(CallToolResult::success(vec![Content::text(
                    serde_json::to_string_pretty(&json)
                        .expect("serializing JSON to a string cannot fail"),
                )]))
            },
            Err(e) => {
                self.state.record_scrape(ScrapeEvent {
                    tool: "crawl_site",
                    domain: domain_of(&params.url),
                    outcome: Outcome::Error,
                    count: 0,
                    duration: start.elapsed(),
                });
                Ok(CallToolResult::error(vec![Content::text(e.to_string())]))
            },
        }
    }

    /// Discover and crawl URLs from a sitemap
    #[tool(
        description = "Discover URLs from a website's sitemap and crawl them. Auto-discovers sitemap from robots.txt if not provided."
    )]
    // serde_json::to_string cannot fail for a serde_json::Value.
    #[allow(clippy::expect_used)]
    #[instrument(skip(self), name = "mcp.crawl_with_sitemap", fields(url = %params.url))]
    async fn crawl_with_sitemap(
        &self,
        Parameters(params): Parameters<CrawlWithSitemapParams>,
    ) -> Result<CallToolResult, McpError> {
        params.validate()?;

        tracing::info!("starting sitemap crawl");
        let _permit = acquire_semaphore!(self, scraping);

        let seed_url = url::Url::parse(&params.url).map_err(|e| {
            tracing::error!("invalid URL: {}", e);
            McpError::invalid_params(
                format!("invalid URL: {e}"),
                Some(serde_json::Value::String("url".to_string())),
            )
        })?;
        let start = Instant::now();
        let config = webfang_core::domain::CrawlerConfig::new(seed_url);
        match webfang_core::application::crawler::crawl_with_sitemap(
            &params.url,
            params.sitemap_url.as_deref(),
            &config,
        )
        .await
        {
            Ok(urls) => {
                let count = urls.len();
                self.state.record_scrape(ScrapeEvent {
                    tool: "crawl_with_sitemap",
                    domain: domain_of(&params.url),
                    outcome: Outcome::Success,
                    count,
                    duration: start.elapsed(),
                });
                tracing::info!("sitemap crawl complete: {} urls found", urls.len());
                let url_strings: Vec<String> = urls.iter().map(|u| u.url.to_string()).collect();
                Ok(CallToolResult::success(vec![Content::text(
                    serde_json::to_string_pretty(&url_strings)
                        .expect("serializing JSON to a string cannot fail"),
                )]))
            },
            Err(e) => {
                self.state.record_scrape(ScrapeEvent {
                    tool: "crawl_with_sitemap",
                    domain: domain_of(&params.url),
                    outcome: Outcome::Error,
                    count: 0,
                    duration: start.elapsed(),
                });
                tracing::error!("sitemap crawl failed: {}", e);
                Ok(CallToolResult::error(vec![Content::text(e.to_string())]))
            },
        }
    }

    /// Discover URLs from a single page's HTML links
    #[tool(
        description = "Fetch a single page and extract all internal links. Lightweight URL discovery without full crawl."
    )]
    #[instrument(skip(self), fields(url = %params.url))]
    async fn discover_urls(
        &self,
        Parameters(params): Parameters<DiscoverUrlsParams>,
    ) -> Result<CallToolResult, McpError> {
        params.validate()?;

        let _permit = acquire_semaphore!(self, scraping);

        let start = Instant::now();
        let port = self.state.container.http_client();
        match port.get(&params.url).await {
            Ok(resp) => {
                let html = resp.body;
                match webfang_core::infrastructure::crawler::extract_links(&html, &params.url) {
                    Ok(links) => {
                        let count = links.len();
                        self.state.record_scrape(ScrapeEvent {
                            tool: "discover_urls",
                            domain: domain_of(&params.url),
                            outcome: Outcome::Success,
                            count,
                            duration: start.elapsed(),
                        });
                        let content = serde_json::to_string_pretty(&links)
                            .unwrap_or_else(|_| "failed to serialize".into());
                        Ok(CallToolResult::success(vec![Content::text(content)]))
                    },
                    Err(e) => {
                        self.state.record_scrape(ScrapeEvent {
                            tool: "discover_urls",
                            domain: domain_of(&params.url),
                            outcome: Outcome::Error,
                            count: 0,
                            duration: start.elapsed(),
                        });
                        Ok(CallToolResult::error(vec![Content::text(e.to_string())]))
                    },
                }
            },
            Err(e) => {
                self.state.record_scrape(ScrapeEvent {
                    tool: "discover_urls",
                    domain: domain_of(&params.url),
                    outcome: Outcome::Error,
                    count: 0,
                    duration: start.elapsed(),
                });
                Ok(CallToolResult::error(vec![Content::text(format!(
                    "HTTP error: {e}"
                ))]))
            },
        }
    }

    /// Auto-discover sitemap URL from robots.txt or common locations
    #[tool(
        description = "Auto-discover a website's sitemap URL by checking robots.txt and common locations (/sitemap.xml, /sitemap_index.xml, etc.)."
    )]
    #[instrument(skip(self), fields(url = %params.url))]
    async fn discover_sitemap(
        &self,
        Parameters(params): Parameters<DiscoverUrlsParams>,
    ) -> Result<CallToolResult, McpError> {
        params.validate()?;

        let _permit = acquire_semaphore!(self, scraping);

        let seed = url::Url::parse(&params.url).map_err(|e| {
            McpError::invalid_params(
                format!("invalid URL: {e}"),
                Some(serde_json::Value::String("url".to_string())),
            )
        })?;
        let start = Instant::now();
        let crawler_config = webfang_core::domain::CrawlerConfig::new(seed);

        match webfang_core::application::crawler::crawl_with_sitemap(
            &params.url,
            None,
            &crawler_config,
        )
        .await
        {
            Ok(discovered) => {
                let count = discovered.len();
                self.state.record_scrape(ScrapeEvent {
                    tool: "discover_sitemap",
                    domain: domain_of(&params.url),
                    outcome: Outcome::Success,
                    count,
                    duration: start.elapsed(),
                });
                let urls: Vec<String> = discovered.into_iter().map(|d| d.url.to_string()).collect();
                let content = serde_json::to_string_pretty(&urls)
                    .unwrap_or_else(|_| "failed to serialize".into());
                Ok(CallToolResult::success(vec![Content::text(content)]))
            },
            Err(e) => {
                self.state.record_scrape(ScrapeEvent {
                    tool: "discover_sitemap",
                    domain: domain_of(&params.url),
                    outcome: Outcome::Error,
                    count: 0,
                    duration: start.elapsed(),
                });
                Ok(CallToolResult::error(vec![Content::text(e.to_string())]))
            },
        }
    }

    /// Detect if a URL requires JavaScript rendering (SPA)
    #[tool(
        description = "Detect if a page requires JavaScript rendering (Single Page Application). Checks for minimal content and SPA markers like <div id=\"root\"> or <div id=\"app\">."
    )]
    #[instrument(skip(self), fields(url = %params.url))]
    // serde_json::to_string cannot fail for a serde_json::Value.
    #[allow(clippy::expect_used)]
    async fn detect_spa(
        &self,
        Parameters(params): Parameters<DetectSpaParams>,
    ) -> Result<CallToolResult, McpError> {
        params.validate()?;

        let _permit = acquire_semaphore!(self, scraping);

        let start = Instant::now();
        let port = self.state.container.http_client();
        match port.get(&params.url).await {
            Ok(resp) => {
                self.state.record_scrape(ScrapeEvent {
                    tool: "detect_spa",
                    domain: domain_of(&params.url),
                    outcome: Outcome::Success,
                    count: 1,
                    duration: start.elapsed(),
                });
                let html = resp.body;
                let text = webfang_core::infrastructure::scraper::fallback::extract_text(&html);
                match webfang_core::application::scraper_service::detect_spa_content(
                    &params.url,
                    &text,
                    &html,
                ) {
                    Some(info) => {
                        let json = serde_json::json!({
                            "url": info.url,
                            "char_count": info.char_count,
                            "has_spa_markers": info.has_spa_markers,
                        });
                        Ok(CallToolResult::success(vec![Content::text(
                            serde_json::to_string_pretty(&json)
                                .expect("serializing JSON to a string cannot fail"),
                        )]))
                    },
                    None => Ok(CallToolResult::success(vec![Content::text(
                        "not an SPA - sufficient content found",
                    )])),
                }
            },
            Err(e) => {
                self.state.record_scrape(ScrapeEvent {
                    tool: "detect_spa",
                    domain: domain_of(&params.url),
                    outcome: Outcome::Error,
                    count: 0,
                    duration: start.elapsed(),
                });
                Ok(CallToolResult::error(vec![Content::text(format!(
                    "HTTP error: {e}"
                ))]))
            },
        }
    }
}

/// Build the scraping core router (8 tools for URL scraping and crawling).
///
/// Returns a partial router that is combined with the other category routers
/// via the `+` operator in
/// [`build_tool_router`](crate::mcp_server::handlers::build_tool_router).
pub fn build_router() -> ToolRouter<McpHandler> {
    McpHandler::tool_router_scraping()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::mcp_server::state::McpState;
    use rmcp::handler::server::wrapper::Parameters;
    use rmcp::model::CallToolResult;
    use tempfile::TempDir;
    use webfang_core::di::Container;
    use webfang_core::domain::CrawlerConfig;
    use webfang_core::infrastructure::config::ScraperConfig;
    use wiremock::matchers::{method, path};
    use wiremock::{Mock, MockServer, ResponseTemplate};

    const ARTICLE_HTML: &str = r#"<!DOCTYPE html>
<html><head><title>Test Page</title></head>
<body><article><h1>Main Heading</h1>
<p>This is the content of the article. It has enough text to be extracted by Readability.</p>
</article></body></html>"#;

    const LINKS_HTML: &str = r#"<html><body>
<a href="/internal">internal</a>
<a href="https://external.com/x">external</a>
</body></html>"#;

    async fn test_handler() -> (McpHandler, TempDir) {
        let tmp = TempDir::new().expect("create temp dir");
        let crawler_config =
            CrawlerConfig::new(url::Url::parse("https://example.com").expect("valid url"));
        let scraper_config = ScraperConfig {
            output_dir: tmp.path().to_path_buf(),
            ..Default::default()
        };
        let container = Container::new(crawler_config, scraper_config)
            .await
            .expect("create container");
        let state = McpState::new(container);
        (McpHandler::new(state), tmp)
    }

    async fn mock_article() -> MockServer {
        let server = MockServer::start().await;
        Mock::given(method("GET"))
            .and(path("/"))
            .respond_with(ResponseTemplate::new(200).set_body_string(ARTICLE_HTML))
            .mount(&server)
            .await;
        server
    }

    fn result_text(result: &CallToolResult) -> String {
        serde_json::to_value(result)
            .ok()
            .and_then(|v| v.get("content").and_then(|c| c.as_array()).cloned())
            .and_then(|arr| arr.first().cloned())
            .and_then(|first| {
                first
                    .get("text")
                    .and_then(|t| t.as_str())
                    .map(str::to_string)
            })
            .unwrap_or_default()
    }

    #[tokio::test]
    async fn scrape_url_success_extracts_content() {
        let (handler, _tmp) = test_handler().await;
        let server = mock_article().await;
        let res = handler
            .scrape_url(Parameters(ScrapeUrlParams { url: server.uri() }))
            .await
            .expect("scrape_url returns Ok");
        let text = result_text(&res);
        assert!(
            text.contains("Main Heading"),
            "scraped content must include heading: {text}"
        );
    }

    #[tokio::test]
    async fn scrape_url_invalid_url_is_invalid_params() {
        let (handler, _tmp) = test_handler().await;
        let res = handler
            .scrape_url(Parameters(ScrapeUrlParams {
                url: "not a url".to_string(),
            }))
            .await;
        assert!(res.is_err(), "invalid URL must be a protocol error");
    }

    #[tokio::test]
    async fn scrape_url_http_error_is_tool_error() {
        let (handler, _tmp) = test_handler().await;
        // Port with nothing listening → connection refused → HttpError → isError.
        let res = handler
            .scrape_url(Parameters(ScrapeUrlParams {
                url: "http://127.0.0.1:1/".to_string(),
            }))
            .await
            .expect("scrape_url returns Ok on http error");
        let json = serde_json::to_value(&res).expect("serialize");
        assert_eq!(
            json.get("isError").and_then(|v| v.as_bool()),
            Some(true),
            "http error must map to isError:true, got: {json}"
        );
    }

    #[tokio::test]
    async fn scrape_with_options_success() {
        let (handler, _tmp) = test_handler().await;
        let server = mock_article().await;
        let res = handler
            .scrape_with_options(Parameters(ScrapeWithOptionsParams {
                url: server.uri(),
                max_pages: Some(1),
                download_images: Some(false),
                download_documents: Some(false),
                selector: None,
            }))
            .await
            .expect("scrape_with_options returns Ok");
        let text = result_text(&res);
        assert!(
            text.contains("Main Heading"),
            "scrape_with_options must extract content: {text}"
        );
    }

    #[tokio::test]
    async fn scrape_with_options_invalid_url_is_invalid_params() {
        let (handler, _tmp) = test_handler().await;
        let res = handler
            .scrape_with_options(Parameters(ScrapeWithOptionsParams {
                url: "::bad::".to_string(),
                max_pages: None,
                download_images: None,
                download_documents: None,
                selector: None,
            }))
            .await;
        assert!(res.is_err(), "invalid URL must be a protocol error");
    }

    #[tokio::test]
    async fn scrape_batch_success() {
        let (handler, _tmp) = test_handler().await;
        let server = mock_article().await;
        let res = handler
            .scrape_batch(Parameters(ScrapeBatchParams {
                urls: vec![server.uri()],
                concurrency: Some(2),
            }))
            .await
            .expect("scrape_batch returns Ok");
        let text = result_text(&res);
        assert!(
            text.contains("Main Heading"),
            "batch must scrape content: {text}"
        );
    }

    #[tokio::test]
    async fn scrape_batch_no_valid_urls_is_error() {
        let (handler, _tmp) = test_handler().await;
        // Params validation (#512) rejects unparseable URLs up front.
        let res = handler
            .scrape_batch(Parameters(ScrapeBatchParams {
                urls: vec!["not a url".to_string()],
                concurrency: None,
            }))
            .await;
        assert!(
            res.is_err(),
            "invalid URLs must be a protocol error, got: {res:?}"
        );
    }

    #[test]
    fn zero_limits_are_rejected() {
        // Bug #597: concurrency:0 deadlocks buffer_unordered(0).
        // Bug #598: max_pages:0 panics mpsc::channel(0).
        // Both must be rejected up front with invalid_params.
        let batch = ScrapeBatchParams {
            urls: vec!["https://example.com".to_string()],
            concurrency: Some(0),
        }
        .validate();
        assert!(batch.is_err(), "concurrency 0 must be rejected: {batch:?}");

        let crawl = CrawlSiteParams {
            url: "https://example.com".into(),
            max_depth: None,
            max_pages: Some(0),
        }
        .validate();
        assert!(crawl.is_err(), "max_pages 0 must be rejected: {crawl:?}");
    }

    #[tokio::test]
    async fn discover_urls_success_extracts_links() {
        let (handler, _tmp) = test_handler().await;
        let server = MockServer::start().await;
        Mock::given(method("GET"))
            .and(path("/"))
            .respond_with(ResponseTemplate::new(200).set_body_string(LINKS_HTML))
            .mount(&server)
            .await;
        let res = handler
            .discover_urls(Parameters(DiscoverUrlsParams { url: server.uri() }))
            .await
            .expect("discover_urls returns Ok");
        let text = result_text(&res);
        assert!(
            text.contains("internal"),
            "discover_urls must extract internal link: {text}"
        );
    }

    #[tokio::test]
    async fn discover_urls_invalid_url_is_invalid_params() {
        let (handler, _tmp) = test_handler().await;
        // Params validation (#512) rejects unparseable URLs up front.
        let res = handler
            .discover_urls(Parameters(DiscoverUrlsParams {
                url: "not a url".to_string(),
            }))
            .await;
        assert!(
            res.is_err(),
            "invalid URL must be a protocol error, got: {res:?}"
        );
    }

    #[tokio::test]
    async fn discover_urls_http_error_is_tool_error() {
        let (handler, _tmp) = test_handler().await;
        let res = handler
            .discover_urls(Parameters(DiscoverUrlsParams {
                url: "http://127.0.0.1:1/".to_string(),
            }))
            .await
            .expect("discover_urls returns Ok on http error");
        let json = serde_json::to_value(&res).expect("serialize");
        assert_eq!(
            json.get("isError").and_then(|v| v.as_bool()),
            Some(true),
            "http error must map to isError:true, got: {json}"
        );
    }

    #[tokio::test]
    async fn detect_spa_sufficient_content_is_not_spa() {
        let (handler, _tmp) = test_handler().await;
        let server = MockServer::start().await;
        let body = "<html><body><p>This page has plenty of substantive readable content that comfortably exceeds the SPA minimum content threshold used by the detector logic.</p></body></html>";
        Mock::given(method("GET"))
            .and(path("/"))
            .respond_with(ResponseTemplate::new(200).set_body_string(body))
            .mount(&server)
            .await;
        let res = handler
            .detect_spa(Parameters(DetectSpaParams { url: server.uri() }))
            .await
            .expect("detect_spa returns Ok");
        let text = result_text(&res);
        assert!(
            text.contains("not an SPA"),
            "sufficient content must report not-an-SPA: {text}"
        );
    }

    #[tokio::test]
    async fn detect_spa_invalid_url_is_invalid_params() {
        let (handler, _tmp) = test_handler().await;
        // Params validation (#512) rejects unparseable URLs up front.
        let res = handler
            .detect_spa(Parameters(DetectSpaParams {
                url: "not a url".to_string(),
            }))
            .await;
        assert!(
            res.is_err(),
            "invalid URL must be a protocol error, got: {res:?}"
        );
    }

    #[tokio::test]
    async fn crawl_site_invalid_url_is_invalid_params() {
        let (handler, _tmp) = test_handler().await;
        let res = handler
            .crawl_site(Parameters(CrawlSiteParams {
                url: "not a url".to_string(),
                max_depth: None,
                max_pages: None,
            }))
            .await;
        assert!(res.is_err(), "invalid URL must be a protocol error");
    }

    #[tokio::test]
    async fn crawl_with_sitemap_invalid_url_is_invalid_params() {
        let (handler, _tmp) = test_handler().await;
        let res = handler
            .crawl_with_sitemap(Parameters(CrawlWithSitemapParams {
                url: "not a url".to_string(),
                sitemap_url: None,
            }))
            .await;
        assert!(res.is_err(), "invalid URL must be a protocol error");
    }

    #[tokio::test]
    async fn discover_sitemap_invalid_url_is_invalid_params() {
        let (handler, _tmp) = test_handler().await;
        let res = handler
            .discover_sitemap(Parameters(DiscoverUrlsParams {
                url: "not a url".to_string(),
            }))
            .await;
        assert!(res.is_err(), "invalid URL must be a protocol error");
    }
}
