//! Scraping Core tools — 8 tools for URL scraping and crawling
//!
//! Tools: scrape_url, scrape_with_options, scrape_batch, crawl_site,
//! crawl_with_sitemap, discover_urls, discover_sitemap, detect_spa

use super::McpHandler;
use crate::mcp_server::metrics::{domain_of, Outcome};
use crate::mcp_server::params::*;
use crate::mcp_server::selector_service;
use rmcp::handler::server::tool::ToolRouter;
use rmcp::handler::server::wrapper::Parameters;
use rmcp::tool;
use rmcp::tool_router;
use rmcp::{model::CallToolResult, model::Content, ErrorData as McpError};
use std::time::Instant;
use tracing::instrument;

#[tool_router(router = tool_router_scraping, vis = "pub")]
// Allow: the `tool_router_scraping` fn generated by rmcp-macros cannot be documented from this crate.
#[allow(missing_docs)]
impl McpHandler {
    /// Scrape a single URL and extract clean content using Readability algorithm
    ///
    /// Respects the site's robots.txt: a disallowed URL is rejected with a
    /// `robots.txt` error before any fetch (#749, uniform with #697).
    #[tool(
        description = "Scrape a single URL and extract clean content using Readability algorithm (Firefox Reader mode). Returns title, content, excerpt, author, and date."
    )]
    #[instrument(skip(self), fields(url = %params.url))]
    async fn scrape_url(
        &self,
        Parameters(params): Parameters<ScrapeUrlParams>,
    ) -> Result<CallToolResult, McpError> {
        params.validate()?;

        let _permit = acquire_semaphore!(self, scraping);

        let url = url::Url::parse(&params.url).map_err(|e| {
            McpError::invalid_params(
                format!("invalid URL: {e}"),
                Some(serde_json::Value::String("url".to_string())),
            )
        })?;

        crate::mcp_server::ssrf::validate_url_no_ssrf(&url).await?;

        let start = Instant::now();
        // One run identity per tool call, shared by its success and error events (#501/#698).
        let root_correlation = webfang_core::domain::CorrelationId::new();
        // robots.txt gate BEFORE any fetch (#749): a disallowed URL is rejected
        // without touching the network, mirroring `scrape_with_options` (#697).
        if let Some(err) = self.state.robots_denied_for(&url).await {
            self.state.record_scrape_identity(
                "scrape_url",
                domain_of(&params.url),
                Outcome::Error,
                0,
                start,
                &root_correlation,
            );
            return Ok(CallToolResult::error(vec![Content::text(err.to_string())]));
        }
        let client = self.state.container.http_client().as_ref();
        match webfang_core::application::scraper_service::scrape_with_readability(client, &url)
            .await
        {
            Ok(results) => {
                let count = results.len();
                self.state.record_scrape_identity(
                    "scrape_url",
                    domain_of(&params.url),
                    Outcome::Success,
                    count,
                    start,
                    &root_correlation,
                );
                let content = serde_json::to_string_pretty(&results)
                    .unwrap_or_else(|_| "failed to serialize".into());
                Ok(CallToolResult::success(vec![Content::text(content)]))
            },
            Err(e) => {
                self.state.record_scrape_identity(
                    "scrape_url",
                    domain_of(&params.url),
                    Outcome::Error,
                    0,
                    start,
                    &root_correlation,
                );
                Ok(CallToolResult::error(vec![Content::text(e.to_string())]))
            },
        }
    }

    /// Scrape a URL with configurable options (asset download, concurrency)
    #[tool(
        description = "Scrape a URL with configurable options including asset downloading, concurrency, and delay settings."
    )]
    #[instrument(skip(self), fields(url = %params.url))]
    async fn scrape_with_options(
        &self,
        Parameters(params): Parameters<ScrapeWithOptionsParams>,
    ) -> Result<CallToolResult, McpError> {
        params.validate()?;

        let _permit = acquire_semaphore!(self, scraping);

        let url = url::Url::parse(&params.url).map_err(|e| {
            McpError::invalid_params(
                format!("invalid URL: {e}"),
                Some(serde_json::Value::String("url".to_string())),
            )
        })?;

        crate::mcp_server::ssrf::validate_url_no_ssrf(&url).await?;

        let mut config = webfang_core::infrastructure::config::ScraperConfig::default();
        if let Some(max) = params.max_pages {
            config.max_pages = Some(max as usize);
        }
        if params.download_images == Some(true) {
            config.download_images = true;
        }
        if params.download_documents == Some(true) {
            config.download_documents = true;
        }
        // Wire CSS selector (defaults to "body" when not provided)
        if let Some(ref sel) = params.selector {
            config.selector = sel.clone();
        }

        let start = Instant::now();
        let client = self.state.container.http_client().as_ref();
        let dl = self
            .state
            .downloader
            .as_deref()
            .map(|d| d as &dyn webfang_core::domain::ports::AssetDownloaderPort);
        let inspector = self.state.inspector.as_deref();
        // robots.txt enforcement (#697): shared fetcher from the state; the
        // tool-level opt-out is `params.ignore_robots`.
        let robots = self.state.robots_fetcher.as_deref();
        let ignore_robots = params.ignore_robots.unwrap_or(false);
        // An MCP tool call IS an operation (#501): mint the run-root identity
        // at the handler entry; the use case derives the page child from it.
        let root_correlation = webfang_core::domain::CorrelationId::new();
        match webfang_core::application::scraper_service::scrape_with_config(
            client,
            &url,
            &config,
            dl,
            inspector,
            None,
            robots,
            ignore_robots,
            &root_correlation,
        )
        .await
        {
            Ok(outcome) => {
                let count = outcome.results.len();
                self.state.record_scrape_identity(
                    "scrape_with_options",
                    domain_of(&params.url),
                    Outcome::Success,
                    count,
                    start,
                    &root_correlation,
                );
                let response = selector_service::build_scrape_response(
                    outcome.results,
                    &outcome.extract_result,
                    &params.selector,
                );
                let content = serde_json::to_string_pretty(&response)
                    .unwrap_or_else(|_| "failed to serialize".into());
                Ok(CallToolResult::success(vec![Content::text(content)]))
            },
            Err(e) => {
                self.state.record_scrape_identity(
                    "scrape_with_options",
                    domain_of(&params.url),
                    Outcome::Error,
                    0,
                    start,
                    &root_correlation,
                );
                Ok(CallToolResult::error(vec![Content::text(e.to_string())]))
            },
        }
    }

    /// Scrape multiple URLs with concurrency control
    #[tool(
        description = "Scrape multiple URLs with concurrency control. Failed URLs are logged but don't stop the batch."
    )]
    #[instrument(skip(self), name = "mcp.scrape_batch", fields(url_count = params.urls.len()))]
    async fn scrape_batch(
        &self,
        Parameters(params): Parameters<ScrapeBatchParams>,
    ) -> Result<CallToolResult, McpError> {
        params.validate()?;

        tracing::info!("starting batch scrape");
        let _permit = acquire_semaphore!(self, scraping);

        let mut urls: Vec<url::Url> = Vec::with_capacity(params.urls.len());
        for raw in &params.urls {
            let url = url::Url::parse(raw).map_err(|e| {
                McpError::invalid_params(
                    format!("invalid URL: {e}"),
                    Some(serde_json::Value::String("urls".to_string())),
                )
            })?;
            crate::mcp_server::ssrf::validate_url_no_ssrf(&url).await?;
            urls.push(url);
        }

        if urls.is_empty() {
            return Ok(CallToolResult::error(vec![Content::text(
                "no valid URLs provided",
            )]));
        }

        let start = Instant::now();
        // One run identity per tool call, shared by its success and error events (#501/#698).
        let root_correlation = webfang_core::domain::CorrelationId::new();
        let domain = urls
            .first()
            .and_then(|u| u.host_str())
            .map(str::to_string)
            .unwrap_or_else(|| "unknown".to_string());
        let count = urls.len();

        let mut config = webfang_core::infrastructure::config::ScraperConfig::default();
        if let Some(c) = params.concurrency {
            config.scraper_concurrency = c;
        }

        let client = self.state.container.http_client().as_ref();
        let dl = self
            .state
            .downloader
            .as_deref()
            .map(|d| d as &dyn webfang_core::domain::ports::AssetDownloaderPort);
        // robots.txt enforcement (#697): shared fetcher from the state; the
        // tool-level opt-out is `params.ignore_robots`.
        let robots = self.state.robots_fetcher.as_deref();
        let ignore_robots = params.ignore_robots.unwrap_or(false);
        match webfang_core::application::scraper_service::scrape_multiple_with_limit(
            client,
            &urls,
            &config,
            dl,
            robots,
            ignore_robots,
        )
        .await
        {
            Ok(outcome) => {
                let failed_count = outcome.failed.len();
                // Per-domain attribution (#696): a batch may span multiple
                // hosts, so metrics are grouped by the REAL host of each
                // result/failure instead of assuming `urls.first()`. All
                // events share the run-root correlation (#501/#698).
                record_batch_metrics_by_domain(&self.state, &outcome, start, &root_correlation);
                tracing::info!(
                    "batch scrape complete: {} pages, {} failed",
                    outcome.results.len(),
                    failed_count
                );
                // Serialize the full outcome (results + failed) so the caller
                // knows exactly which URLs failed and why (issue #591).
                let content = serde_json::to_string_pretty(&outcome)
                    .unwrap_or_else(|_| "failed to serialize".into());
                Ok(CallToolResult::success(vec![Content::text(content)]))
            },
            Err(e) => {
                self.state.record_scrape_identity(
                    "scrape_batch",
                    domain,
                    Outcome::Error,
                    count,
                    start,
                    &root_correlation,
                );
                tracing::error!("batch scrape failed: {}", e);
                Ok(CallToolResult::error(vec![Content::text(e.to_string())]))
            },
        }
    }

    /// Crawl a website with BFS and depth limit
    #[tool(
        description = "Crawl a website using BFS with configurable depth limit, concurrency control, and rate limiting."
    )]
    #[instrument(skip(self), fields(url = %params.url))]
    // serde_json::to_string cannot fail for a serde_json::Value.
    #[allow(clippy::expect_used)]
    async fn crawl_site(
        &self,
        Parameters(params): Parameters<CrawlSiteParams>,
    ) -> Result<CallToolResult, McpError> {
        params.validate()?;

        let _permit = acquire_semaphore!(self, scraping);

        let seed_url = url::Url::parse(&params.url).map_err(|e| {
            McpError::invalid_params(
                format!("invalid URL: {e}"),
                Some(serde_json::Value::String("url".to_string())),
            )
        })?;

        crate::mcp_server::ssrf::validate_url_no_ssrf(&seed_url).await?;

        let start = Instant::now();
        // One run identity per tool call, shared by its success and error events (#501/#698).
        let root_correlation = webfang_core::domain::CorrelationId::new();
        // Clone: the builder consumes `seed_url` and the Ok arm re-uses it as
        // the filter anchor (the config itself is moved into the crawl).
        let crawler_config = webfang_core::domain::CrawlerConfig::builder(seed_url.clone())
            .max_depth(params.max_depth.unwrap_or(3))
            .max_pages(params.max_pages.unwrap_or(100) as usize)
            .build();

        match webfang_core::application::crawler::crawl_site(crawler_config).await {
            Ok(result) => {
                let count = result.total_pages;
                self.state.record_scrape_identity(
                    "crawl_site",
                    domain_of(&params.url),
                    Outcome::Success,
                    count,
                    start,
                    &root_correlation,
                );
                // REQ-01: filter discovered URLs before responding — keep only
                // seed-host-internal entries; exclusions warn with the URL.
                let mut urls = Vec::with_capacity(result.urls.len());
                filter_ssrf_safe(&result.urls, &seed_url, &mut urls);
                let json = serde_json::json!({
                    "urls": urls,
                    "total_pages": result.total_pages,
                    "errors": result.errors,
                    "error_breakdown": result.error_breakdown,
                });
                Ok(CallToolResult::success(vec![Content::text(
                    serde_json::to_string_pretty(&json)
                        .expect("serializing JSON to a string cannot fail"),
                )]))
            },
            Err(e) => {
                self.state.record_scrape_identity(
                    "crawl_site",
                    domain_of(&params.url),
                    Outcome::Error,
                    0,
                    start,
                    &root_correlation,
                );
                Ok(CallToolResult::error(vec![Content::text(e.to_string())]))
            },
        }
    }

    /// Discover and crawl URLs from a sitemap
    #[tool(
        description = "Discover URLs from a website's sitemap and crawl them. Auto-discovers sitemap from robots.txt if not provided."
    )]
    // serde_json::to_string cannot fail for a serde_json::Value.
    #[allow(clippy::expect_used)]
    #[instrument(skip(self), name = "mcp.crawl_with_sitemap", fields(url = %params.url))]
    async fn crawl_with_sitemap(
        &self,
        Parameters(params): Parameters<CrawlWithSitemapParams>,
    ) -> Result<CallToolResult, McpError> {
        params.validate()?;

        tracing::info!("starting sitemap crawl");
        let _permit = acquire_semaphore!(self, scraping);

        let seed_url = url::Url::parse(&params.url).map_err(|e| {
            tracing::error!("invalid URL: {}", e);
            McpError::invalid_params(
                format!("invalid URL: {e}"),
                Some(serde_json::Value::String("url".to_string())),
            )
        })?;
        crate::mcp_server::ssrf::validate_url_no_ssrf(&seed_url).await?;

        // REQ-02: validate the explicit sitemap URL at entry, BEFORE any
        // sitemap fetch (guard ON unless disabled via env for tests).
        if let Some(s) = &params.sitemap_url {
            let sitemap = url::Url::parse(s).map_err(|e| {
                McpError::invalid_params(format!("URL de sitemap inválida: {e}"), None)
            })?;
            crate::mcp_server::ssrf::validate_url_no_ssrf(&sitemap).await?;
        }

        let start = Instant::now();
        // One run identity per tool call, shared by its success and error events (#501/#698).
        let root_correlation = webfang_core::domain::CorrelationId::new();
        // Clone: `CrawlerConfig::new` consumes `seed_url` and the Ok arm
        // re-uses it as the filter anchor.
        let config = webfang_core::domain::CrawlerConfig::new(seed_url.clone());

        match webfang_core::application::crawler::crawl_with_sitemap(
            &params.url,
            params.sitemap_url.as_deref(),
            &config,
        )
        .await
        {
            Ok(urls) => {
                let count = urls.len();
                self.state.record_scrape_identity(
                    "crawl_with_sitemap",
                    domain_of(&params.url),
                    Outcome::Success,
                    count,
                    start,
                    &root_correlation,
                );
                tracing::info!("sitemap crawl complete: {} urls found", urls.len());
                // REQ-01: filter discovered URLs before responding. Sitemap
                // discovery is host-agnostic — the filter is the gate that
                // drops external-domain and forbidden-literal-IP entries.
                let mut url_strings = Vec::with_capacity(urls.len());
                filter_ssrf_safe(&urls, &seed_url, &mut url_strings);
                Ok(CallToolResult::success(vec![Content::text(
                    serde_json::to_string_pretty(&url_strings)
                        .expect("serializing JSON to a string cannot fail"),
                )]))
            },
            Err(e) => {
                self.state.record_scrape_identity(
                    "crawl_with_sitemap",
                    domain_of(&params.url),
                    Outcome::Error,
                    0,
                    start,
                    &root_correlation,
                );
                tracing::error!("sitemap crawl failed: {}", e);
                Ok(CallToolResult::error(vec![Content::text(e.to_string())]))
            },
        }
    }

    /// Discover URLs from a single page's HTML links
    ///
    /// Respects the site's robots.txt: a disallowed URL is rejected with a
    /// `robots.txt` error before any fetch (#749, uniform with #697).
    #[tool(
        description = "Fetch a single page and extract all internal links. Lightweight URL discovery without full crawl."
    )]
    #[instrument(skip(self), fields(url = %params.url))]
    async fn discover_urls(
        &self,
        Parameters(params): Parameters<DiscoverUrlsParams>,
    ) -> Result<CallToolResult, McpError> {
        params.validate()?;

        let _permit = acquire_semaphore!(self, scraping);

        let url = url::Url::parse(&params.url).map_err(|e| {
            McpError::invalid_params(
                format!("invalid URL: {e}"),
                Some(serde_json::Value::String("url".to_string())),
            )
        })?;
        crate::mcp_server::ssrf::validate_url_no_ssrf(&url).await?;

        let start = Instant::now();
        // One run identity per tool call, shared by its success and error events (#501/#698).
        let root_correlation = webfang_core::domain::CorrelationId::new();
        // robots.txt gate BEFORE any fetch (#749).
        if let Some(robots_error) = robots_denied_response(
            self,
            "discover_urls",
            &url,
            &params.url,
            start,
            &root_correlation,
        )
        .await
        {
            return Ok(robots_error);
        }
        let port = self.state.container.http_client();
        match port.get(url.as_str()).await {
            Ok(resp) => {
                // A non-2xx response (e.g. 404) is a genuine failure for URL
                // discovery, not an empty link set (issue #606). Surface it as
                // a tool error rather than a misleading empty `[]`.
                if !(200..=299).contains(&resp.status) {
                    self.state.record_scrape_identity(
                        "discover_urls",
                        domain_of(&params.url),
                        Outcome::Error,
                        0,
                        start,
                        &root_correlation,
                    );
                    return Ok(CallToolResult::error(vec![Content::text(format!(
                        "HTTP error: status {}",
                        resp.status
                    ))]));
                }
                let html = resp.body;
                match webfang_core::infrastructure::crawler::extract_links(&html, &params.url) {
                    Ok(links) => {
                        let count = links.len();
                        self.state.record_scrape_identity(
                            "discover_urls",
                            domain_of(&params.url),
                            Outcome::Success,
                            count,
                            start,
                            &root_correlation,
                        );
                        let content = serde_json::to_string_pretty(&links)
                            .unwrap_or_else(|_| "failed to serialize".into());
                        Ok(CallToolResult::success(vec![Content::text(content)]))
                    },
                    Err(e) => {
                        self.state.record_scrape_identity(
                            "discover_urls",
                            domain_of(&params.url),
                            Outcome::Error,
                            0,
                            start,
                            &root_correlation,
                        );
                        Ok(CallToolResult::error(vec![Content::text(e.to_string())]))
                    },
                }
            },
            Err(e) => {
                self.state.record_scrape_identity(
                    "discover_urls",
                    domain_of(&params.url),
                    Outcome::Error,
                    0,
                    start,
                    &root_correlation,
                );
                Ok(CallToolResult::error(vec![Content::text(format!(
                    "HTTP error: {e}"
                ))]))
            },
        }
    }

    /// Auto-discover sitemap URL from robots.txt or common locations
    #[tool(
        description = "Auto-discover a website's sitemap URL by checking robots.txt and common locations (/sitemap.xml, /sitemap_index.xml, etc.)."
    )]
    #[instrument(skip(self), fields(url = %params.url))]
    async fn discover_sitemap(
        &self,
        Parameters(params): Parameters<DiscoverUrlsParams>,
    ) -> Result<CallToolResult, McpError> {
        params.validate()?;

        let _permit = acquire_semaphore!(self, scraping);

        let seed = url::Url::parse(&params.url).map_err(|e| {
            McpError::invalid_params(
                format!("invalid URL: {e}"),
                Some(serde_json::Value::String("url".to_string())),
            )
        })?;
        crate::mcp_server::ssrf::validate_url_no_ssrf(&seed).await?;

        let start = Instant::now();
        // One run identity per tool call, shared by its success and error events (#501/#698).
        let root_correlation = webfang_core::domain::CorrelationId::new();
        let crawler_config = webfang_core::domain::CrawlerConfig::new(seed);

        match webfang_core::application::crawler::crawl_with_sitemap(
            &params.url,
            None,
            &crawler_config,
        )
        .await
        {
            Ok(discovered) => {
                let count = discovered.len();
                self.state.record_scrape_identity(
                    "discover_sitemap",
                    domain_of(&params.url),
                    Outcome::Success,
                    count,
                    start,
                    &root_correlation,
                );
                let urls: Vec<String> = discovered.into_iter().map(|d| d.url.to_string()).collect();
                let content = serde_json::to_string_pretty(&urls)
                    .unwrap_or_else(|_| "failed to serialize".into());
                Ok(CallToolResult::success(vec![Content::text(content)]))
            },
            Err(e) => {
                self.state.record_scrape_identity(
                    "discover_sitemap",
                    domain_of(&params.url),
                    Outcome::Error,
                    0,
                    start,
                    &root_correlation,
                );
                Ok(CallToolResult::error(vec![Content::text(e.to_string())]))
            },
        }
    }

    /// Predict if a URL requires JavaScript rendering (SPA)
    ///
    /// Runs the same cleaning + extraction chain the default scrape uses
    /// (`predict_spa_status`, #760), so the verdict anticipates whether the
    /// scrape itself will fail the minimum-content guard.
    ///
    /// Respects the site's robots.txt: a disallowed URL is rejected with a
    /// `robots.txt` error before any fetch (#749, uniform with #697).
    #[tool(
        description = "Predicts if a page requires JavaScript rendering (Single Page Application) by running the same cleaning and extraction pipeline as a scrape, so its verdict matches what the scrape would do. Reports insufficient-content diagnostics and SPA markers (e.g. <div id=\"root\">, <div id=\"app\">) when the default pipeline cannot extract enough text."
    )]
    #[instrument(skip(self), fields(url = %params.url))]
    // serde_json::to_string cannot fail for a serde_json::Value.
    #[allow(clippy::expect_used)]
    async fn detect_spa(
        &self,
        Parameters(params): Parameters<DetectSpaParams>,
    ) -> Result<CallToolResult, McpError> {
        params.validate()?;

        let _permit = acquire_semaphore!(self, scraping);

        let url = url::Url::parse(&params.url).map_err(|e| {
            McpError::invalid_params(
                format!("invalid URL: {e}"),
                Some(serde_json::Value::String("url".to_string())),
            )
        })?;
        crate::mcp_server::ssrf::validate_url_no_ssrf(&url).await?;

        let start = Instant::now();
        // One run identity per tool call, shared by its success and error events (#501/#698).
        let root_correlation = webfang_core::domain::CorrelationId::new();
        // robots.txt gate BEFORE any fetch (#749).
        if let Some(robots_error) = robots_denied_response(
            self,
            "detect_spa",
            &url,
            &params.url,
            start,
            &root_correlation,
        )
        .await
        {
            return Ok(robots_error);
        }
        let port = self.state.container.http_client();
        match port.get(url.as_str()).await {
            Ok(resp) => {
                self.state.record_scrape_identity(
                    "detect_spa",
                    domain_of(&params.url),
                    Outcome::Success,
                    1,
                    start,
                    &root_correlation,
                );
                let html = resp.body;
                // #760: run the same cleaning + extraction chain the scrape's
                // minimum-content guard consumes, so the tool's verdict
                // anticipates the scrape's (the old raw-htmd path counted
                // <noscript>/header/footer text the real pipeline discards).
                match webfang_core::application::spa_detection::predict_spa_status(
                    url.as_str(),
                    &html,
                ) {
                    Some(info) => {
                        let json = serde_json::json!({
                            "url": info.url,
                            "char_count": info.char_count,
                            "has_spa_markers": info.has_spa_markers,
                        });
                        Ok(CallToolResult::success(vec![Content::text(
                            serde_json::to_string_pretty(&json)
                                .expect("serializing JSON to a string cannot fail"),
                        )]))
                    },
                    None => Ok(CallToolResult::success(vec![Content::text(
                        "not an SPA - sufficient content found",
                    )])),
                }
            },
            Err(e) => {
                self.state.record_scrape_identity(
                    "detect_spa",
                    domain_of(&params.url),
                    Outcome::Error,
                    0,
                    start,
                    &root_correlation,
                );
                Ok(CallToolResult::error(vec![Content::text(format!(
                    "HTTP error: {e}"
                ))]))
            },
        }
    }
}

/// robots.txt gate for single-URL direct-fetch tools (#749).
///
/// Delegates to the single policy source
/// (`McpState::robots_denied_for` → `scraper_service::enforce_robots_policy`,
/// fail-open when no fetcher is wired). On denial, records an
/// `Outcome::Error` scrape identity for `tool` — the same shape as each
/// handler's HTTP-error branch — and returns the tool error envelope carrying
/// the denial text (`WafBlocked(url, "robots.txt")`).
async fn robots_denied_response(
    handler: &McpHandler,
    tool: &'static str,
    url: &url::Url,
    raw_url: &str,
    start: Instant,
    correlation: &webfang_core::domain::CorrelationId,
) -> Option<CallToolResult> {
    let err = handler.state.robots_denied_for(url).await?;
    handler.state.record_scrape_identity(
        tool,
        domain_of(raw_url),
        Outcome::Error,
        0,
        start,
        correlation,
    );
    Some(CallToolResult::error(vec![Content::text(err.to_string())]))
}

/// Keep only seed-host-internal URLs in the discovery output (REQ-01, SSRF
/// defense-in-depth).
///
/// The engine's internal-link gating already applies on the BFS crawl path,
/// but sitemap discovery returns every `<loc>` host-agnostic. This post-hoc
/// filter is the authoritative gate that ensures no external-domain or
/// forbidden-literal-IP URL ever reaches an MCP response, complementing the
/// entry-level SSRF validator. Each exclusion emits a structured `warn` with
/// the `url` field (REQ-01/REQ-07).
///
/// Returns the number of excluded URLs. `total_pages` / crawl counts are NOT
/// recomputed — they keep engine semantics (pages crawled, not links emitted).
fn filter_ssrf_safe(
    urls: &[webfang_core::domain::DiscoveredUrl],
    seed: &url::Url,
    out: &mut Vec<String>,
) -> usize {
    let seed_host = seed.host_str().unwrap_or(""); // mirrors crawl_task.rs internal-link anchor
    let mut excluded = 0usize;
    for d in urls {
        let internal =
            webfang_core::domain::url_validation::is_internal_link(d.url.as_str(), seed_host);
        if internal {
            // Hostnames compared here are non-literal hosts; literal IPs on a
            // non-seed host fall through to the exclusion branch below.
            out.push(d.url.to_string());
            continue;
        }
        excluded += 1;
        let reason = if webfang_core::infrastructure::ssrf::is_forbidden_literal_host(
            d.url.host_str().unwrap_or(""),
        ) {
            "forbidden_literal_ip"
        } else {
            "external_domain"
        };
        tracing::warn!(
            url = %d.url,
            reason = %reason,
            "discovered URL excluded from MCP response (SSRF defense-in-depth)"
        );
    }
    excluded
}

/// Build the scraping core router (8 tools for URL scraping and crawling).
///
/// Returns a partial router that is combined with the other category routers
/// via the `+` operator in
/// [`build_tool_router`](crate::mcp_server::handlers::build_tool_router).
pub fn build_router() -> ToolRouter<McpHandler> {
    McpHandler::tool_router_scraping()
}

/// Record per-domain scrape metrics for a completed batch (#696).
///
/// Groups successes and failures by their REAL host so multi-domain batches
/// attribute pages correctly in the metrics snapshot. Every event shares the
/// run-root `correlation` (#501/#698): one operation identity, one event per
/// domain group. `BTreeMap` keeps emission order deterministic (DD-6).
fn record_batch_metrics_by_domain(
    state: &crate::mcp_server::McpState,
    outcome: &webfang_core::application::scraper_service::ScrapeBatchOutcome,
    start: Instant,
    correlation: &webfang_core::domain::CorrelationId,
) {
    // (successes, failures) per host.
    let mut groups: std::collections::BTreeMap<String, (usize, usize)> =
        std::collections::BTreeMap::new();
    for result in &outcome.results {
        let host = result
            .url
            .host_str()
            .map(str::to_string)
            .unwrap_or_else(|| "unknown".to_string());
        groups.entry(host).or_default().0 += 1;
    }
    for failed in &outcome.failed {
        let host = url::Url::parse(&failed.url)
            .ok()
            .and_then(|u| u.host_str().map(str::to_string))
            .unwrap_or_else(|| "unknown".to_string());
        groups.entry(host).or_default().1 += 1;
    }
    for (host, (ok, failed)) in groups {
        let outcome_type = if failed == 0 {
            Outcome::Success
        } else if ok == 0 {
            Outcome::Error
        } else {
            Outcome::Partial
        };
        state.record_scrape_identity(
            "scrape_batch",
            host,
            outcome_type,
            ok + failed,
            start,
            correlation,
        );
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::mcp_server::state::McpState;
    use rmcp::handler::server::wrapper::Parameters;
    use rmcp::model::CallToolResult;
    use serial_test::serial;
    use tempfile::TempDir;
    use webfang_core::di::Container;
    use webfang_core::domain::CrawlerConfig;
    use webfang_core::infrastructure::config::ScraperConfig;
    use webfang_core::infrastructure::crawler::robots_utils::RobotsFetcher;
    use wiremock::matchers::{method, path};
    use wiremock::{Mock, MockServer, ResponseTemplate};

    async fn test_handler() -> (McpHandler, TempDir) {
        let (mut state, tmp) = test_state().await;
        // Determinism (#705): handler tests must stay offline — the robots
        // check performs a real robots.txt fetch, so unit tests drop the
        // fetcher instead of risking network access through loopback URLs.
        state.robots_fetcher = None;
        (McpHandler::new(state), tmp)
    }

    /// Build a state with a real robots fetcher for #749 enforcement tests.
    /// Offline-friendly: construction never touches the network.
    async fn test_handler_with_robots() -> (McpHandler, TempDir) {
        let (state, tmp) = test_state().await;
        let state = state.with_robots_fetcher(std::sync::Arc::new(
            RobotsFetcher::with_default_profile(5).expect("fetcher construction is offline"),
        ));
        (McpHandler::new(state), tmp)
    }

    /// Shared state construction for `test_handler` / `test_handler_with_robots`.
    /// The `TempDir` is returned so the caller keeps the configured
    /// `output_dir` alive.
    async fn test_state() -> (McpState, TempDir) {
        let tmp = TempDir::new().expect("create temp dir");
        let crawler_config =
            CrawlerConfig::new(url::Url::parse("https://example.com").expect("valid url"));
        let scraper_config = ScraperConfig {
            output_dir: tmp.path().to_path_buf(),
            ..Default::default()
        };
        let container = Container::new(crawler_config, scraper_config)
            .await
            .expect("create container");
        (McpState::new(container), tmp)
    }

    // ── #749 robots.txt gate fixtures (modeled on
    // `crates/webfang_core/tests/scraper_service_test.rs::robots`) ──

    /// Minimal article HTML that Readability extracts deterministically
    /// (scraping_coverage_test.rs style).
    const ARTICLE_HTML: &str = r#"<!DOCTYPE html>
<html>
<head><title>Public Page</title></head>
<body>
<article>
<h1>Main Heading</h1>
<p>This is the content of the article. It has enough text to be extracted by Readability.</p>
</article>
</body>
</html>"#;

    /// Mount a robots.txt disallowing `/private/*` and a 200 page at
    /// `/{path}` on the same origin — the fetcher keys its rule cache on the
    /// page URL's origin, so both routes must sit on one `MockServer`.
    async fn mount_robots_site(server: &MockServer, page_path: &str) {
        Mock::given(method("GET"))
            .and(path("/robots.txt"))
            .respond_with(
                ResponseTemplate::new(200).set_body_string("User-agent: *\nDisallow: /private\n"),
            )
            .mount(server)
            .await;
        Mock::given(method("GET"))
            .and(path(format!("/{page_path}")))
            .respond_with(ResponseTemplate::new(200).set_body_string(ARTICLE_HTML))
            .mount(server)
            .await;
    }

    /// Count requests that are NOT the robots.txt probe — zero proves the
    /// gate short-circuited BEFORE any page fetch.
    async fn page_hits(server: &MockServer) -> usize {
        server
            .received_requests()
            .await
            .expect("request recording is enabled")
            .iter()
            .filter(|r| r.url.path() != "/robots.txt")
            .count()
    }

    /// The first text content of a tool result, serialized as the transport
    /// would.
    fn result_text(result: &CallToolResult) -> String {
        serde_json::to_value(result)
            .ok()
            .and_then(|v| v.get("content").and_then(|c| c.as_array()).cloned())
            .and_then(|arr| arr.first().cloned())
            .and_then(|first| {
                first
                    .get("text")
                    .and_then(|t| t.as_str())
                    .map(str::to_owned)
            })
            .unwrap_or_default()
    }

    /// Assert that a tool result is an honest error (`isError:true`) whose
    /// text reports the robots.txt denial.
    fn assert_robots_error(result: &CallToolResult) -> String {
        let json = serde_json::to_value(result).expect("CallToolResult serializes");
        assert_eq!(
            json.get("isError").and_then(|v| v.as_bool()),
            Some(true),
            "robots denial must set isError:true, got: {json}"
        );
        let text = result_text(result);
        assert!(
            text.contains("robots.txt"),
            "error text must report the robots.txt denial, got: {text}"
        );
        text
    }

    /// Assert that a handler rejected a loopback/private URL via the SSRF gate.
    fn assert_ssrf_rejected(res: Result<CallToolResult, McpError>) {
        let err = res.expect_err("loopback/internal URL must be blocked by SSRF");
        let msg = err.to_string();
        assert!(
            msg.contains("SSRF"),
            "error must report SSRF protection, got: {msg}"
        );
    }

    /// WEBFANG_MCP_DISABLE_SSRF is a process-global variable. The Coverage job
    /// runs raw `cargo test` (single process, parallel threads — nextest
    /// isolates per process, which hides the race), so every test that reads
    /// or mutates the escape hatch is `#[serial]` to keep the guard's state
    /// consistent (pattern: metrics.rs).
    #[tokio::test]
    #[serial]
    async fn scrape_url_rejects_loopback() {
        // Defensive under shared-process harnesses: the escape hatch must be
        // unset for this process so the guard is active. (nextest isolates
        // each test in its own process, so this is a no-op there.)
        std::env::remove_var("WEBFANG_MCP_DISABLE_SSRF");
        // SSRF protection must block requests to internal/loopback addresses
        // before any fetch happens (Bug #673).
        let (handler, _tmp) = test_handler().await;
        let res = handler
            .scrape_url(Parameters(ScrapeUrlParams {
                url: "http://127.0.0.1/".to_string(),
            }))
            .await;
        assert_ssrf_rejected(res);
    }

    #[tokio::test]
    async fn scrape_url_invalid_url_is_invalid_params() {
        let (handler, _tmp) = test_handler().await;
        let res = handler
            .scrape_url(Parameters(ScrapeUrlParams {
                url: "not a url".to_string(),
            }))
            .await;
        assert!(res.is_err(), "invalid URL must be a protocol error");
    }

    #[tokio::test]
    #[serial]
    async fn scrape_with_options_rejects_loopback() {
        // Defensive under shared-process harnesses: the escape hatch must be
        // unset for this process so the guard is active. (nextest isolates
        // each test in its own process, so this is a no-op there.)
        std::env::remove_var("WEBFANG_MCP_DISABLE_SSRF");
        // SSRF protection must block internal/loopback addresses (Bug #673).
        let (handler, _tmp) = test_handler().await;
        let res = handler
            .scrape_with_options(Parameters(ScrapeWithOptionsParams {
                url: "http://127.0.0.1/".to_string(),
                max_pages: Some(1),
                download_images: Some(false),
                download_documents: Some(false),
                selector: None,
                ignore_robots: None,
            }))
            .await;
        assert_ssrf_rejected(res);
    }

    #[tokio::test]
    async fn scrape_with_options_invalid_url_is_invalid_params() {
        let (handler, _tmp) = test_handler().await;
        let res = handler
            .scrape_with_options(Parameters(ScrapeWithOptionsParams {
                url: "::bad::".to_string(),
                max_pages: None,
                download_images: None,
                download_documents: None,
                selector: None,
                ignore_robots: None,
            }))
            .await;
        assert!(res.is_err(), "invalid URL must be a protocol error");
    }

    #[tokio::test]
    #[serial]
    async fn scrape_batch_rejects_loopback() {
        // Defensive under shared-process harnesses: the escape hatch must be
        // unset for this process so the guard is active. (nextest isolates
        // each test in its own process, so this is a no-op there.)
        std::env::remove_var("WEBFANG_MCP_DISABLE_SSRF");
        // SSRF protection must block internal/loopback addresses in a batch (Bug #673).
        let (handler, _tmp) = test_handler().await;
        let res = handler
            .scrape_batch(Parameters(ScrapeBatchParams {
                urls: vec!["http://127.0.0.1/".to_string()],
                concurrency: Some(2),
                ignore_robots: None,
            }))
            .await;
        assert_ssrf_rejected(res);
    }

    #[tokio::test]
    async fn scrape_batch_no_valid_urls_is_error() {
        let (handler, _tmp) = test_handler().await;
        // Params validation (#512) rejects unparseable URLs up front.
        let res = handler
            .scrape_batch(Parameters(ScrapeBatchParams {
                urls: vec!["not a url".to_string()],
                concurrency: None,
                ignore_robots: None,
            }))
            .await;
        assert!(
            res.is_err(),
            "invalid URLs must be a protocol error, got: {res:?}"
        );
    }

    #[test]
    fn zero_limits_are_rejected() {
        // Bug #597: concurrency:0 deadlocks buffer_unordered(0).
        // Bug #598: max_pages:0 panics mpsc::channel(0).
        // Both must be rejected up front with invalid_params.
        let batch = ScrapeBatchParams {
            urls: vec!["https://example.com".to_string()],
            concurrency: Some(0),
            ignore_robots: None,
        }
        .validate();
        assert!(batch.is_err(), "concurrency 0 must be rejected: {batch:?}");

        let crawl = CrawlSiteParams {
            url: "https://example.com".into(),
            max_depth: None,
            max_pages: Some(0),
        }
        .validate();
        assert!(crawl.is_err(), "max_pages 0 must be rejected: {crawl:?}");
    }

    #[tokio::test]
    #[serial]
    async fn discover_urls_rejects_loopback() {
        // Defensive under shared-process harnesses: the escape hatch must be
        // unset for this process so the guard is active. (nextest isolates
        // each test in its own process, so this is a no-op there.)
        std::env::remove_var("WEBFANG_MCP_DISABLE_SSRF");
        // SSRF protection must block internal/loopback addresses (Bug #673).
        let (handler, _tmp) = test_handler().await;
        let res = handler
            .discover_urls(Parameters(DiscoverUrlsParams {
                url: "http://127.0.0.1/".to_string(),
            }))
            .await;
        assert_ssrf_rejected(res);
    }

    #[tokio::test]
    async fn discover_urls_invalid_url_is_invalid_params() {
        let (handler, _tmp) = test_handler().await;
        // Params validation (#512) rejects unparseable URLs up front.
        let res = handler
            .discover_urls(Parameters(DiscoverUrlsParams {
                url: "not a url".to_string(),
            }))
            .await;
        assert!(
            res.is_err(),
            "invalid URL must be a protocol error, got: {res:?}"
        );
    }

    #[tokio::test]
    #[serial]
    async fn detect_spa_rejects_loopback() {
        // Defensive under shared-process harnesses: the escape hatch must be
        // unset for this process so the guard is active. (nextest isolates
        // each test in its own process, so this is a no-op there.)
        std::env::remove_var("WEBFANG_MCP_DISABLE_SSRF");
        // SSRF protection must block internal/loopback addresses (Bug #673).
        let (handler, _tmp) = test_handler().await;
        let res = handler
            .detect_spa(Parameters(DetectSpaParams {
                url: "http://127.0.0.1/".to_string(),
            }))
            .await;
        assert_ssrf_rejected(res);
    }

    #[tokio::test]
    async fn detect_spa_invalid_url_is_invalid_params() {
        let (handler, _tmp) = test_handler().await;
        // Params validation (#512) rejects unparseable URLs up front.
        let res = handler
            .detect_spa(Parameters(DetectSpaParams {
                url: "not a url".to_string(),
            }))
            .await;
        assert!(
            res.is_err(),
            "invalid URL must be a protocol error, got: {res:?}"
        );
    }

    // ── #749: robots.txt must be respected before any page fetch ──

    /// `scrape_url` with a robots-disallowed URL returns an `isError:true`
    /// result reporting `robots.txt` and never issues the page fetch.
    #[cfg_attr(miri, ignore)] // real network stack via wreq — unsupported by Miri
    #[tokio::test]
    #[serial]
    async fn scrape_url_robots_disallowed_returns_error_and_zero_page_hits() {
        std::env::set_var("WEBFANG_MCP_DISABLE_SSRF", "1"); // wiremock binds 127.0.0.1
        let (handler, _tmp) = test_handler_with_robots().await;
        let server = MockServer::start().await;
        mount_robots_site(&server, "private/page").await;

        let res = handler
            .scrape_url(Parameters(ScrapeUrlParams {
                url: format!("{}/private/page", server.uri()),
            }))
            .await
            .expect("handler returns Ok with an honest error");

        assert_robots_error(&res);
        assert_eq!(
            page_hits(&server).await,
            0,
            "the robots gate must short-circuit before the page fetch"
        );
    }

    /// Positive path: a robots-allowed URL passes the gate through to a real
    /// scrape (fail-open positive: allowed = no interference), and the
    /// extracted content reaches the caller.
    #[cfg_attr(miri, ignore)] // real network stack via wreq — unsupported by Miri
    #[tokio::test]
    #[serial]
    async fn scrape_url_robots_allowed_still_scrapes_page() {
        std::env::set_var("WEBFANG_MCP_DISABLE_SSRF", "1"); // wiremock binds 127.0.0.1
        let (handler, _tmp) = test_handler_with_robots().await;
        let server = MockServer::start().await;
        mount_robots_site(&server, "public/page").await;

        let res = handler
            .scrape_url(Parameters(ScrapeUrlParams {
                url: format!("{}/public/page", server.uri()),
            }))
            .await
            .expect("handler returns Ok");

        let json = serde_json::to_value(&res).expect("CallToolResult serializes");
        assert_ne!(
            json.get("isError").and_then(|v| v.as_bool()),
            Some(true),
            "robots-allowed URL must not be rejected: {}",
            result_text(&res)
        );
        assert_eq!(page_hits(&server).await, 1, "the page must be fetched");
        assert!(
            result_text(&res).contains("Public Page"),
            "allowed scrape must return the extracted article title, got: {}",
            result_text(&res)
        );
    }

    /// `discover_urls` with a robots-disallowed URL returns a `robots.txt`
    /// error and never issues the page fetch.
    #[cfg_attr(miri, ignore)] // real network stack via wreq — unsupported by Miri
    #[tokio::test]
    #[serial]
    async fn discover_urls_robots_disallowed_returns_error_and_zero_page_hits() {
        std::env::set_var("WEBFANG_MCP_DISABLE_SSRF", "1"); // wiremock binds 127.0.0.1
        let (handler, _tmp) = test_handler_with_robots().await;
        let server = MockServer::start().await;
        mount_robots_site(&server, "private/list").await;

        let res = handler
            .discover_urls(Parameters(DiscoverUrlsParams {
                url: format!("{}/private/list", server.uri()),
            }))
            .await
            .expect("handler returns Ok with an honest error");

        assert_robots_error(&res);
        assert_eq!(
            page_hits(&server).await,
            0,
            "the robots gate must short-circuit before the page fetch"
        );
    }

    /// `detect_spa` with a robots-disallowed URL returns a `robots.txt` error
    /// and never issues the page fetch.
    #[cfg_attr(miri, ignore)] // real network stack via wreq — unsupported by Miri
    #[tokio::test]
    #[serial]
    async fn detect_spa_robots_disallowed_returns_error_and_zero_page_hits() {
        std::env::set_var("WEBFANG_MCP_DISABLE_SSRF", "1"); // wiremock binds 127.0.0.1
        let (handler, _tmp) = test_handler_with_robots().await;
        let server = MockServer::start().await;
        mount_robots_site(&server, "private/app").await;

        let res = handler
            .detect_spa(Parameters(DetectSpaParams {
                url: format!("{}/private/app", server.uri()),
            }))
            .await
            .expect("handler returns Ok with an honest error");

        assert_robots_error(&res);
        assert_eq!(
            page_hits(&server).await,
            0,
            "the robots gate must short-circuit before the page fetch"
        );
    }

    #[tokio::test]
    async fn crawl_site_invalid_url_is_invalid_params() {
        let (handler, _tmp) = test_handler().await;
        let res = handler
            .crawl_site(Parameters(CrawlSiteParams {
                url: "not a url".to_string(),
                max_depth: None,
                max_pages: None,
            }))
            .await;
        assert!(res.is_err(), "invalid URL must be a protocol error");
    }

    #[tokio::test]
    async fn crawl_with_sitemap_invalid_url_is_invalid_params() {
        let (handler, _tmp) = test_handler().await;
        let res = handler
            .crawl_with_sitemap(Parameters(CrawlWithSitemapParams {
                url: "not a url".to_string(),
                sitemap_url: None,
            }))
            .await;
        assert!(res.is_err(), "invalid URL must be a protocol error");
    }

    /// REQ-01: the post-hoc filter keeps seed-host-internal URLs and drops
    /// external-domain and forbidden-literal-IP URLs, reporting the exclusion
    /// count. Empty input produces empty output with zero exclusions.
    #[test]
    fn filter_ssrf_safe_keeps_internal_drops_external_literal() {
        let seed = url::Url::parse("https://example.com/").expect("valid seed");
        let discovered = vec![
            webfang_core::domain::DiscoveredUrl::html(
                url::Url::parse("https://example.com/a").expect("valid url"),
                1,
                seed.clone(),
            ),
            webfang_core::domain::DiscoveredUrl::html(
                url::Url::parse("https://other.com/x").expect("valid url"),
                1,
                seed.clone(),
            ),
            webfang_core::domain::DiscoveredUrl::html(
                url::Url::parse("http://10.0.0.5/x").expect("valid url"),
                1,
                seed.clone(),
            ),
        ];

        let mut out = Vec::new();
        let excluded = filter_ssrf_safe(&discovered, &seed, &mut out);
        assert_eq!(
            out,
            vec!["https://example.com/a".to_string()],
            "only the seed-host URL survives"
        );
        assert_eq!(excluded, 2, "external + forbidden literal are excluded");

        let mut empty_out = Vec::new();
        assert_eq!(
            filter_ssrf_safe(&[], &seed, &mut empty_out),
            0,
            "empty input excludes nothing"
        );
        assert!(
            empty_out.is_empty(),
            "empty input keeps the output empty (established as the filtered case above returns entries)"
        );
    }

    /// REQ-02: an internal `sitemap_url` is rejected at entry (guard ON) with
    /// the SSRF message, before any sitemap fetch. The seed uses a public
    /// literal IP so its own validation resolves locally (no DNS dependency).
    #[tokio::test]
    #[serial]
    async fn crawl_with_sitemap_rejects_internal_sitemap_url() {
        // Defensive under shared-process harnesses: the escape hatch must be
        // unset for this process so the guard is active. (nextest isolates
        // each test in its own process, so this is a no-op there.)
        std::env::remove_var("WEBFANG_MCP_DISABLE_SSRF");

        let (handler, _tmp) = test_handler().await;
        let res = handler
            .crawl_with_sitemap(Parameters(CrawlWithSitemapParams {
                url: "http://8.8.8.8/".to_string(),
                sitemap_url: Some("http://127.0.0.1/".to_string()),
            }))
            .await;
        assert_ssrf_rejected(res);
    }

    #[tokio::test]
    async fn discover_sitemap_invalid_url_is_invalid_params() {
        let (handler, _tmp) = test_handler().await;
        let res = handler
            .discover_sitemap(Parameters(DiscoverUrlsParams {
                url: "not a url".to_string(),
            }))
            .await;
        assert!(res.is_err(), "invalid URL must be a protocol error");
    }
    // --- record_batch_metrics_by_domain (#696) ---

    /// Build a minimal successful `ScrapedContent` for a given URL.
    fn scraped(url: &str) -> webfang_core::domain::entities::content::ScrapedContent {
        webfang_core::domain::entities::content::ScrapedContent {
            title: "t".into(),
            content: "c".into(),
            url: webfang_core::domain::ValidUrl::new(url::Url::parse(url).expect("valid url")),
            excerpt: None,
            author: None,
            date: None,
            html: None,
            assets: vec![],
            correlation_id: None,
        }
    }

    /// Build a minimal `ScrapeFailed` for a given URL.
    fn failed(url: &str) -> webfang_core::application::scraper_service::ScrapeFailed {
        webfang_core::application::scraper_service::ScrapeFailed {
            url: url.to_string(),
            error: "boom".into(),
            category:
                webfang_core::application::scraper_service::ScrapeErrorCategory::PermanentFatal,
        }
    }

    /// Record a batch outcome against the handler's metrics (#696 tests).
    fn record(
        handler: &McpHandler,
        outcome: webfang_core::application::scraper_service::ScrapeBatchOutcome,
    ) {
        record_batch_metrics_by_domain(
            &handler.state,
            &outcome,
            Instant::now(),
            &webfang_core::domain::CorrelationId::new(),
        );
    }

    #[tokio::test]
    async fn batch_metrics_multi_domain_attributed_per_host() {
        // OBS-MCP-BATCH-001: a batch spanning two hosts must record one
        // event per REAL host, not everything under `urls.first()`.
        let (handler, _tmp) = test_handler().await;
        let outcome = webfang_core::application::scraper_service::ScrapeBatchOutcome {
            results: vec![
                scraped("https://example.com/a"),
                scraped("https://books.toscrape.com/b"),
            ],
            failed: vec![],
        };
        record(&handler, outcome);

        let snap = handler.state.metrics_snapshot();
        assert_eq!(snap.total_events, 2, "one event per domain");
        assert_eq!(snap.domains.len(), 2, "two distinct domains recorded");
        assert_eq!(snap.domains["example.com"].pages, 1, "example.com pages");
        assert_eq!(
            snap.domains["books.toscrape.com"].pages, 1,
            "books.toscrape.com pages"
        );
    }

    #[tokio::test]
    async fn batch_metrics_single_domain_regression_guard() {
        let (handler, _tmp) = test_handler().await;
        let outcome = webfang_core::application::scraper_service::ScrapeBatchOutcome {
            results: vec![
                scraped("https://example.com/a"),
                scraped("https://example.com/b"),
            ],
            failed: vec![],
        };
        record(&handler, outcome);

        let snap = handler.state.metrics_snapshot();
        assert_eq!(snap.total_events, 1, "single domain = single event");
        assert_eq!(snap.domains["example.com"].pages, 2, "both pages counted");
        assert_eq!(snap.success_count, 1, "all-success batch is Success");
    }

    #[tokio::test]
    async fn batch_metrics_mixed_outcomes_per_domain() {
        // A domain with both a success and a failure is Partial; a domain
        // with only failures is Error.
        let (handler, _tmp) = test_handler().await;
        let outcome = webfang_core::application::scraper_service::ScrapeBatchOutcome {
            results: vec![scraped("https://example.com/ok")],
            failed: vec![
                failed("https://example.com/bad"),
                failed("https://broken.test/x"),
            ],
        };
        record(&handler, outcome);

        let snap = handler.state.metrics_snapshot();
        assert_eq!(snap.domains.len(), 2);
        assert_eq!(snap.partial_count, 1, "mixed domain is Partial");
        assert_eq!(snap.error_count, 1, "all-failed domain is Error");
        assert_eq!(snap.domains["example.com"].pages, 2, "ok + bad counted");
        assert_eq!(snap.domains["broken.test"].pages, 1);
    }
}
