//! Security & Diagnostics tools — 4 tools for WAF detection and metrics
//!
//! Tools: detect_waf, verify_waf_integrity, list_waf_providers,
//! get_scrape_metrics

use super::McpHandler;
use crate::mcp_server::metrics::MetricsSnapshot;
use crate::mcp_server::params::*;
use rmcp::handler::server::tool::ToolRouter;
use rmcp::handler::server::wrapper::Parameters;
use rmcp::tool;
use rmcp::tool_router;
use rmcp::{model::CallToolResult, model::Content, ErrorData as McpError};
use tracing::instrument;
use webfang_core::infrastructure::http::waf_engine::{InspectionContext, WafInspector, WafVerdict};

#[tool_router(router = tool_router_security, vis = "pub")]
// Allow: the `tool_router_security` fn generated by rmcp-macros cannot be documented from this crate.
#[allow(missing_docs)]
impl McpHandler {
    /// Detect WAF/CAPTCHA challenge in HTML body
    #[tool(
        description = "Scan HTML body for WAF/CAPTCHA signatures (Cloudflare, reCAPTCHA, hCaptcha, DataDome, PerimeterX, Akamai, etc.). Runs in degraded mode (no HTTP context): reports only unambiguous challenge markers — vendor fingerprints need status via verify_waf_integrity. Returns provider name if detected."
    )]
    #[instrument(skip(self), fields(html_len = params.html.len()))]
    async fn detect_waf(
        &self,
        Parameters(params): Parameters<DetectWafParams>,
    ) -> Result<CallToolResult, McpError> {
        params.validate()?;

        let _permit = acquire_semaphore!(self, security);

        match detect_waf_provider(&params.html) {
            Some(provider) => Ok(CallToolResult::success(vec![Content::text(format!(
                "WAF detected: {provider}"
            ))])),
            None => Ok(CallToolResult::success(vec![Content::text(
                "no WAF detected",
            )])),
        }
    }

    /// Multi-layer WAF inspection (headers + body + entropy analysis)
    #[tool(
        description = "Multi-layer WAF inspection: checks control headers, body signatures via Aho-Corasick, and entropy analysis for silent challenges. Optionally pass status and content_type for context-aware detection (fingerprint evidence then blocks only on correlated WAF statuses 403/429/503/520-529); without them, runs degraded mode where only unambiguous challenge markers block and fingerprint/control-header evidence never blocks on mere presence. The status/content_type params are additive (tool signature backward compatible); control-header verdict semantics intentionally changed per issue #346 — mere-presence blocking was the bug."
    )]
    #[instrument(skip(self), fields(params = ?params))]
    async fn verify_waf_integrity(
        &self,
        Parameters(params): Parameters<VerifyWafIntegrityParams>,
    ) -> Result<CallToolResult, McpError> {
        params.validate()?;

        let _permit = acquire_semaphore!(self, security);

        let html = params.html.as_deref().unwrap_or("");
        let mut header_map = wreq::header::HeaderMap::new();
        if let Some(ref hdrs) = params.headers {
            for (key, value) in hdrs {
                if let (Ok(name), Ok(val)) = (
                    wreq::header::HeaderName::from_bytes(key.as_bytes()),
                    wreq::header::HeaderValue::from_str(value),
                ) {
                    header_map.insert(name, val);
                }
            }
        }
        // Additive optional context (REQ-WAF-09): the status/content_type params
        // are backward compatible (tool signature unchanged). The verdict is NOT
        // unchanged, though — without them this is degraded mode, where control
        // header (Fingerprint) evidence never blocks on mere presence. That is the
        // intentional #346 / REQ-WAF-05 fix (mere-presence blocking was the bug),
        // so degraded verdicts deliberately differ from the pre-#346 verify_integrity.
        let verdict = verify_waf_verdict(html, params.status, params.content_type, header_map);
        if verdict.is_blocked {
            Ok(CallToolResult::success(vec![Content::text(format!(
                "WAF blocked: {}",
                verdict.evidence_chain()
            ))]))
        } else {
            Ok(CallToolResult::success(vec![Content::text(
                "WAF integrity check passed",
            )]))
        }
    }

    /// List all supported WAF providers
    #[tool(
        description = "List all WAF/CAPTCHA providers that can be detected by the WAF inspector."
    )]
    #[instrument(skip(self))]
    async fn list_waf_providers(&self) -> Result<CallToolResult, McpError> {
        let _permit = acquire_semaphore!(self, security);

        let providers =
            webfang_core::infrastructure::http::waf_engine::WafInspector::supported_providers();
        Ok(CallToolResult::success(vec![Content::text(
            providers.join(", "),
        )]))
    }

    /// Get scrape metrics (request timing, status codes, pages scraped)
    #[tool(
        description = "Get scraping metrics including request timing, status code distribution, and pages scraped per domain."
    )]
    #[instrument(skip(self))]
    async fn get_scrape_metrics(&self) -> Result<CallToolResult, McpError> {
        let _permit = acquire_semaphore!(self, security);

        Ok(render_metrics(&self.state.metrics_snapshot()))
    }
}

/// Build the security & diagnostics router (WAF detection and metrics tools).
///
/// Returns a partial router that is combined with the other category routers
/// via the `+` operator in
/// [`build_tool_router`](crate::mcp_server::handlers::build_tool_router).
pub fn build_router() -> ToolRouter<McpHandler> {
    McpHandler::tool_router_security()
}

/// Inspect a body in degraded mode for the MCP `detect_waf` tool (REQ-WAF-09).
///
/// Returns the first evidence's provider when the degraded verdict blocks.
/// Without HTTP context only [`WafTier::Challenge`](WafInspector) markers block;
/// fingerprint evidence is collected but never blocks here — this is the
/// false-positive fix (#346).
fn detect_waf_provider(html: &str) -> Option<&'static str> {
    let verdict = WafInspector::inspect(html, &InspectionContext::default());
    if verdict.is_blocked {
        verdict.evidences.first().map(|e| e.provider)
    } else {
        None
    }
}

/// Run the `verify_waf_integrity` inspection (REQ-WAF-09).
///
/// `status` and `content_type` are additive optional context, so the API shape
/// (tool signature) is backward compatible. The verdict semantics are NOT
/// unchanged, though: when both are absent the inspection runs degraded mode,
/// where only Challenge-tier (T1) markers block and control-header / fingerprint
/// evidence never blocks on mere presence. That is the intentional fix for
/// issue #346 / REQ-WAF-05 — mere-presence blocking of control headers was the
/// bug — so degraded-mode verdicts deliberately differ from the pre-#346
/// `verify_integrity`.
fn verify_waf_verdict(
    html: &str,
    status: Option<u16>,
    content_type: Option<String>,
    headers: wreq::header::HeaderMap,
) -> WafVerdict {
    let ctx = InspectionContext {
        status,
        content_type,
        headers,
        ignore_waf: false,
    };
    WafInspector::inspect(html, &ctx)
}

/// Render a metrics snapshot as the `get_scrape_metrics` tool result.
///
/// Empty accumulator (`total_events == 0`, DD-12) → honest Spanish
/// pre-condition error (`isError:true`, REQ-05). Populated → the snapshot as
/// pretty JSON via `CallToolResult::success` (REQ-04). A serialization failure
/// maps to an honest Spanish error, never a panic (REQ-10). Mirrors the
/// `load_results_from` honest-error pattern in `export.rs`.
fn render_metrics(snapshot: &MetricsSnapshot) -> CallToolResult {
    if snapshot.total_events == 0 {
        return CallToolResult::error(vec![Content::text(
            "no hay métricas disponibles: todavía no se registró ninguna operación de scraping",
        )]);
    }
    match serde_json::to_string_pretty(snapshot) {
        Ok(json) => CallToolResult::success(vec![Content::text(json)]),
        Err(e) => CallToolResult::error(vec![Content::text(format!(
            "no se pudieron serializar las métricas: {e}"
        ))]),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use webfang_core::infrastructure::http::waf_engine::WafTier;

    // ========================================================================
    // TASK-12 — detect_waf degraded mode (REQ-WAF-09)
    // ========================================================================

    #[test]
    fn detect_waf_provider_challenge_t1_is_detected() {
        // Degraded mode: a Challenge-tier (T1) marker blocks even without context.
        let html = r#"<div id="cf-turnstile" data-sitekey="abc"></div>"#;
        assert_eq!(detect_waf_provider(html), Some("Cloudflare Turnstile"));
    }

    #[test]
    fn detect_waf_provider_fingerprint_t2_never_blocks_degraded() {
        // Degraded mode: a bare vendor name (T2) is evidence only and never
        // blocks without a correlated WAF status — the false-positive fix.
        let html = r#"<html><body>powered by cloudflare</body></html>"#;
        assert_eq!(detect_waf_provider(html), None);
    }

    #[test]
    fn detect_waf_provider_clean_body_is_none() {
        assert_eq!(
            detect_waf_provider("<html><body>normal</body></html>"),
            None
        );
    }

    #[test]
    fn detect_waf_provider_hcaptcha_response_is_detected() {
        // Issue #606: the hCaptcha response marker must be detected as a
        // Challenge-tier provider (degraded mode blocks on it).
        let html = r#"<input type="hidden" name="h-captcha-response" value="abc">"#;
        assert_eq!(detect_waf_provider(html), Some("hCaptcha"));
    }

    // ========================================================================
    // verify_waf_integrity — status range validation (issue #606)
    // ========================================================================

    #[test]
    fn verify_waf_status_zero_is_rejected() {
        let params = VerifyWafIntegrityParams {
            html: Some("<html>clean</html>".to_string()),
            headers: None,
            status: Some(0),
            content_type: None,
        };
        assert!(
            params.validate().is_err(),
            "status 0 must be rejected (not a valid HTTP status)"
        );
    }

    #[test]
    fn verify_waf_status_out_of_range_is_rejected() {
        let params = VerifyWafIntegrityParams {
            html: Some("<html>clean</html>".to_string()),
            headers: None,
            status: Some(600),
            content_type: None,
        };
        assert!(
            params.validate().is_err(),
            "status 600 must be rejected (out of valid range)"
        );
    }

    #[test]
    fn verify_waf_status_valid_range_is_accepted() {
        for s in [100u16, 200, 403, 599] {
            let params = VerifyWafIntegrityParams {
                html: Some("<html>clean</html>".to_string()),
                headers: None,
                status: Some(s),
                content_type: None,
            };
            assert!(
                params.validate().is_ok(),
                "status {s} must be accepted within [100,599]"
            );
        }
    }

    // ========================================================================
    // TASK-12 — verify_waf_integrity additive context (REQ-WAF-09)
    // ========================================================================

    #[test]
    fn verify_waf_degraded_mode_does_not_block_on_control_headers_without_status() {
        // REL-01: the name states exactly what is pinned. No status / content-type
        // → degraded mode, where a T2 control header alone never blocks on mere
        // presence. This is the intentional #346 / REQ-WAF-05 verdict change (the
        // pre-#346 verify_integrity DID block on mere presence — that was the bug);
        // only the additive optional params are backward compatible, not verdicts.
        let mut headers = wreq::header::HeaderMap::new();
        headers.insert("x-datadome-response", "1".parse().unwrap());
        let verdict = verify_waf_verdict("<html>clean</html>", None, None, headers);
        assert!(
            !verdict.is_blocked,
            "T2 header alone must not block (degraded)"
        );
        assert!(!verdict.evidences.is_empty(), "evidence is still collected");
    }

    #[test]
    fn verify_waf_verdict_without_context_blocks_t1() {
        // Degraded parity: a T1 challenge still blocks with no context.
        let verdict = verify_waf_verdict("Just a moment...", None, None, Default::default());
        assert!(verdict.is_blocked);
    }

    #[test]
    fn verify_waf_verdict_with_waf_status_blocks_t2() {
        // New capability: supplying a correlated WAF status (403) makes a
        // bare vendor name (T2) block.
        let verdict = verify_waf_verdict(
            "<html>blocked by akamai</html>",
            Some(403),
            Some("text/html".to_string()),
            Default::default(),
        );
        assert!(verdict.is_blocked, "T2 + 403 must block");
        assert!(verdict
            .evidences
            .iter()
            .any(|e| e.tier == WafTier::Fingerprint));
    }

    #[test]
    fn verify_waf_verdict_with_ok_status_passes_t2() {
        // New capability: the same T2 body at status 200 passes.
        let verdict = verify_waf_verdict(
            "<html>blocked by akamai</html>",
            Some(200),
            Some("text/html".to_string()),
            Default::default(),
        );
        assert!(!verdict.is_blocked, "T2 + 200 must pass");
    }

    // ========================================================================
    // ISSUE #599 / #628 — REQ-WAF-09 regression: Fingerprint (T2) NEVER blocks
    // without a correlated WAF status (403/429/503/520-529), even in degraded
    // mode and at status 200. The pattern "Checking your browser" was
    // mis-classified as Challenge-tier in #599-era code; it is a generic phrase
    // that appears in benign content (articles about Cloudflare) and was
    // reclasified to Fingerprint (#628). These tests (two regression guards)
    // pin the genuine REQ-WAF-09 contract for T2 evidence so a future change
    // cannot regress into mere-presence blocking.
    // ========================================================================

    #[test]
    fn issue_599_fingerprint_body_degraded_never_blocks() {
        // DEGRADED (no status/context): a body mentioning a WAF vendor without a
        // correlated WAF status must NOT block (REQ-WAF-09). Here the text is a
        // benign "Powered by Cloudflare Ray ID" mention; even if a T2 fingerprint
        // matched, degraded mode never blocks on mere presence.
        let verdict = verify_waf_verdict(
            "<html><body>Powered by Cloudflare Ray ID: abc123</body></html>",
            None,
            None,
            Default::default(),
        );
        assert!(
            !verdict.is_blocked,
            "vendor mention must not block in degraded mode"
        );
    }

    #[test]
    fn issue_628_fingerprint_body_does_not_block_at_200() {
        // Issue #628: "Checking your browser" was reclasified from Challenge to
        // Fingerprint. With status 200 (no WAF correlation) it must NOT block —
        // a legitimate page citing this phrase would be a false positive.
        // Fingerprint evidence is collected but the verdict is not blocked.
        let verdict = verify_waf_verdict(
            "Checking your browser before accessing. Powered by Cloudflare Ray ID: abc",
            Some(200),
            Some("text/html".to_string()),
            Default::default(),
        );
        assert!(
            !verdict.is_blocked,
            "fingerprint must not block at status 200 (REQ-WAF-09)"
        );
        assert!(
            verdict.evidences.iter().any(|e| e.provider == "Cloudflare"),
            "fingerprint evidence should still be collected"
        );
    }

    #[test]
    fn issue_628_fingerprint_body_blocks_with_correlated_status() {
        // Fingerprint-tier blocks when correlated with a WAF status (403/429/503/520-529).
        let verdict = verify_waf_verdict(
            "Checking your browser before accessing. Powered by Cloudflare Ray ID: abc",
            Some(403),
            Some("text/html".to_string()),
            Default::default(),
        );
        assert!(
            verdict.is_blocked,
            "fingerprint must block with correlated WAF status (REQ-WAF-09)"
        );
    }

    // ========================================================================
    // get_scrape_metrics — render_metrics honest rendering (REQ-04/05/10)
    // ========================================================================

    /// REQ-05/REQ-10: an empty accumulator renders an honest Spanish
    /// pre-condition error (isError:true) — NOT the legacy canned success JSON.
    #[test]
    fn render_metrics_empty_is_honest_spanish_error() {
        use crate::mcp_server::metrics::ScrapeMetrics;

        let snapshot = ScrapeMetrics::default().snapshot();
        assert_eq!(snapshot.total_events, 0, "fresh accumulator is empty");
        let result = render_metrics(&snapshot);

        // Serialize exactly as the MCP transport would, then assert the honest
        // error contract (mirrors export.rs load_results_from_none test).
        let json = serde_json::to_value(&result).expect("CallToolResult must serialize");
        assert_eq!(
            json.get("isError").and_then(|v| v.as_bool()),
            Some(true),
            "empty metrics must set isError:true, got: {json}"
        );
        let text = json
            .get("content")
            .and_then(|c| c.as_array())
            .and_then(|arr| arr.first())
            .and_then(|first| first.get("text"))
            .and_then(|t| t.as_str())
            .unwrap_or_default();
        assert!(
            text.contains("no hay métricas disponibles"),
            "honest Spanish empty-state error expected, got: {text}"
        );
        assert!(
            !text.contains("Metrics collection requires active scraping session"),
            "legacy canned text must be gone, got: {text}"
        );
    }

    /// REQ-04: a populated snapshot renders as a JSON success (isError not
    /// true) carrying the real counts and per-domain breakdown.
    #[test]
    fn render_metrics_populated_is_json_success() {
        use crate::mcp_server::metrics::{Outcome, ScrapeEvent, ScrapeMetrics};
        use std::time::Duration;

        let mut metrics = ScrapeMetrics::default();
        metrics.record(ScrapeEvent {
            tool: "scrape_url",
            domain: "example.com".to_string(),
            outcome: Outcome::Success,
            count: 4,
            duration: Duration::from_millis(100),
            trace_id: None,
            correlation_id: None,
        });
        let snapshot = metrics.snapshot();
        let result = render_metrics(&snapshot);

        let json = serde_json::to_value(&result).expect("CallToolResult must serialize");
        assert_ne!(
            json.get("isError").and_then(|v| v.as_bool()),
            Some(true),
            "populated metrics must not be an error, got: {json}"
        );
        let text = json
            .get("content")
            .and_then(|c| c.as_array())
            .and_then(|arr| arr.first())
            .and_then(|first| first.get("text"))
            .and_then(|t| t.as_str())
            .unwrap_or_default();
        let parsed: serde_json::Value =
            serde_json::from_str(text).expect("content text must be valid JSON");
        assert_eq!(
            parsed.get("total_events").and_then(|v| v.as_u64()),
            Some(1),
            "real total_events expected, got: {parsed}"
        );
        assert!(
            parsed
                .get("domains")
                .and_then(|d| d.get("example.com"))
                .is_some(),
            "per-domain breakdown expected, got: {parsed}"
        );
    }

    // ========================================================================
    // Handler-method coverage (direct dispatch, no MCP server, no network).
    // The free functions above are already unit-tested; these exercise the
    // `#[tool]` wrappers (semaphore, McpState wiring, render) end-to-end.
    // ========================================================================

    use crate::mcp_server::state::McpState;
    use rmcp::handler::server::wrapper::Parameters;
    use rmcp::model::CallToolResult;
    use tempfile::TempDir;
    use webfang_core::di::Container;
    use webfang_core::domain::CrawlerConfig;
    use webfang_core::infrastructure::config::ScraperConfig;

    async fn super_test_container() -> (TempDir, Container) {
        let tmp = TempDir::new().expect("create temp dir");
        let crawler_config =
            CrawlerConfig::new(url::Url::parse("https://example.com").expect("valid url"));
        let scraper_config = ScraperConfig {
            output_dir: tmp.path().to_path_buf(),
            ..Default::default()
        };
        let container = Container::new(crawler_config, scraper_config)
            .await
            .expect("create container");
        (tmp, container)
    }

    fn result_text(result: &CallToolResult) -> String {
        serde_json::to_value(result)
            .ok()
            .and_then(|v| v.get("content").and_then(|c| c.as_array()).cloned())
            .and_then(|arr| arr.first().cloned())
            .and_then(|first| {
                first
                    .get("text")
                    .and_then(|t| t.as_str())
                    .map(str::to_owned)
            })
            .unwrap_or_default()
    }

    #[tokio::test]
    async fn detect_waf_handler_detects_challenge() {
        let (_tmp, container) = super_test_container().await;
        let handler = McpHandler::new(McpState::new(container));
        let html = r#"<div id="cf-turnstile" data-sitekey="abc"></div>"#;
        let res = handler
            .detect_waf(Parameters(DetectWafParams {
                html: html.to_string(),
            }))
            .await
            .expect("detect_waf returns Ok");
        let text = result_text(&res);
        assert!(
            text.contains("WAF detected"),
            "challenge must be detected: {text}"
        );
    }

    #[tokio::test]
    async fn detect_waf_handler_clean_body() {
        let (_tmp, container) = super_test_container().await;
        let handler = McpHandler::new(McpState::new(container));
        let res = handler
            .detect_waf(Parameters(DetectWafParams {
                html: "<html><body>clean</body></html>".to_string(),
            }))
            .await
            .expect("detect_waf returns Ok");
        let text = result_text(&res);
        assert_eq!(text, "no WAF detected", "clean body: {text}");
    }

    #[tokio::test]
    async fn verify_waf_integrity_handler_blocks_with_status() {
        let (_tmp, container) = super_test_container().await;
        let handler = McpHandler::new(McpState::new(container));
        let res = handler
            .verify_waf_integrity(Parameters(VerifyWafIntegrityParams {
                html: Some("<html>blocked by akamai</html>".to_string()),
                headers: None,
                status: Some(403),
                content_type: Some("text/html".to_string()),
            }))
            .await
            .expect("verify_waf_integrity returns Ok");
        let text = result_text(&res);
        assert!(text.contains("WAF blocked"), "T2 + 403 must block: {text}");
    }

    #[tokio::test]
    async fn verify_waf_integrity_handler_passes_without_context() {
        let (_tmp, container) = super_test_container().await;
        let handler = McpHandler::new(McpState::new(container));
        let res = handler
            .verify_waf_integrity(Parameters(VerifyWafIntegrityParams {
                html: Some("<html>clean</html>".to_string()),
                headers: None,
                status: None,
                content_type: None,
            }))
            .await
            .expect("verify_waf_integrity returns Ok");
        let text = result_text(&res);
        assert!(
            text.contains("integrity check passed"),
            "clean body without context passes: {text}"
        );
    }

    #[tokio::test]
    async fn list_waf_providers_handler_returns_list() {
        let (_tmp, container) = super_test_container().await;
        let handler = McpHandler::new(McpState::new(container));
        let res = handler
            .list_waf_providers()
            .await
            .expect("list_waf_providers returns Ok");
        let text = result_text(&res);
        assert!(!text.is_empty(), "providers list must be non-empty");
    }

    #[tokio::test]
    async fn get_scrape_metrics_handler_empty_is_honest_error() {
        let (_tmp, container) = super_test_container().await;
        let handler = McpHandler::new(McpState::new(container));
        let res = handler
            .get_scrape_metrics()
            .await
            .expect("get_scrape_metrics returns Ok");
        let json = serde_json::to_value(&res).expect("serialize");
        assert_eq!(
            json.get("isError").and_then(|v| v.as_bool()),
            Some(true),
            "empty metrics must be an honest error: {json}"
        );
    }

    #[tokio::test]
    async fn get_scrape_metrics_handler_populated_is_json() {
        let (_tmp, container) = super_test_container().await;
        let state = McpState::new(container);
        let handler = McpHandler::new(state.clone());
        use crate::mcp_server::metrics::{Outcome, ScrapeEvent};
        use std::time::Duration;
        state.record_scrape(ScrapeEvent {
            tool: "scrape_url",
            domain: "example.com".to_string(),
            outcome: Outcome::Success,
            count: 1,
            duration: Duration::from_millis(5),
            trace_id: None,
            correlation_id: None,
        });
        let res = handler
            .get_scrape_metrics()
            .await
            .expect("get_scrape_metrics returns Ok");
        let text = result_text(&res);
        assert!(
            text.contains("total_events"),
            "populated metrics must render JSON: {text}"
        );
    }
}
