//! URL Utility tools — 6 tools for URL manipulation
//!
//! Tools: validate_url, extract_domain, normalize_url,
//! match_url_pattern, is_internal_link, url_to_file_path

use super::McpHandler;
use crate::mcp_server::params::*;
use rmcp::handler::server::tool::ToolRouter;
use rmcp::handler::server::wrapper::Parameters;
use rmcp::tool;
use rmcp::tool_router;
use rmcp::{model::CallToolResult, model::Content, ErrorData as McpError};
use tracing::instrument;

#[tool_router(router = tool_router_url_utils, vis = "pub")]
// Allow: the `tool_router_url_utils` fn generated by rmcp-macros cannot be documented from this crate.
#[allow(missing_docs)]
impl McpHandler {
    /// Validate and parse a URL (RFC 3986 compliant)
    #[tool(
        description = "Validate and parse a URL. Returns parsed components (scheme, host, port, path, query) or error details."
    )]
    #[instrument(skip(self), fields(url = %params.url))]
    // serde_json::to_string cannot fail for a serde_json::Value.
    #[allow(clippy::expect_used)]
    async fn validate_url(
        &self,
        Parameters(params): Parameters<ValidateUrlParams>,
    ) -> Result<CallToolResult, McpError> {
        let _permit = acquire_semaphore!(self, url_utils);

        match url::Url::parse(&params.url) {
            Ok(u) => {
                let info = serde_json::json!({
                    "valid": true,
                    "scheme": u.scheme(),
                    "host": u.host_str().unwrap_or(""),
                    "port": u.port(),
                    "path": u.path(),
                    "query": u.query().unwrap_or(""),
                });
                Ok(CallToolResult::success(vec![Content::text(
                    serde_json::to_string_pretty(&info)
                        .expect("serializing JSON to a string cannot fail"),
                )]))
            },
            Err(e) => {
                let info = serde_json::json!({"valid": false, "error": e.to_string()});
                Ok(CallToolResult::success(vec![Content::text(
                    serde_json::to_string_pretty(&info)
                        .expect("serializing JSON to a string cannot fail"),
                )]))
            },
        }
    }

    /// Extract domain/host from a URL
    #[tool(
        description = "Extract the domain (host) from a URL. E.g., 'https://www.example.com/path' → 'www.example.com'."
    )]
    #[instrument(skip(self), fields(url = %params.url))]
    async fn extract_domain(
        &self,
        Parameters(params): Parameters<ExtractDomainParams>,
    ) -> Result<CallToolResult, McpError> {
        let _permit = acquire_semaphore!(self, url_utils);

        match url::Url::parse(&params.url) {
            Ok(u) => {
                let domain = u.host_str().unwrap_or("");
                Ok(CallToolResult::success(vec![Content::text(domain)]))
            },
            Err(e) => Ok(CallToolResult::error(vec![Content::text(e.to_string())])),
        }
    }

    /// Normalize a URL (remove fragments, preserve trailing slashes, remove default ports)
    #[tool(
        description = "Normalize a URL by removing fragments, preserving trailing slashes, and removing default ports."
    )]
    #[instrument(skip(self), fields(url = %params.url))]
    async fn normalize_url(
        &self,
        Parameters(params): Parameters<NormalizeUrlParams>,
    ) -> Result<CallToolResult, McpError> {
        let _permit = acquire_semaphore!(self, url_utils);

        // Delegate to core normalize_url with strip_www=false (MCP preserves www prefix)
        let normalized = webfang_core::infrastructure::crawler::normalize_url(&params.url, false);

        // Core returns as-is for non-URLs; MCP tool reports error for invalid input
        if !params.url.contains("://") {
            return Ok(CallToolResult::error(vec![Content::text(
                "Invalid URL: no scheme found".to_string(),
            )]));
        }

        Ok(CallToolResult::success(vec![Content::text(normalized)]))
    }

    /// Match a URL against a glob pattern
    #[tool(
        description = "Check if a URL matches a glob-style pattern. Supports path patterns (start with '/') and host patterns."
    )]
    #[instrument(skip(self), fields(url = %params.url, pattern = %params.pattern))]
    async fn match_url_pattern(
        &self,
        Parameters(params): Parameters<MatchUrlPatternParams>,
    ) -> Result<CallToolResult, McpError> {
        let _permit = acquire_semaphore!(self, url_utils);

        let matches = webfang_core::domain::matches_pattern(&params.url, &params.pattern);
        Ok(CallToolResult::success(vec![Content::text(
            matches.to_string(),
        )]))
    }

    /// Check if a URL is internal to a seed domain
    #[tool(
        description = "Check if a URL belongs to the same domain (or subdomain) as the seed domain."
    )]
    #[instrument(skip(self), fields(url = %params.url, seed_domain = %params.seed_domain))]
    async fn is_internal_link(
        &self,
        Parameters(params): Parameters<IsInternalLinkParams>,
    ) -> Result<CallToolResult, McpError> {
        let _permit = acquire_semaphore!(self, url_utils);

        let is_internal = webfang_core::domain::url_validation::is_internal_link(
            &params.url,
            &params.seed_domain,
        );
        Ok(CallToolResult::success(vec![Content::text(
            is_internal.to_string(),
        )]))
    }

    /// Convert a URL to a domain-based file path
    #[tool(
        description = "Convert a URL to a domain-based file path. E.g., 'https://example.com/docs/page' → './output/example.com/docs/docs-page.md'. Path segments are flattened into the filename."
    )]
    #[instrument(skip(self), fields(url = %params.url))]
    // serde_json::to_string cannot fail for a serde_json::Value.
    #[allow(clippy::expect_used)]
    async fn url_to_file_path(
        &self,
        Parameters(params): Parameters<ValidateUrlParams>,
    ) -> Result<CallToolResult, McpError> {
        let _permit = acquire_semaphore!(self, url_utils);

        match webfang_core::adapters::url_path::OutputPath::from_url(&params.url) {
            Ok(output_path) => {
                let info = serde_json::json!({
                    "full_path": output_path.to_full_path(),
                    "relative_path": output_path.to_folder_path(),
                    "domain": output_path.domain().to_string(),
                });
                Ok(CallToolResult::success(vec![Content::text(
                    serde_json::to_string_pretty(&info)
                        .expect("serializing JSON to a string cannot fail"),
                )]))
            },
            Err(e) => Ok(CallToolResult::error(vec![Content::text(e.to_string())])),
        }
    }
}

/// Build the URL utility router (6 tools for URL manipulation).
///
/// Returns a partial router that is combined with the other category routers
/// via the `+` operator in
/// [`build_tool_router`](crate::mcp_server::handlers::build_tool_router).
pub fn build_router() -> ToolRouter<McpHandler> {
    McpHandler::tool_router_url_utils()
}

#[cfg(test)]
mod tests {
    use webfang_core::domain::url_validation::normalize_seed_host;

    #[test]
    fn normalize_seed_host_bare_domain() {
        assert_eq!(normalize_seed_host("example.com"), "example.com");
    }

    #[test]
    fn normalize_seed_host_with_scheme() {
        assert_eq!(normalize_seed_host("https://example.com"), "example.com");
    }

    #[test]
    fn normalize_seed_host_with_scheme_and_path() {
        assert_eq!(
            normalize_seed_host("https://example.com/path"),
            "example.com"
        );
    }

    #[test]
    fn normalize_seed_host_bare_with_path() {
        assert_eq!(normalize_seed_host("example.com/path"), "example.com");
    }

    #[test]
    fn normalize_seed_host_subdomain() {
        assert_eq!(normalize_seed_host("blog.example.com"), "blog.example.com");
    }

    #[test]
    fn normalize_seed_host_with_scheme_subdomain() {
        assert_eq!(
            normalize_seed_host("https://blog.example.com"),
            "blog.example.com"
        );
    }

    #[test]
    fn normalize_seed_host_empty() {
        assert_eq!(normalize_seed_host(""), "");
    }

    // --- Integration-style tests for the classification logic ---

    fn classify(url: &str, seed_domain: &str) -> bool {
        webfang_core::domain::url_validation::is_internal_link(url, seed_domain)
    }

    #[test]
    fn internal_link_bare_domain() {
        assert!(classify("https://example.com/a", "example.com"));
    }

    #[test]
    fn internal_link_subdomain_bare() {
        assert!(classify("https://blog.example.com/x", "example.com"));
    }

    #[test]
    fn internal_link_with_scheme() {
        assert!(classify("https://example.com/a", "https://example.com"));
    }

    #[test]
    fn external_link() {
        assert!(!classify("https://otro.com/a", "example.com"));
    }

    #[test]
    fn internal_link_seed_with_path() {
        assert!(classify("https://example.com/a", "example.com/path"));
    }

    #[test]
    fn invalid_url_returns_false() {
        assert!(!classify("not-a-url", "example.com"));
    }

    #[test]
    fn port_in_url_does_not_break() {
        assert!(classify("https://example.com:8080/a", "example.com"));
    }
}
