//! Adapter-layer behavioral tests for the `webfang` binary.
//!
//! Every test uses wiremock (no real network) and TempDir (auto-cleanup).
//! Run with: `cargo nextest run --test behavioral`

mod cli;

// The shared CLI harness lives at `tests/common/cli_harness.rs` (one directory
// up from this subdirectory crate). We point the module loader at it explicitly
// so the `cli/*` submodules keep resolving `crate::cmd`, `crate::BehavioralTest`,
// and friends.
#[path = "../common/cli_harness.rs"]
mod common;

// Re-export the centralized CLI behavioral harness so `cli/*` submodules can
// keep using `crate::cmd`, `crate::BehavioralTest`, and friends. (`webfang_path`
// and `redact_temp_path` stay crate-private in `common` — only `cli_harness.rs`
// needs them directly.)
pub(crate) use crate::common::{cmd, redact_nondeterministic, BehavioralTest};

use insta::assert_snapshot;
use std::path::Path;

// Snapshot-assertion wrappers stay at the crate root on purpose: insta derives a
// snapshot's on-disk location from the module path where `assert_snapshot!`
// expands, so these must remain here to preserve `tests/behavioral/snapshots/`.
/// Assert a snapshot of `value`, redacting the harness temp dir and other
/// non-deterministic output (timestamps, dynamic ports, ANSI codes) first.
///
/// `dir` is the temp-dir path so the absolute temp location never leaks into
/// the committed snapshot. Pass a non-matching path when the run had no temp
/// dir (e.g. `Path::new("__no_temp__")`).
///
/// Uses `insta::Settings::add_filter` to collapse the frontmatter `date:`
/// field (a bare `YYYY-MM-DD` generated by `Utc::now()` in `frontmatter.rs`)
/// to `[DATE]`, matching the convention in `obsidian_test.rs` and
/// `cli_behavioral_test.rs`.
pub(crate) fn assert_snapshot_redacted(name: &str, dir: &Path, value: impl Into<String>) {
    let redacted = redact_nondeterministic(dir, &value.into());
    let mut settings = insta::Settings::clone_current();
    settings.add_filter(r"date: \d{4}-\d{2}-\d{2}", "date: [DATE]");
    settings.bind(|| {
        assert_snapshot!(name, redacted);
    });
}

/// Assert a snapshot of `value` with no path redaction.
///
/// Use for deterministic outputs that never embed the temp dir (e.g. `--help`,
/// `--version`, or stderr from a run that passed no `--output`).
pub(crate) fn assert_snapshot_plain(name: &str, value: impl Into<String>) {
    assert_snapshot!(name, value.into());
}
