#!/usr/bin/env bash
#
# ci_test_budget.sh — Phase 3 PR test-budget reporter (advisory, never a gate).
#
# Purpose: show the PR test budget — which areas changed, which test files
# protect them, and the estimated CI lane set. Runs the cheap filename-only
# classifier (default base/head), then joins its `affected` areas with the
# machine-readable inventory at docs/test-inventory.json (generated by
# scripts/ci_test_inventory.py — regenerate with
# `python3 scripts/ci_test_inventory.py` before reading the budget).
#
# Matching rule: a test file matches when its inventory `area` appears in
# the classifier `affected` CSV; `affected` containing `all` or `code`
# matches everything (fail-closed, mirrors the fast gate); `snapshot` in
# `affected` additionally matches every snapshot-using file. Area names
# come from scripts/ci_path_classifier.sh (docs, ci, code, ai, mcp, cli,
# core, crawler, downloader, tests, release, lock, snapshot, all).
#
# Usage: scripts/ci_test_budget.sh [--base-ref <ref>] [--head-ref <ref>]
# Exit code: always 0 (advisory reporter). Missing inventory or classifier
# failure degrades to a warning, never a red step. No cargo.
#
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLASSIFIER="$SCRIPT_DIR/ci_path_classifier.sh"
BASE_REF="origin/main"
HEAD_REF="HEAD"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --base-ref) BASE_REF="${2:?missing value for --base-ref}"; shift 2 ;;
    --head-ref) HEAD_REF="${2:?missing value for --head-ref}"; shift 2 ;;
    -h | --help) sed -n '2,20p' "$0"; exit 0 ;;
    *) echo "error: unknown argument '$1' (see --help)" >&2; exit 2 ;;
  esac
done

ROOT="$(git rev-parse --show-toplevel 2>/dev/null || echo "$SCRIPT_DIR/..")"
# The JSON's ignored_count is a per-file MENTION signal over crates/*/tests/
# only. It is deliberately not reconciled with the frozen budget enforced by
# scripts/check_ignored_guard.sh, which also covers src/ test modules and
# compares attributes vs doc/comment mentions per category (#1328). The
# inventory of record is docs/test-inventory.md; do not read a sum mismatch
# here as drift.
INVENTORY="$ROOT/docs/test-inventory.json"

CLASS_OUT=""
if ! CLASS_OUT="$(bash "$CLASSIFIER" --base-ref "$BASE_REF" --head-ref "$HEAD_REF" --format github 2>/dev/null)"; then
  echo "test-budget: warning: classifier failed; failing closed to affected=all" >&2
  CLASS_OUT="affected=all
run_code_jobs=true
needs_ai=true
needs_mcp=true
snapshot_changed=false"
fi

# Never blind-source tool output: read only the five known keys.
affected="all" run_code_jobs="true" needs_ai="true" needs_mcp="true" snapshot_changed="false"
for key in affected run_code_jobs needs_ai needs_mcp snapshot_changed; do
  val="$(printf '%s\n' "$CLASS_OUT" | grep -E "^${key}=" | tail -1 | cut -d= -f2)"
  if [[ -n "$val" ]]; then printf -v "$key" '%s' "$val"; fi
done

if [[ ! -f "$INVENTORY" ]]; then
  echo "test-budget: warning: inventory absent ($INVENTORY); regenerate with: python3 scripts/ci_test_inventory.py" >&2
  echo "test-budget: affected areas: $affected"
  echo "test-budget: estimated CI lanes: run_code_jobs=$run_code_jobs needs_ai=$needs_ai needs_mcp=$needs_mcp snapshot_changed=$snapshot_changed"
  exit 0
fi

AFFECTED="$affected" python3 - "$INVENTORY" <<'EOF'
import json, sys

inventory_path = sys.argv[1]
affected = {a for a in __import__("os").environ.get("AFFECTED", "").split(",") if a}
data = json.load(open(inventory_path, encoding="utf-8"))
files = data.get("files", [])

match_all = bool(affected & {"all", "code"})

def matches(entry):
    if match_all:
        return True
    if entry.get("area") in affected:
        return True
    if "snapshot" in affected and entry.get("snapshot_usage"):
        return True
    return False

matched = [e for e in files if matches(e)]
total = sum(e.get("test_count", 0) for e in matched)
ignored = sum(e.get("ignored_count", 0) for e in matched)
snap_files = [e for e in matched if e.get("snapshot_usage")]

print(f"test-budget: affected areas: {','.join(sorted(affected))}")
print(f"test-budget: matching test files ({len(matched)}):")
for e in matched:
    snap = "yes" if e.get("snapshot_usage") else "no"
    print(f"  {e['path']} (area={e['area']} tests={e['test_count']} "
          f"ignored={e['ignored_count']} snapshots={snap} tier={e['tier']})")
print(f"test-budget: totals: files={len(matched)} tests={total} ignored={ignored} "
      f"snapshot_files={len(snap_files)}")
EOF

echo "test-budget: estimated CI lanes: run_code_jobs=$run_code_jobs needs_ai=$needs_ai needs_mcp=$needs_mcp snapshot_changed=$snapshot_changed"
exit 0
